*---------------------------------------------------------------
* Generated by cobc from tests/arith.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY is served by our own COBRT runtime, below.
*---------------------------------------------------------------
ARITH    CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                establish addressability
         USING *,12
         ST    13,SAVEAREA+4       backward chain to caller
         LA    11,SAVEAREA
         ST    11,8(13)            forward chain from caller
         LR    13,11               our save area is now current
* ADD P1 -> P2
         ZAP   PWK1(8),P2(4)
         ZAP   PWK2(8),P1(4)
         AP    PWK1(8),PWK2(8)
         ZAP   P2(4),PWK1(8)
* MOVE P2 -> R1
         ZAP   PWK1(8),P2(4)
         UNPK  R1(9),PWK1(8)       packed -> zoned
         OI    R1+8,X'F0'          unsigned: force an F zone
* DISPLAY R1
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* ADD P3 -> P2
         ZAP   PWK1(8),P2(4)
         ZAP   PWK2(8),P3(4)
         SRP   PWK2(8),1,0         align scale (left)
         AP    PWK1(8),PWK2(8)
         ZAP   P2(4),PWK1(8)
* MOVE P2 -> R3
         ZAP   PWK1(8),P2(4)
         UNPK  R3(9),PWK1(8)       packed -> zoned
         OI    R3+8,X'F0'          unsigned: force an F zone
* DISPLAY R3
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
* ADD B2 -> B1
         L     2,B1
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         L     2,B2
         CVD   2,DWK               binary -> packed
         ZAP   PWK2(8),DWK(8)
         AP    PWK1(8),PWK2(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         ST    2,B1
* MOVE B1 -> R2
         L     2,B1
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         UNPK  R2(9),PWK1(8)       packed -> zoned
         OI    R2+8,X'F0'          unsigned: force an F zone
* DISPLAY R2
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
* SUBTRACT P1 -> Z1
         PACK  PWK1(8),Z1(7)       zoned -> packed
         ZAP   PWK2(8),P1(4)
         SP    PWK1(8),PWK2(8)
         UNPK  Z1(7),PWK1(8)       packed -> zoned
* MOVE Z1 -> R4
         PACK  PWK1(8),Z1(7)       zoned -> packed
         UNPK  R4(9),PWK1(8)       packed -> zoned
         OI    R4+8,X'F0'          unsigned: force an F zone
* DISPLAY R4
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
* ADD 005 -> SC
         ZAP   PWK1(8),SC(2)
         SRP   PWK1(8),1,0         align scale (left)
         ZAP   PWK2(8),IMM0001(8)  literal
         AP    PWK1(8),PWK2(8)
         SRP   PWK1(8),63,0        align scale (right)
         ZAP   SC(2),PWK1(8)
* ADD 005 -> SC
         ZAP   PWK1(8),SC(2)
         SRP   PWK1(8),1,0         align scale (left)
         ZAP   PWK2(8),IMM0002(8)  literal
         AP    PWK1(8),PWK2(8)
         SRP   PWK1(8),63,0        align scale (right)
         ZAP   SC(2),PWK1(8)
* MOVE SC -> R5
         ZAP   PWK1(8),SC(2)
         UNPK  R5(4),PWK1(8)       packed -> zoned
         OI    R5+3,X'F0'          unsigned: force an F zone
* DISPLAY R5
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(R1)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'9'
PARM0002 DC    A(R3)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'9'
PARM0003 DC    A(R2)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'9'
PARM0004 DC    A(R4)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'9'
IMM0001  DC    PL8'005'
IMM0002  DC    PL8'005'
PARM0005 DC    A(R5)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'4'
* WORKING-STORAGE
P1       DC    PL4'12345'          PIC S7 digits scale 2 COMP-3
P2       DC    PL4'6789'           PIC S7 digits scale 2 COMP-3
P3       DC    PL4'105'            PIC S6 digits scale 1 COMP-3
B1       DC    F'1000'             PIC S7 digits scale 0 COMP
B2       DC    F'250'              PIC S7 digits scale 0 COMP
Z1       DC    ZL7'9999'           PIC S7 digits scale 2 DISPLAY
SC       DC    PL2'00'             PIC S2 digits scale 1 COMP-3
R1       DC    ZL9'000'            PIC 9 digits scale 2 DISPLAY
R2       DC    ZL9'0'              PIC 9 digits scale 0 DISPLAY
R3       DC    ZL9'000'            PIC 9 digits scale 2 DISPLAY
R4       DC    ZL9'000'            PIC 9 digits scale 2 DISPLAY
R5       DC    ZL4'00'             PIC 4 digits scale 1 DISPLAY
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
SAVEAREA DS    18F
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at the line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
