*---------------------------------------------------------------
* Generated by cobc370 from callsub.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
*---------------------------------------------------------------
CALLSUB  CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
B0000    EQU   COBBEG              the first code block
         USING COBBEG,12
         B     PRO001
PROCON   DC    A(COBCON)
PRO001   L     11,PROCON           the constants region
         LA    10,2048(,11)        and its second 4K
         LA    10,2048(,10)
         USING COBCON,11
         USING COBCON+4096,10
         LA    9,2048(,10)         and its third 4K: one data base is e
         LA    9,2048(,9)
         USING COBCON+8192,9
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
         SR    0,0
         SPM   0                   no overflow interrupts: high-order t
         CLI   SPIEDONE,X'01'      already armed?
         BE    SPIEARMD            the macro is several instructions: a
         SPIE  COBSPIE,((1,7),9,(11,12),15)  report program checks by l
         MVI   SPIEDONE,X'01'
SPIEARMD DS    0H
T0000    DS    0H
* MOVE ABCD -> T
         LA    6,0                 subscript-1
         MH    6,H0001             times element size
         L     8,BL0000            base locator
         USING WSC0000,8
         LA    6,D0001(6)          element address
         MVC   0(4,6),S0001        literal move, space padded
T0001    DS    0H
* MOVE ABCD -> T
         LA    6,1                 subscript-1
         MH    6,H0001             times element size
         LA    6,D0001(6)          element address
         MVC   0(4,6),S0001        literal move, space padded
T0002    DS    0H
* MOVE ABCD -> T
         LA    6,2                 subscript-1
         MH    6,H0001             times element size
         LA    6,D0001(6)          element address
         MVC   0(4,6),S0001        literal move, space padded
T0003    DS    0H
* CALL 'FOO'
         LA    6,0                 subscript-1
         MH    6,H0001             times element size
         LA    6,D0001(6)          element address
         LA    0,0(,6)             T
         ST    0,PL003+0
         OI    PL003+0,X'80'       high bit marks the last argument
         LA    1,PL003             R1 -> parameter list
         L     15,VC003
         BALR  14,15               static call, resolved by the linkage
         STH   15,D0002            the callee's return code -> RETURN-C
T0004    DS    0H
* STOP RUN
         LH    15,D0002            RETURN-CODE -> the step's condition
         L     13,4(13)            restore caller's save area
         L     14,12(13)           caller's return address
         LM    0,12,20(13)         caller's R0-R12; R15 keeps the code
         BR    14                  return to caller
* end of the Procedure Division: an implicit STOP RUN
* STOP RUN
         LH    15,D0002            RETURN-CODE -> the step's condition
         L     13,4(13)            restore caller's save area
         L     14,12(13)           caller's return address
         LM    0,12,20(13)         caller's R0-R12; R15 keeps the code
         BR    14                  return to caller
         DROP  12
COBCON   DS    0D                  constants, work areas, out-of-line c
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL16
PWK2     DS    PL16
EDSRC    DS    PL16                ED source, sized to the selectors
EDWK     DS    CL64                ED pattern and result
ZWK      DS    CL24                zoned work area
MULT8    DS    PL8                 ** multiplier
QTMP     DS    PL16                DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
H0001    DC    H'4'                element sizes
S0001    DC    CL4'ABCD'           nonnumeric constants
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
* CALL parameter lists and entry points
PL003    DS    1F
VC003    DC    V(FOO)
SAVEAREA DS    18F
* program-check exit: report the source line, then let it abend
COBSPIE  DS    0H
         USING COBSPIE,15
         STM   14,12,SPIEREGS      R15 is our base on entry
         LR    9,15                keep a base across the WTO
         DROP  15
         USING COBSPIE,9
         LR    10,1                the PIE
*  the interruption code, as the digit people know it
         SR    7,7
         IC    7,7(,10)            low byte of the interruption code
         N     7,SPIE15
         LA    7,SPIEHEX(7)
         MVC   SPIECODE(1),0(7)
*  the interrupt address, as an offset into this module
         L     2,8(,10)            second word of the old PSW
         N     2,SPIEADR           leaves the instruction address
         S     2,SPIEBEG           relative to the entry point
*  the last table entry at or before it names the statement
         L     3,SPIETAB
         LH    4,SPIENUM
         SR    5,5                 no line yet
SPIELOOP LTR   4,4
         BZ    SPIEFND
         L     6,0(,3)             this statement's offset
         CR    6,2
         BH    SPIEFND             past it: the previous one is the ans
         LH    5,4(,3)
         LA    3,8(,3)
         BCTR  4,0
         B     SPIELOOP
SPIEFND  CVD   5,SPIEDW
         UNPK  SPIELINE(5),SPIEDW+5(3)
         OI    SPIELINE+4,X'F0'
         ST    2,SPIEDW            the offset, relative to COBBEG
         UNPK  SPIEOFF(7),SPIEDW+1(4)  low three bytes to zoned
         TR    SPIEOFF(6),SPIEHEXT  zoned to hex digits
         WTO   MF=(E,SPIEWTO)      into the job log, beside the abend
*  cancel the exit and back up to the failing instruction,
*  so the abend happens for real -- same code, same dump
         SR    2,2
         IC    2,7(,10)            the interruption code
         A     2,SPIE3000
         ABEND (2),DUMP
SPIEHEX  DC    C'0123456789ABCDEF'
SPIEHEXT DC    240X'00',C'0123456789ABCDEF'
SPIE15   DC    F'15'
SPIE3000 DC    F'3000'
SPIEADR  DC    X'00FFFFFF'
SPIEBEG  DC    A(COBBEG)
SPIETAB  DC    A(SPIELTB)
SPIENUM  DC    H'5'                statements in the table
SPIEREGS DS    15F
SPIEDONE DC    X'00'               1 once this module's SPIE is armed
SPIEDW   DS    D
SPIEWTO  WTO   'COBC370: PROGRAM CHECK 0C0 LINE 00000 OFFSET 000000',  X
               MF=L
SPIECODE EQU   SPIEWTO+29,1        the 0C? digit, patched above
SPIELINE EQU   SPIEWTO+36,5        the line number, likewise
SPIEOFF  EQU   SPIEWTO+49,7        the offset from COBBEG, in hex
         DS    0F
CB0000   DC    A(B0000)            a code block's base
         LTORG
* statement offsets, ascending, paired with source lines
SPIELTB  DS    0F
         DC    A(T0000-COBBEG),AL2(8,0)
         DC    A(T0001-COBBEG),AL2(8,0)
         DC    A(T0002-COBBEG),AL2(8,0)
         DC    A(T0003-COBBEG),AL2(9,0)
         DC    A(T0004-COBBEG),AL2(10,0)
         CSECT                     WORKING-STORAGE: private code, one p
COBWS    DS    0D
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DS    0CL12               TT (01 group)
D0001    DC    3CL4' '             T PIC X(4) table
D0002    DC    HL2'0'              RETURN-CODE PIC S9(4)v0 COMP
         END
