*---------------------------------------------------------------
* Generated by cobc from tests/compute.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY is served by our own COBRT runtime, below.
*---------------------------------------------------------------
COMPTEST CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                establish addressability
         USING *,12
         ST    13,SAVEAREA+4       backward chain to caller
         LA    11,SAVEAREA
         ST    11,8(13)            forward chain from caller
         LR    13,11               our save area is now current
* COMPUTE R1 = ...
         ZAP   WK0(16),A(4)
         ZAP   WK1(16),B(4)
         L     2,C
         CVD   2,DWK               binary -> packed
         ZAP   WK2(16),DWK(8)
         ZAP   MULT8(8),WK2(16)    MP takes at most 8 bytes on the righ
         MP    WK1(16),MULT8(8)    scale becomes the sum of the scales
         AP    WK0(16),WK1(16)
         ZAP   PWK1(8),WK0(16)
         UNPK  R1(9),PWK1(8)       packed -> zoned
         OI    R1+8,X'F0'          unsigned: force an F zone
* COMPUTE R2 = ...
         ZAP   WK0(16),A(4)
         ZAP   WK1(16),B(4)
         AP    WK0(16),WK1(16)
         L     2,C
         CVD   2,DWK               binary -> packed
         ZAP   WK1(16),DWK(8)
         ZAP   MULT8(8),WK1(16)    MP takes at most 8 bytes on the righ
         MP    WK0(16),MULT8(8)    scale becomes the sum of the scales
         ZAP   PWK1(8),WK0(16)
         UNPK  R2(9),PWK1(8)       packed -> zoned
         OI    R2+8,X'F0'          unsigned: force an F zone
* COMPUTE R3 = ...
         ZAP   WK0(16),A(4)
         ZAP   WK1(16),B(4)
         SRP   WK0(16),6,0         align scale (left)
         ZAP   DIVR8(8),WK1(16)    DP takes at most 8 bytes on the righ
         DP    WK0(16),DIVR8(8)    quotient in the leading 8 bytes
         ZAP   QTMP(8),WK0(8)
         ZAP   WK0(16),QTMP(8)     drop the remainder
         SRP   WK0(16),60,0        align scale (right)
         ZAP   PWK1(8),WK0(16)
         UNPK  R3(9),PWK1(8)       packed -> zoned
         OI    R3+8,X'F0'          unsigned: force an F zone
* COMPUTE R4 ROUNDED = ...
         ZAP   WK0(16),A(4)
         ZAP   WK1(16),B(4)
         SRP   WK0(16),6,0         align scale (left)
         ZAP   DIVR8(8),WK1(16)    DP takes at most 8 bytes on the righ
         DP    WK0(16),DIVR8(8)    quotient in the leading 8 bytes
         ZAP   QTMP(8),WK0(8)
         ZAP   WK0(16),QTMP(8)     drop the remainder
         SRP   WK0(16),60,5        align scale (right, ROUNDED)
         ZAP   PWK1(8),WK0(16)
         UNPK  R4(9),PWK1(8)       packed -> zoned
         OI    R4+8,X'F0'          unsigned: force an F zone
* COMPUTE R5 = ...
         ZAP   WK1(16),B(4)
         ZAP   WK0(16),K0001(8)    unary minus
         SP    WK0(16),WK1(16)
         ZAP   WK1(16),A(4)
         AP    WK0(16),WK1(16)
         ZAP   PWK1(8),WK0(16)
         UNPK  R5(9),PWK1(8)       packed -> zoned
         OI    R5+8,X'F0'          unsigned: force an F zone
* COMPUTE R6 = ...
         ZAP   WK0(16),A(4)
         L     2,C
         CVD   2,DWK               binary -> packed
         ZAP   WK1(16),DWK(8)
         SRP   WK0(16),4,0         align scale (left)
         ZAP   DIVR8(8),WK1(16)    DP takes at most 8 bytes on the righ
         DP    WK0(16),DIVR8(8)    quotient in the leading 8 bytes
         ZAP   QTMP(8),WK0(8)
         ZAP   WK0(16),QTMP(8)     drop the remainder
         SRP   WK0(16),60,0        align scale (right)
         ZAP   PWK1(8),WK0(16)
         UNPK  R6(9),PWK1(8)       packed -> zoned
         OI    R6+8,X'F0'          unsigned: force an F zone
* COMPUTE R7 ROUNDED = ...
         ZAP   WK0(16),A(4)
         ZAP   WK1(16),B(4)
         AP    WK0(16),WK1(16)
         L     2,C
         CVD   2,DWK               binary -> packed
         ZAP   WK1(16),DWK(8)
         SRP   WK0(16),4,0         align scale (left)
         ZAP   DIVR8(8),WK1(16)    DP takes at most 8 bytes on the righ
         DP    WK0(16),DIVR8(8)    quotient in the leading 8 bytes
         ZAP   QTMP(8),WK0(8)
         ZAP   WK0(16),QTMP(8)     drop the remainder
         SRP   WK0(16),60,5        align scale (right, ROUNDED)
         ZAP   PWK1(8),WK0(16)
         UNPK  R7(9),PWK1(8)       packed -> zoned
         OI    R7+8,X'F0'          unsigned: force an F zone
* DISPLAY R1
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* DISPLAY R2
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
* DISPLAY R3
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
* DISPLAY R4
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
* DISPLAY R5
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
* DISPLAY R6
         LA    1,PARM0006
         L     15,VDISP
         BALR  14,15
* DISPLAY R7
         LA    1,PARM0007
         L     15,VDISP
         BALR  14,15
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(R1)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'9'
PARM0002 DC    A(R2)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'9'
PARM0003 DC    A(R3)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'9'
PARM0004 DC    A(R4)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'9'
PARM0005 DC    A(R5)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'9'
PARM0006 DC    A(R6)
         DC    X'80',AL3(LEN0006)  last parameter
LEN0006  DC    H'9'
PARM0007 DC    A(R7)
         DC    X'80',AL3(LEN0007)  last parameter
LEN0007  DC    H'9'
* WORKING-STORAGE
A        DC    PL4'10000'          PIC S7 digits scale 2 COMP-3
B        DC    PL4'600'            PIC S7 digits scale 2 COMP-3
C        DC    F'7'                PIC S5 digits scale 0 COMP
R1       DC    ZL9'000'            PIC 9 digits scale 2 DISPLAY
R2       DC    ZL9'000'            PIC 9 digits scale 2 DISPLAY
R3       DC    ZL9'000'            PIC 9 digits scale 2 DISPLAY
R4       DC    ZL9'000'            PIC 9 digits scale 2 DISPLAY
R5       DC    ZL9'000'            PIC 9 digits scale 2 DISPLAY
R6       DC    ZL9'000'            PIC 9 digits scale 2 DISPLAY
R7       DC    ZL9'000'            PIC 9 digits scale 2 DISPLAY
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
K0001    DC    PL8'0'              numeric constants
SAVEAREA DS    18F
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at the line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
