*---------------------------------------------------------------
* Generated by cobc370 from tests/edtest.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
EDTEST   CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* MAIN-PARA.
P0000    DS    0H
* MOVE SRC -> E1
         L     8,BL0000            base locator
         USING WSC0000,8
         ZAP   PWK1(8),D0000(6)
         ZAP   EDSRC(6),PWK1(8)    source, sized to the selector count
         MVC   EDWK(16),M0001      load the ED pattern
         LA    1,EDWK+2            default sign position
         EDMK  EDWK(16),EDSRC
         BCTR  1,0                 one left of the first significant di
         BNM   G0001               not negative?
         MVI   0(1),C'-'
G0001    DS    0H
         MVC   D0001(15),EDWK+1    the edited result
* DISPLAY
         MVC   DSPBUF+0(15),D0001
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* MOVE 123456 -> E2
         ZAP   PWK1(8),K0001(8)    literal
         ZAP   EDSRC(5),PWK1(8)    source, sized to the selector count
         MVC   EDWK(12),M0002      load the ED pattern
         ED    EDWK(12),EDSRC
         MVC   D0002(10),EDWK+2    the edited result
* DISPLAY
         MVC   DSPBUF+0(10),D0002
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
* MOVE 42 -> E3
         ZAP   PWK1(8),K0002(8)    literal
         ZAP   EDSRC(4),PWK1(8)    source, sized to the selector count
         MVC   EDWK(9),M0003       load the ED pattern
         ED    EDWK(9),EDSRC
         BNM   G0003               not negative?
         MVI   EDWK+3,C'-'
         B     G0004
G0003    MVI   EDWK+3,C'+'
G0004    DS    0H
         MVC   D0003(6),EDWK+3     the edited result
* DISPLAY
         MVC   DSPBUF+0(6),D0003
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
* MOVE 123456 -> E4
         ZAP   PWK1(8),K0001(8)    literal
         ZAP   EDSRC(5),PWK1(8)    source, sized to the selector count
         MVC   EDWK(12),M0004      load the ED pattern
         ED    EDWK(12),EDSRC
         MVC   D0004(10),EDWK+2    the edited result
* DISPLAY
         MVC   DSPBUF+0(10),D0004
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
* MOVE -98765 -> E5
         ZAP   PWK1(8),K0003(8)    literal
         ZAP   EDSRC(5),PWK1(8)    source, sized to the selector count
         MVC   EDWK(13),M0005      load the ED pattern
         LA    1,EDWK+3            default sign position
         EDMK  EDWK(13),EDSRC
         BCTR  1,0                 one left of the first significant di
         BNM   G0005               not negative?
         MVI   0(1),C'-'
G0005    DS    0H
         MVC   D0005(11),EDWK+2    the edited result
* DISPLAY
         MVC   DSPBUF+0(11),D0005
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'15'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'10'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'6'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'10'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'11'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
K0001    DC    PL8'123456'         numeric constants
K0002    DC    PL8'42'
K0003    DC    PL8'-98765'
M0001    DC    XL16'40402020206B2020206B2021204B2020'  ED patterns
M0002    DC    XL12'40202020206B2021204B2020'
M0003    DC    XL9'402021402020202020'
M0004    DC    XL12'5C202020206B2021204B2020'
M0005    DC    XL13'40204020206B2020206B202120'
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
SAVEAREA DS    18F
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DC    PL6'-123456789'     SRC PIC S9(11)v2 COMP-3
D0001    DC    CL15' '             E1 edited, 15 chars
D0002    DC    CL10' '             E2 edited, 10 chars
D0003    DC    CL6' '              E3 edited, 6 chars
D0004    DC    CL10' '             E4 edited, 10 chars
D0005    DC    CL11' '             E5 edited, 11 chars
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
