*---------------------------------------------------------------
* Generated by cobc370 from fdrecs.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
*---------------------------------------------------------------
FDRECS   CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
         SPIE  COBSPIE,((1,15))    report program checks by line
T0000    DS    0H
* OPEN OUTPUT OUT-FILE
         OPEN  (FD000,OUTPUT)
T0001    DS    0H
* MOVE HDR  -> H-TAG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(4),S0001      literal move, space padded
T0002    DS    0H
* MOVE A HEADER LINE              -> H-TEXT
         MVC   D0002(26),S0002     literal move, space padded
T0003    DS    0H
* WRITE HEADER-REC
         PUT   FD000,D0000
         DROP  8
L0002    DS    0H
T0004    DS    0H
* MOVE DTL  -> D-TAG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0004(4),S0003      literal move, space padded
T0005    DS    0H
* MOVE 42 -> D-NUM
         ZAP   PWK1(16),K0001(16)  literal
         UNPK  D0005(6),PWK1(16)   packed -> zoned
         OI    D0005+5,X'F0'       unsigned: force an F zone
T0006    DS    0H
* MOVE FORTY-TWO            -> D-NAME
         MVC   D0006(20),S0004     literal move, space padded
T0007    DS    0H
* WRITE DETAIL-REC
         PUT   FD000,D0000
         DROP  8
L0004    DS    0H
T0008    DS    0H
* MOVE WHOLEREC WRITTEN AS ONE FIELD  -> WHOLE-REC
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0007(30),S0005     literal move, space padded
T0009    DS    0H
* WRITE WHOLE-REC
         PUT   FD000,D0000
         DROP  8
L0006    DS    0H
T0010    DS    0H
* WRITE DETAIL-REC
*  FROM: fill the record area first
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(30),D0008     alphanumeric move
         PUT   FD000,D0000
         DROP  8
L0008    DS    0H
T0011    DS    0H
* WRITE WHOLE-REC
         L     8,BL0000            base locator
         USING WSC0000,8
         PUT   FD000,D0000
         DROP  8
L0010    DS    0H
T0012    DS    0H
* CLOSE OUT-FILE
         CLOSE (FD000)
T0013    DS    0H
* STOP RUN
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL16
PWK2     DS    PL16
EDSRC    DS    PL16                ED source, sized to the selectors
EDWK     DS    CL64                ED pattern and result
ZWK      DS    CL20                zoned, for a numeric to alphanumeric
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
* file control blocks
FD000    DCB   DDNAME=OUTFILE,DSORG=PS,MACRF=(PM),RECFM=FB,            X
               LRECL=30,BLKSIZE=30
K0001    DC    PL16'42'            numeric constants
S0001    DC    CL4'HDR '           nonnumeric constants
S0002    DC    CL26'A HEADER LINE             '
S0003    DC    CL4'DTL '
S0004    DC    CL20'FORTY-TWO           '
S0005    DC    CL30'WHOLEREC WRITTEN AS ONE FIELD '
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
SAVEAREA DS    18F
* program-check exit: report the source line, then let it abend
COBSPIE  DS    0H
         USING COBSPIE,15
         STM   14,12,SPIEREGS      R15 is our base on entry
         LR    9,15                keep a base across the WTO
         DROP  15
         USING COBSPIE,9
         LR    10,1                the PIE
*  the interruption code, as the digit people know it
         SR    7,7
         IC    7,7(,10)            low byte of the interruption code
         N     7,SPIE15
         LA    7,SPIEHEX(7)
         MVC   SPIECODE(1),0(7)
*  the interrupt address, as an offset into this module
         L     2,8(,10)            second word of the old PSW
         N     2,SPIEADR           leaves the instruction address
         S     2,SPIEBEG           relative to the entry point
*  the last table entry at or before it names the statement
         L     3,SPIETAB
         LH    4,SPIENUM
         SR    5,5                 no line yet
SPIELOOP LTR   4,4
         BZ    SPIEFND
         LH    6,0(,3)             this statement's offset
         CR    6,2
         BH    SPIEFND             past it: the previous one is the ans
         LH    5,2(,3)
         LA    3,4(,3)
         BCTR  4,0
         B     SPIELOOP
SPIEFND  CVD   5,SPIEDW
         UNPK  SPIELINE(5),SPIEDW+5(3)
         OI    SPIELINE+4,X'F0'
         WTO   MF=(E,SPIEWTO)      into the job log, beside the abend
*  cancel the exit and back up to the failing instruction,
*  so the abend happens for real -- same code, same dump
         SR    2,2
         IC    2,7(,10)            the interruption code
         A     2,SPIE3000
         ABEND (2),DUMP
SPIEHEX  DC    C'0123456789ABCDEF'
SPIE15   DC    F'15'
SPIE3000 DC    F'3000'
SPIEADR  DC    X'00FFFFFF'
SPIEBEG  DC    A(COBBEG)
SPIETAB  DC    A(SPIELTB)
SPIENUM  DC    H'14'               statements in the table
SPIEREGS DS    15F
SPIEDW   DS    D
SPIEWTO  WTO   'COBC370: PROGRAM CHECK 0C0 AT SOURCE LINE 00000',      X
               MF=L
SPIECODE EQU   SPIEWTO+29,1        the 0C? digit, patched above
SPIELINE EQU   SPIEWTO+46,5        the line number, likewise
* statement offsets, ascending, paired with source lines
SPIELTB  DS    0H
         DC    AL2(T0000-COBBEG),AL2(28)
         DC    AL2(T0001-COBBEG),AL2(29)
         DC    AL2(T0002-COBBEG),AL2(30)
         DC    AL2(T0003-COBBEG),AL2(31)
         DC    AL2(T0004-COBBEG),AL2(32)
         DC    AL2(T0005-COBBEG),AL2(33)
         DC    AL2(T0006-COBBEG),AL2(34)
         DC    AL2(T0007-COBBEG),AL2(35)
         DC    AL2(T0008-COBBEG),AL2(36)
         DC    AL2(T0009-COBBEG),AL2(37)
         DC    AL2(T0010-COBBEG),AL2(38)
         DC    AL2(T0011-COBBEG),AL2(41)
         DC    AL2(T0012-COBBEG),AL2(42)
         DC    AL2(T0013-COBBEG),AL2(43)
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DS    0CL30               HEADER-REC (01 group)
D0001    DC    CL4' '              H-TAG PIC X(4)
D0002    DC    CL26' '             H-TEXT PIC X(26)
D0003    EQU   COBWS+0             DETAIL-REC REDEFINES
D0004    EQU   COBWS+0             D-TAG REDEFINES
D0005    EQU   COBWS+4             D-NUM REDEFINES
D0006    EQU   COBWS+10            D-NAME REDEFINES
D0007    EQU   COBWS+0             WHOLE-REC REDEFINES
         DS    XL2                 reserve the rest of a table
D0008    DC    CL30'FROMBUILT IN WORKING-STORAGE  '  BUILT PIC X(30)
         END
