*---------------------------------------------------------------
* Generated by cobc370 from tests/figval.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
FIGVAL   CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* MAIN-PARA.
P0000    DS    0H
* DISPLAY
         MVC   DSPBUF+0(6),S0001
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+6(8),D0001
         MVC   DSPBUF+14(1),S0002
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* DISPLAY
         MVC   DSPBUF+0(6),S0003
         MVC   DSPBUF+6(1),D0003
         MVC   DSPBUF+7(1),S0002
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
* IF
         CLC   D0004(4),D0006      alphanumeric compare
         BNL   L0001
* DISPLAY
         MVC   DSPBUF+0(15),S0004
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
         B     L0002
         DROP  8
L0001    DS    0H
* DISPLAY
         MVC   DSPBUF+0(19),S0005
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
L0002    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0005(4),D0006      alphanumeric compare
         BNH   L0003
* DISPLAY
         MVC   DSPBUF+0(16),S0006
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
         B     L0004
         DROP  8
L0003    DS    0H
* DISPLAY
         MVC   DSPBUF+0(20),S0007
         LA    1,PARM0006
         L     15,VDISP
         BALR  14,15
L0004    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0004(4),D0005      alphanumeric compare
         BNL   L0005
* DISPLAY
         MVC   DSPBUF+0(14),S0008
         LA    1,PARM0007
         L     15,VDISP
         BALR  14,15
         B     L0006
         DROP  8
L0005    DS    0H
* DISPLAY
         MVC   DSPBUF+0(18),S0009
         LA    1,PARM0008
         L     15,VDISP
         BALR  14,15
L0006    DS    0H
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'15'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'8'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'15'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'19'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'16'
PARM0006 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0006)  last parameter
LEN0006  DC    H'20'
PARM0007 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0007)  last parameter
LEN0007  DC    H'14'
PARM0008 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0008)  last parameter
LEN0008  DC    H'18'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
S0001    DC    CL6'NAME ['         nonnumeric constants
S0002    DC    CL1']'
S0003    DC    CL6'MODE ['
S0004    DC    CL15'LOW BELOW SPACE'
S0005    DC    CL19'LOW NOT BELOW SPACE'
S0006    DC    CL16'HIGH ABOVE SPACE'
S0007    DC    CL20'HIGH NOT ABOVE SPACE'
S0008    DC    CL14'LOW BELOW HIGH'
S0009    DC    CL18'LOW NOT BELOW HIGH'
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
SAVEAREA DS    18F
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DS    0CL13               MB-BLOCK (01 group)
D0001    DC    CL8'LTF'            WS-MODULE-NAME PIC X(8)
D0002    DC    4X'00'              WS-MODULE-ADDR PIC X(4)
D0003    DC    CL1'K'              WS-CALL-MODE PIC X(1)
D0004    DC    4X'00'              WS-LOW PIC X(4)
D0005    DC    4X'FF'              WS-HIGH PIC X(4)
D0006    DC    CL4' '              WS-SPC PIC X(4)
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
