*---------------------------------------------------------------
* Generated by cobc370 from tests/filetest.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY is served by our own COBRT runtime, below.
*---------------------------------------------------------------
FILETEST CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                establish addressability
         USING *,12
         ST    13,SAVEAREA+4       backward chain to caller
         LA    11,SAVEAREA
         ST    11,8(13)            forward chain from caller
         LR    13,11               our save area is now current
* MAIN-PARA.
P0000    DS    0H
* OPEN INPUT IN-FILE
         OPEN  (FD000,INPUT)
* OPEN OUTPUT OUT-FILE
         OPEN  (FD001,OUTPUT)
* PERFORM READ-PARA THRU READ-EXIT
         LA    15,R0001            return here
         ST    15,X0002            into the range's exit cell
         B     P0001
R0001    DS    0H
         LA    15,F0002            restore fall-through
         ST    15,X0002
* CLOSE IN-FILE
         CLOSE (FD000)
* CLOSE OUT-FILE
         CLOSE (FD001)
* MOVE REC-COUNT -> OUT-NUM
         L     2,D0002
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         UNPK  D0003(5),PWK1(8)    packed -> zoned
         OI    D0003+4,X'F0'       unsigned: force an F zone
* DISPLAY OUT-NUM
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* READ-PARA.
P0001    DS    0H
* READ IN-FILE
         LA    1,L0001             this READ's AT END
         STCM  1,7,FD000+33        into DCBEODAD
         GET   FD000,D0000         QSAM move mode
         B     L0002
L0001    DS    0H                  AT END
* GO TO READ-EXIT
         B     P0002
L0002    DS    0H
* ADD 1 -> REC-COUNT
         L     2,D0002
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         ZAP   PWK2(8),K0001(8)    literal
         AP    PWK1(8),PWK2(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         ST    2,D0002
* MOVE IN-REC -> OUT-REC
         MVC   D0001(80),D0000     alphanumeric move
* WRITE OUT-REC
         PUT   FD001,D0001
* GO TO READ-PARA
         B     P0001
* READ-EXIT.
P0002    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0002
         BR    15
F0002    DS    0H                  fall-through when not performed
X0002    DC    A(F0002)            READ-EXIT
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(D0003)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'5'
* WORKING-STORAGE
D0000    DC    CL80' '             IN-REC PIC X(80)
D0001    DC    CL80' '             OUT-REC PIC X(80)
D0002    DC    F'0'                REC-COUNT PIC S9(5)v0 COMP
D0003    DC    ZL5'0'              OUT-NUM PIC 9(5)v0 DISP
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
* file control blocks
FD000    DCB   DDNAME=INFILE,DSORG=PS,MACRF=(GM),RECFM=FB,             X
               LRECL=80,BLKSIZE=80
FD001    DCB   DDNAME=OUTFILE,DSORG=PS,MACRF=(PM),RECFM=FB,            X
               LRECL=80,BLKSIZE=80
K0001    DC    PL8'1'              numeric constants
SAVEAREA DS    18F
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
