*---------------------------------------------------------------
* Generated by cobc370 from tests/grpperf.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
GRPPERF  CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* MAIN-PARA.
P0000    DS    0H
* PERFORM ADD-PARA THRU ADD-EXIT
         LA    15,R0001            return here
         ST    15,X0002            into the range's exit cell
         B     P0001
R0001    DS    0H
         LA    15,F0002            restore fall-through
         ST    15,X0002
* PERFORM ADD-PARA THRU ADD-EXIT
         LA    15,R0002            return here
         ST    15,X0002            into the range's exit cell
         B     P0001
R0002    DS    0H
         LA    15,F0002            restore fall-through
         ST    15,X0002
* PERFORM ADD-PARA THRU ADD-EXIT
         LA    15,R0003            return here
         ST    15,X0002            into the range's exit cell
         B     P0001
R0003    DS    0H
         LA    15,F0002            restore fall-through
         ST    15,X0002
* MOVE CUSTOMER-REC -> SAVE-REC
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0004(16),D0000     alphanumeric move
* MOVE SAVE-NAME -> OUT-NAME
         MVC   D0009(9),D0005      alphanumeric move
* DISPLAY
         MVC   DSPBUF+0(9),D0009
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* MOVE SAVE-BAL -> OUT-NUM
         ZAP   PWK1(8),D0007(4)
         UNPK  D0011(7),PWK1(8)    packed -> zoned
         OI    D0011+6,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(7),D0011
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
* MOVE COUNTER -> OUT-NUM
         LH    2,D0008
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         SRP   PWK1(8),2,0         align scale (left)
         UNPK  D0011(7),PWK1(8)    packed -> zoned
         OI    D0011+6,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(7),D0011
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
* PERFORM SHOW-PARA
         LA    15,R0004            return here
         ST    15,X0003            into the range's exit cell
         B     P0003
R0004    DS    0H
         DROP  8
         LA    15,F0003            restore fall-through
         ST    15,X0003
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* ADD-PARA.
P0001    DS    0H
* ADD 1 -> COUNTER
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0008
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         ZAP   PWK2(8),K0001(8)    literal
         AP    PWK1(8),PWK2(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         STH   2,D0008
* ADD 1050 -> CUST-BAL
         ZAP   PWK1(8),D0003(4)
         ZAP   PWK2(8),K0002(8)    literal
         AP    PWK1(8),PWK2(8)
         ZAP   D0003(4),PWK1(8)
         DROP  8
* ADD-EXIT.
P0002    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0002
         BR    15
F0002    DS    0H                  fall-through when not performed
* SHOW-PARA.
P0003    DS    0H
* MOVE CUST-CODE -> OUT-CODE
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0010(3),D0002      alphanumeric move
* DISPLAY
         MVC   DSPBUF+0(3),D0010
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
* end of a PERFORM range: return through its cell
         L     15,X0003
         BR    15
F0003    DS    0H                  fall-through when not performed
X0002    DC    A(F0002)            ADD-EXIT
X0003    DC    A(F0003)            SHOW-PARA
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'9'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'7'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'7'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'3'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
K0001    DC    PL8'1'              numeric constants
K0002    DC    PL8'1050'
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
SAVEAREA DS    18F
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DS    0CL16               CUSTOMER-REC (01 group)
D0001    DC    CL9'ACME CORP'      CUST-NAME PIC X(9)
D0002    DC    CL3'AAA'            CUST-CODE PIC X(3)
D0003    DC    PL4'10000'          CUST-BAL PIC S9(7)v2 COMP-3
D0004    DS    0CL16               SAVE-REC (01 group)
D0005    DC    CL9' '              SAVE-NAME PIC X(9)
D0006    DC    CL3' '              SAVE-CODE PIC X(3)
D0007    DC    PL4'000'            SAVE-BAL PIC S9(7)v2 COMP-3
D0008    DC    HL2'0'              COUNTER PIC S9(4)v0 COMP
         DS    XL6                 reserve the rest of a table
D0009    DC    CL9' '              OUT-NAME PIC X(9)
         DS    XL7                 reserve the rest of a table
D0010    DC    CL3' '              OUT-CODE PIC X(3)
         DS    XL5                 reserve the rest of a table
D0011    DC    CL7'0000000'        OUT-NUM PIC 9(7)v2 DISP
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
