*---------------------------------------------------------------
* Generated by cobc370 from tests/hello.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY is served by our own COBRT runtime, below.
*---------------------------------------------------------------
HELLO    CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                establish addressability
         USING *,12
         ST    13,SAVEAREA+4       backward chain to caller
         LA    11,SAVEAREA
         ST    11,8(13)            forward chain from caller
         LR    13,11               our save area is now current
* DISPLAY 'HELLO FROM COBC. NO SYS1.COBLIB HERE.'
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* DISPLAY 'SECOND LINE, WITH A QUOTE: DON'T PANIC.'
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(LIT0001)
         DC    X'80',AL3(LEN0001)  last parameter
LIT0001  DC    C'HELLO FROM COBC. NO SYS1.COBLIB HERE.'
LEN0001  DC    H'37'
PARM0002 DC    A(LIT0002)
         DC    X'80',AL3(LEN0002)  last parameter
LIT0002  DC    C'SECOND LINE, WITH A QUOTE: DON''T PANIC.'
LEN0002  DC    H'39'
SAVEAREA DS    18F
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
