*---------------------------------------------------------------
* Generated by cobc370 from iftest.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
IFTEST   CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
         SR    0,0
         SPM   0                   no overflow interrupts: high-order t
         CLI   SPIEDONE,X'01'      already armed?
         BE    SPIEARMD            the macro is several instructions: a
         SPIE  COBSPIE,((1,7),9,(11,12),15)  report program checks by l
         MVI   SPIEDONE,X'01'
SPIEARMD DS    0H
* MAIN-PARA.
P0000    DS    0H
T0000    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         L     2,D0000
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   WK1(16),DWK(8)
         CP    WK0(16),WK1(16)     numeric compare
         BNL   L0001
T0001    DS    0H
* MOVE LESS   -> OUT-MSG
         MVC   D0006(6),S0001      literal move, space padded
T0002    DS    0H
         B     L0002
         DROP  8
L0001    DS    0H
T0003    DS    0H
* MOVE NOTLES -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0002      literal move, space padded
         DROP  8
L0002    DS    0H
T0004    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006+0
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
T0005    DS    0H
* IF
         L     2,D0000
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   WK1(16),DWK(8)
         CP    WK0(16),WK1(16)     numeric compare
         BH    L0003
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0001(16)   literal
         CP    WK0(16),WK1(16)     numeric compare
         BNH   L0003
T0006    DS    0H
* MOVE ANDOK  -> OUT-MSG
         MVC   D0006(6),S0003      literal move, space padded
T0007    DS    0H
         B     L0004
         DROP  8
L0003    DS    0H
T0008    DS    0H
* MOVE ANDBAD -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0004      literal move, space padded
         DROP  8
L0004    DS    0H
T0009    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006+0
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
T0010    DS    0H
* IF
         L     2,D0000
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0002(16)   literal
         CP    WK0(16),WK1(16)     numeric compare
         BE    L0019
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0003(16)   literal
         CP    WK0(16),WK1(16)     numeric compare
         BNE   L0005
L0019    DS    0H
T0011    DS    0H
* MOVE OROK   -> OUT-MSG
         MVC   D0006(6),S0005      literal move, space padded
T0012    DS    0H
         B     L0006
         DROP  8
L0005    DS    0H
T0013    DS    0H
* MOVE ORBAD  -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0006      literal move, space padded
         DROP  8
L0006    DS    0H
T0014    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006+0
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
T0015    DS    0H
* IF
         CLC   D0003(3),S0007      alphanumeric compare
         BNE   L0007
T0016    DS    0H
* MOVE STREQ  -> OUT-MSG
         MVC   D0006(6),S0008      literal move, space padded
T0017    DS    0H
         B     L0008
         DROP  8
L0007    DS    0H
T0018    DS    0H
* MOVE STRNE  -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0009      literal move, space padded
         DROP  8
L0008    DS    0H
T0019    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006+0
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
T0020    DS    0H
* IF
         CLC   D0004(1),S0010      alphanumeric compare
         BNE   L0009
T0021    DS    0H
* MOVE EOFYES -> OUT-MSG
         MVC   D0006(6),S0011      literal move, space padded
T0022    DS    0H
         B     L0010
         DROP  8
L0009    DS    0H
T0023    DS    0H
* MOVE EOFNO  -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0012      literal move, space padded
         DROP  8
L0010    DS    0H
T0024    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006+0
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
T0025    DS    0H
* MOVE Y -> EOF-FLAG
         MVC   D0004(1),S0010      literal move, space padded
T0026    DS    0H
* IF
         CLC   D0004(1),S0010      alphanumeric compare
         BNE   L0011
T0027    DS    0H
* MOVE EOFYES -> OUT-MSG
         MVC   D0006(6),S0011      literal move, space padded
T0028    DS    0H
         B     L0012
         DROP  8
L0011    DS    0H
T0029    DS    0H
* MOVE EOFNO  -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0012      literal move, space padded
         DROP  8
L0012    DS    0H
T0030    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006+0
         LA    1,PARM0006
         L     15,VDISP
         BALR  14,15
T0031    DS    0H
* IF
         CP    D0002(4),K0004+15(1)  packed compare, in place
         BE    L0013
T0032    DS    0H
* MOVE NONZER -> OUT-MSG
         MVC   D0006(6),S0013      literal move, space padded
T0033    DS    0H
         B     L0014
         DROP  8
L0013    DS    0H
T0034    DS    0H
* MOVE ISZERO -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0014      literal move, space padded
         DROP  8
L0014    DS    0H
T0035    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006+0
         LA    1,PARM0007
         L     15,VDISP
         BALR  14,15
T0036    DS    0H
* IF
         L     2,D0000
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   WK1(16),DWK(8)
         CP    WK0(16),WK1(16)     numeric compare
         BNH   L0015
T0037    DS    0H
* IF
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0001(16)   literal
         CP    WK0(16),WK1(16)     numeric compare
         BNH   L0016
T0038    DS    0H
* MOVE NEST1  -> OUT-MSG
         MVC   D0006(6),S0015      literal move, space padded
T0039    DS    0H
         B     L0017
         DROP  8
L0016    DS    0H
T0040    DS    0H
* MOVE NEST2  -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0016      literal move, space padded
         DROP  8
L0017    DS    0H
T0041    DS    0H
         B     L0018
L0015    DS    0H
T0042    DS    0H
* MOVE NEST3  -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0017      literal move, space padded
         DROP  8
L0018    DS    0H
T0043    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006+0
         LA    1,PARM0008
         L     15,VDISP
         BALR  14,15
T0044    DS    0H
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'6'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'6'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'6'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'6'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'6'
PARM0006 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0006)  last parameter
LEN0006  DC    H'6'
PARM0007 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0007)  last parameter
LEN0007  DC    H'6'
PARM0008 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0008)  last parameter
LEN0008  DC    H'6'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL16
PWK2     DS    PL16
EDSRC    DS    PL16                ED source, sized to the selectors
EDWK     DS    CL64                ED pattern and result
ZWK      DS    CL24                zoned work area
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
K0001    DC    PL16'0'             numeric constants
K0002    DC    PL16'99'
K0003    DC    PL16'20'
K0004    DC    PL16'000'
S0001    DC    CL6'LESS  '         nonnumeric constants
S0002    DC    CL6'NOTLES'
S0003    DC    CL6'ANDOK '
S0004    DC    CL6'ANDBAD'
S0005    DC    CL6'OROK  '
S0006    DC    CL6'ORBAD '
S0007    DC    CL3'ABC'
S0008    DC    CL6'STREQ '
S0009    DC    CL6'STRNE '
S0010    DC    CL1'Y'
S0011    DC    CL6'EOFYES'
S0012    DC    CL6'EOFNO '
S0013    DC    CL6'NONZER'
S0014    DC    CL6'ISZERO'
S0015    DC    CL6'NEST1 '
S0016    DC    CL6'NEST2 '
S0017    DC    CL6'NEST3 '
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
SAVEAREA DS    18F
* program-check exit: report the source line, then let it abend
COBSPIE  DS    0H
         USING COBSPIE,15
         STM   14,12,SPIEREGS      R15 is our base on entry
         LR    9,15                keep a base across the WTO
         DROP  15
         USING COBSPIE,9
         LR    10,1                the PIE
*  the interruption code, as the digit people know it
         SR    7,7
         IC    7,7(,10)            low byte of the interruption code
         N     7,SPIE15
         LA    7,SPIEHEX(7)
         MVC   SPIECODE(1),0(7)
*  the interrupt address, as an offset into this module
         L     2,8(,10)            second word of the old PSW
         N     2,SPIEADR           leaves the instruction address
         S     2,SPIEBEG           relative to the entry point
*  the last table entry at or before it names the statement
         L     3,SPIETAB
         LH    4,SPIENUM
         SR    5,5                 no line yet
SPIELOOP LTR   4,4
         BZ    SPIEFND
         LH    6,0(,3)             this statement's offset
         CR    6,2
         BH    SPIEFND             past it: the previous one is the ans
         LH    5,2(,3)
         LA    3,4(,3)
         BCTR  4,0
         B     SPIELOOP
SPIEFND  CVD   5,SPIEDW
         UNPK  SPIELINE(5),SPIEDW+5(3)
         OI    SPIELINE+4,X'F0'
         ST    2,SPIEDW            the offset, relative to COBBEG
         UNPK  SPIEOFF(7),SPIEDW+1(4)  low three bytes to zoned
         TR    SPIEOFF(6),SPIEHEXT  zoned to hex digits
         WTO   MF=(E,SPIEWTO)      into the job log, beside the abend
*  cancel the exit and back up to the failing instruction,
*  so the abend happens for real -- same code, same dump
         SR    2,2
         IC    2,7(,10)            the interruption code
         A     2,SPIE3000
         ABEND (2),DUMP
SPIEHEX  DC    C'0123456789ABCDEF'
SPIEHEXT DC    240X'00',C'0123456789ABCDEF'
SPIE15   DC    F'15'
SPIE3000 DC    F'3000'
SPIEADR  DC    X'00FFFFFF'
SPIEBEG  DC    A(COBBEG)
SPIETAB  DC    A(SPIELTB)
SPIENUM  DC    H'45'               statements in the table
SPIEREGS DS    15F
SPIEDONE DC    X'00'               1 once this module's SPIE is armed
SPIEDW   DS    D
SPIEWTO  WTO   'COBC370: PROGRAM CHECK 0C0 LINE 00000 OFFSET 000000',  X
               MF=L
SPIECODE EQU   SPIEWTO+29,1        the 0C? digit, patched above
SPIELINE EQU   SPIEWTO+36,5        the line number, likewise
SPIEOFF  EQU   SPIEWTO+49,7        the offset from COBBEG, in hex
* statement offsets, ascending, paired with source lines
SPIELTB  DS    0H
         DC    AL2(T0000-COBBEG),AL2(15)
         DC    AL2(T0001-COBBEG),AL2(15)
         DC    AL2(T0002-COBBEG),AL2(17)
         DC    AL2(T0003-COBBEG),AL2(17)
         DC    AL2(T0004-COBBEG),AL2(18)
         DC    AL2(T0005-COBBEG),AL2(20)
         DC    AL2(T0006-COBBEG),AL2(20)
         DC    AL2(T0007-COBBEG),AL2(22)
         DC    AL2(T0008-COBBEG),AL2(22)
         DC    AL2(T0009-COBBEG),AL2(23)
         DC    AL2(T0010-COBBEG),AL2(25)
         DC    AL2(T0011-COBBEG),AL2(25)
         DC    AL2(T0012-COBBEG),AL2(27)
         DC    AL2(T0013-COBBEG),AL2(27)
         DC    AL2(T0014-COBBEG),AL2(28)
         DC    AL2(T0015-COBBEG),AL2(30)
         DC    AL2(T0016-COBBEG),AL2(30)
         DC    AL2(T0017-COBBEG),AL2(32)
         DC    AL2(T0018-COBBEG),AL2(32)
         DC    AL2(T0019-COBBEG),AL2(33)
         DC    AL2(T0020-COBBEG),AL2(35)
         DC    AL2(T0021-COBBEG),AL2(35)
         DC    AL2(T0022-COBBEG),AL2(37)
         DC    AL2(T0023-COBBEG),AL2(37)
         DC    AL2(T0024-COBBEG),AL2(38)
         DC    AL2(T0025-COBBEG),AL2(39)
         DC    AL2(T0026-COBBEG),AL2(41)
         DC    AL2(T0027-COBBEG),AL2(41)
         DC    AL2(T0028-COBBEG),AL2(43)
         DC    AL2(T0029-COBBEG),AL2(43)
         DC    AL2(T0030-COBBEG),AL2(44)
         DC    AL2(T0031-COBBEG),AL2(46)
         DC    AL2(T0032-COBBEG),AL2(46)
         DC    AL2(T0033-COBBEG),AL2(48)
         DC    AL2(T0034-COBBEG),AL2(48)
         DC    AL2(T0035-COBBEG),AL2(49)
         DC    AL2(T0036-COBBEG),AL2(51)
         DC    AL2(T0037-COBBEG),AL2(52)
         DC    AL2(T0038-COBBEG),AL2(52)
         DC    AL2(T0039-COBBEG),AL2(54)
         DC    AL2(T0040-COBBEG),AL2(54)
         DC    AL2(T0041-COBBEG),AL2(56)
         DC    AL2(T0042-COBBEG),AL2(56)
         DC    AL2(T0043-COBBEG),AL2(57)
         DC    AL2(T0044-COBBEG),AL2(58)
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DC    FL4'10'             A PIC S9(5)v0 COMP
         DS    XL4                 reserve the rest of a table
D0001    DC    FL4'20'             B PIC S9(5)v0 COMP
         DS    XL4                 reserve the rest of a table
D0002    DC    PL4'000'            BAL PIC S9(7)v2 COMP-3
         DS    XL4                 reserve the rest of a table
D0003    DC    CL3'ABC'            CODE-X PIC X(3)
         DS    XL5                 reserve the rest of a table
D0004    DC    CL1'N'              EOF-FLAG PIC X(1)
         DS    XL7                 reserve the rest of a table
D0006    DC    CL6' '              OUT-MSG PIC X(6)
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL,COBDATE,COBACC,COBUPSI
         ENTRY COBADV,COBSTR,COBUNS,COBWTO,COBWTOR,COBADT,COBMVL
         ENTRY COBDCAL,COBCANC
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBADV -- write one line with ASA carriage control.
*
*   R1 -> A(dcb), A(print buffer), A(halfword record length),
*         A(halfword owed), A(halfword request)
*
* ASA says what to do BEFORE a line prints, which is exactly
* what AFTER ADVANCING means. BEFORE has to be held over: the
* line goes out with whatever was owed from the last BEFORE,
* and its own count becomes what the next line owes. Once the
* two can add up the total is not known until run time, which
* is why this is a routine and not a few instructions inline.
*
* The request is the line count, or -1 for PAGE, negated when
* the phrase was BEFORE.
COBADV   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE7+4
         LA    11,RTSAVE7
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(buffer)
         L     4,8(0,1)            A(length)
         L     5,12(0,1)           A(owed)
         L     6,16(0,1)           A(request)
         L     10,20(0,1)          A(LINAGE cells), or 0
         L     11,24(0,1)          A(LINAGE-COUNTER), or 0
         LH    7,0(0,4)            the record length
         LTR   7,7
         LH    8,0(0,6)            the request
         LH    9,0(0,5)            what the last BEFORE left owing
         LTR   8,8                 BEFORE is the negative side
         BM    ADV100
         CH    8,ADVPAGE           AFTER PAGE, or a channel?
         BNL   ADV020
         CH    9,ADVPAGE           was a skip already owed?
         BNL   ADV030              then it stays one, whatever this ask
         AR    9,8                 owed plus this one
         B     ADV030
ADV020   LR    9,8                 a skip swallows what was owed
ADV030   XC    0(2,5),0(5)         nothing owed after an AFTER
         B     ADV150
ADV100   LCR   8,8                 back to a positive request
ADV110   STH   8,0(0,5)            this is what the next line owes
         LTR   9,9                 nothing owed?
         BNZ   ADV150
         LH    9,ADVONE            then this line simply takes the next
ADV150   SR    8,8                 no END-OF-PAGE yet
         LTR   10,10               a LINAGE file?
         BZ    ADV200
         CH    9,ADVPAGE           a skip?
         BNL   ADV160
         LH    14,0(0,11)          LINAGE-COUNTER
         AR    14,9
         CH    14,0(0,10)          past the body?
         BH    ADV160
         STH   14,0(0,11)
         LH    0,2(0,10)           FOOTING
         LTR   0,0
         BZ    ADV200              no FOOTING: no END-OF-PAGE short of
         CR    14,0
         BL    ADV200
         LA    8,1                 END-OF-PAGE
         B     ADV200
ADV160   LH    14,ADVONE
         STH   14,0(0,11)          counter back to 1
         LA    8,1                 a new page is END-OF-PAGE without FO
         LH    0,2(0,10)
         LTR   0,0
         BZ    ADV170
         SR    8,8                 with FOOTING, only the footing is
ADV170   LH    9,4(0,10)           LINES AT TOP
         LTR   9,9
         BNZ   ADV175
         LH    9,ADVPAGE           no top margin: the line itself carri
         B     ADV200
ADV175   PUT   (2),ADVB1           eject on a blank line; R9 survives i
ADV200   CH    9,ADVPAGE           a page skip?
         BL    ADV210
         BH    ADV205              a channel
         MVI   0(3),C'1'           skip to a new page
         B     ADV300
ADV205   LA    10,ADVCHAN
         AR    10,9
         SH    10,ADVCHOF          request 1001 is the first code
         MVC   0(1,3),0(10)        the channel's ASA code
         B     ADV300
ADV210   LTR   9,9
         BNM   ADV220
         SR    9,9                 never negative here
ADV220   CH    9,ADVTHREE          more than one code can carry?
         BNH   ADV240
         PUT   (2),ADVB3           three blank lines at a time
         SH    9,ADVTHREE
         B     ADV220
ADV240   LA    10,ADVCODE
         AR    10,9
         MVC   0(1,3),0(10)        '+', ' ', '0' or '-'
ADV300   PUT   (2),(3)             the line itself
         L     13,4(13)
         ST    8,16(13)            END-OF-PAGE, into R15's slot for the
         LM    14,12,12(13)
         BR    14
ADVB3    DC    C'-'                a blank line that advances three
         DC    CL132' '
ADVB1    DC    C'1'                a blank line that ejects
         DC    CL132' '
ADVCHAN  DC    C'123456789ABC+'    channels 1-12, CSP
ADVCHOF  DC    H'1001'
ADVCODE  DC    C'+ 0-'             0, 1, 2 or 3 lines
ADVONE   DC    H'1'
ADVPAGE  DC    H'999'              the page-skip request
ADVTHREE DC    H'3'
RTSAVE7  DS    18F
*
* COBUPSI -- set the eight switches from the EXEC PARM.
*
* PARM='/UPSI(10100000)' is the form IBM's later compilers
* take, and the one the runtime looks for: the literal UPSI
* anywhere in the parameter text, then the next eight 0 or 1
* characters, leftmost being UPSI-0. Anything else leaves all
* eight off, which is the documented default.
COBUPSI  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE6+4
         LA    11,RTSAVE6
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(parameter text)
         LA    2,0(0,2)            drop the end-of-list bit
         XC    RTUPSI,RTUPSI       all off unless the PARM says otherwi
         LH    3,0(0,2)            its length
         LA    4,2(0,2)            the text itself
         CH    3,UPSIMIN           room for UPSI and eight digits?
         BL    UPSX
         SH    3,UPSIMIN
         LA    3,1(3)              positions worth trying
UPS10    CLC   0(4,4),UPSITAG
         BE    UPS15
         LA    4,1(4)
         BCT   3,UPS10
         B     UPSX                no UPSI in the parameter
UPS15    LA    4,4(4)              past the tag
         CLI   0(4),C'0'
         BE    UPS20
         CLI   0(4),C'1'
         BE    UPS20
         LA    4,1(4)              skip a ( or an =
UPS20    SR    5,5                 the byte being built
         LA    6,8                 eight of them
UPS30    SLL   5,1
         CLI   0(4),C'1'
         BNE   UPS40
         LA    5,1(5)
UPS40    LA    4,1(4)
         BCT   6,UPS30
         ST    5,RTUPSI            the byte, for the caller to store
UPSX     L     13,4(13)
         L     15,RTUPSI           the byte, while R12 is still ours
         ST    15,16(13)           into the save area's R15 slot
         LM    14,12,12(13)
         BR    14
*
* COBACC -- one transfer from SYSIN into the caller's item.
*
* General rule 2 on II-53 leaves the size of a transfer to the
* implementor: here it is one 80-column record. The buffer is
* blanked first, so a receiver wider than a card is padded and
* a read past the last card returns spaces rather than the
* card before it.
*
* Parameter list: A(item), A(halfword length).
COBACC   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE5+4
         LA    11,RTSAVE5
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(item)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length still to fill
COBA005  LTR   4,4
         BNP   COBA040             filled
         MVI   ACCBUF,C' '
         MVC   ACCBUF+1(255),ACCBUF  blank the buffer
         CLI   ACCEOFF,X'01'       already at end of file?
         BE    COBA020
         CLI   ACCOPEN,X'01'       already open?
         BE    COBA010
         OPEN  (ACCDCB,INPUT)
         MVI   ACCOPEN,X'01'
COBA010  LA    1,COBA030
         STCM  1,7,ACCDCB+33       into DCBEODAD
         GET   ACCDCB,ACCBUF       one card
         B     COBA020
COBA030  MVI   ACCEOFF,X'01'       end of file: the buffer stays blank
COBA020  LR    5,4
         CH    5,ACCCARD
         BNH   COBA035
         LH    5,ACCCARD           one card's worth
COBA035  BCTR  5,0                 EX wants length-1
         EX    5,COBAMVC
         LA    2,1(5,2)            past what was stored
         LA    5,1(5)
         SR    4,5
         B     COBA005
COBA040  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBAMVC  MVC   0(0,2),ACCBUF       patched by EX
ACCCARD  DC    H'80'               a card
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   ACCOPEN,X'01'
         BNE   COBT005
         CLOSE (ACCDCB)
         MVI   ACCOPEN,X'00'
COBT005  CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBDATE -- fill an 8-byte field with MM/DD/YY.
*   R1 -> the field.  TIME DEC hands back the date as packed
*   00YYDDDF, which is Julian, so the day of year has to be
*   walked into a month and a day.
*
COBDATE  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE4+4
         LA    11,RTSAVE4
         ST    11,8(13)
         LR    13,11
         LR    2,1                 the field, before TIME takes R1
         TIME  DEC                 R0 = HHMMSSth, R1 = 00YYDDDF
         ST    1,DTPACK
         UNPK  DTZONE(7),DTPACK(4)  '00YYDDD'
         OI    DTZONE+6,X'F0'
         PACK  DTDW(8),DTZONE+4(3)
         CVB   3,DTDW              day of the year
         PACK  DTDW(8),DTZONE+2(2)
         CVB   4,DTDW              the year
         N     4,DTF3              zero if a leap year -- 1901-2099, so
*                             mod 4 is the whole rule
         LA    5,1                 month
         LA    6,DTMON
DT010    SR    7,7
         IC    7,0(0,6)            days in this month
         CH    5,DTH2              February?
         BNE   DT020
         LTR   4,4
         BNZ   DT020
         LA    7,1(0,7)            29 this year
DT020    CR    3,7
         BNH   DT030               the day falls in this month
         SR    3,7
         LA    5,1(0,5)
         LA    6,1(0,6)
         B     DT010
DT030    CVD   5,DTDW
         UNPK  0(2,2),DTDW+6(2)    MM
         OI    1(2),X'F0'
         MVI   2(2),C'/'
         CVD   3,DTDW
         UNPK  3(2,2),DTDW+6(2)    DD
         OI    4(2),X'F0'
         MVI   5(2),C'/'
         MVC   6(2,2),DTZONE+2     YY, already zoned
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
DTMON    DC    AL1(31,28,31,30,31,30,31,31,30,31,30,31)
DTF3     DC    F'3'
DTH2     DC    H'2'
DTPACK   DS    F
DTZONE   DS    CL8
DTDW     DS    D
RTSAVE4  DS    18F
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTSAVE5  DS    18F
RTSAVE6  DS    18F
RTUPSI   DS    F
UPSITAG  DC    C'UPSI'
UPSIMIN  DC    H'12'               UPSI, a bracket, eight digits
ACCOPEN  DC    X'00'
ACCEOFF  DC    X'00'
ACCBUF   DC    CL256' '            one card from SYSIN, blank padded
ACCMAX   DC    H'256'
ACCDCB   DCB   DDNAME=SYSIN,DSORG=PS,MACRF=(GM),                       X
               EODAD=0
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
*
* COBSTR -- STRING. R1 -> AL4(receiver), AL2(len), AL2(n),
*   AL4(pointer cell or 0); then per item AL4(addr), AL2(len),
*   AL2(delimiter len, 0 for SIZE), AL4(delimiter addr).
* Each item goes byte by byte until its delimiter matches or
* it runs out; the receiver filling up is the overflow, and
* a pointer outside 1..len is overflow with nothing moved.
* R15 = 0 done, 1 overflow. Other bytes of the receiver are
* not touched, which is the rule: STRING does not space-fill.
COBSTR   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE8+4
         LA    11,RTSAVE8
         ST    11,8(13)
         LR    13,11
         LR    2,1                 the block
         L     3,0(2)              receiver
         LH    5,4(2)              its length
         LH    7,6(2)              items
         L     4,8(2)              pointer cell
         LTR   4,4
         BZ    STR010              none: start at 1
         L     4,0(4)
         B     STR020
STR010   LA    4,1
STR020   BCTR  4,0                 position, from 0
         LTR   4,4
         BM    STRBAD              pointer below 1
         CR    4,5
         BNL   STRBAD              pointer past the end
         LA    6,12(2)             the first item
STR100   LTR   7,7
         BZ    STRDONE             all items sent
         L     8,0(6)              item
         LH    9,4(6)              its length
         LH    11,6(6)             delimiter length
         L     10,8(6)             delimiter
STR110   LTR   9,9
         BZ    STR190              item exhausted
         LTR   11,11
         BZ    STR120              SIZE: no delimiter to look for
         CR    9,11
         BL    STR120              too few left to hold the delimiter
         LR    15,11
         BCTR  15,0
         EX    15,STRCLC           delimiter here?
         BE    STR190              yes: the item ends
STR120   CR    4,5
         BNL   STROVF              receiver full
         LA    15,0(3,4)
         MVC   0(1,15),0(8)        one byte
         LA    8,1(8)
         BCTR  9,0
         LA    4,1(4)
         B     STR110
STR190   LA    6,12(6)             next item
         BCTR  7,0
         B     STR100
STRDONE  SR    15,15
         B     STRRET
STROVF   LA    15,1                overflow
STRRET   L     14,8(2)             pointer cell
         LTR   14,14
         BZ    STRX
         LA    4,1(4)              back to counting from 1
         ST    4,0(14)
         B     STRX
STRBAD   LA    15,1                pointer out of range: overflow, noth
STRX     L     13,4(13)
         ST    15,16(13)           R15 survives the LM through its own
         LM    14,12,12(13)
         BR    14
STRCLC   CLC   0(0,8),0(10)        executed with the delimiter length
RTSAVE8  DS    18F
*
* COBUNS -- UNSTRING. R1 -> AL4(sender), AL2(len), AL2(nd),
*   AL4(pointer cell or 0), AL4(tally cell or 0), AL2(nr),
*   AL2(0), AL4(0); then nd delimiters AL4(addr), AL2(len),
*   AL2(ALL); then nr receivers AL4(addr), AL2(len),
*   AL2(DELIMITER IN len), AL4(DELIMITER IN or 0),
*   AL4(COUNT IN cell or 0).
* For each receiver the sender is scanned from the position
* for the first place any delimiter matches, delimiters tried
* in order; the bytes before it go to the receiver, left
* justified and space filled. No delimiters means a receiver
* takes its own length. Bytes left when the receivers are
* used up are the overflow. R15 = 0 done, 1 overflow.
COBUNS   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE9+4
         LA    11,RTSAVE9
         ST    11,8(13)
         LR    13,11
         LR    2,1                 the block
         L     3,0(2)              sender
         LH    5,4(2)              its length
         LH    10,6(2)             delimiters
         L     4,8(2)              pointer cell
         LTR   4,4
         BZ    UNS010
         L     4,0(4)
         B     UNS020
UNS010   LA    4,1
UNS020   BCTR  4,0                 position, from 0
         LTR   4,4
         BM    UNSBAD
         CR    4,5
         BNL   UNSBAD              pointer past the end
         LH    7,16(2)             receivers
         LR    6,10
         SLL   6,3                 eight bytes per delimiter
         LA    6,24(6,2)           the first receiver
UNS100   LTR   7,7
         BZ    UNSEND              receivers used up
         CR    4,5
         BNL   UNSEND              sender used up: the rest stay as the
         LR    8,4                 scan from the position
         SR    9,9                 no delimiter matched yet
         LTR   10,10
         BZ    UNS140              no delimiters: take the receiver's l
UNS110   CR    8,5
         BNL   UNS170              end of the sender, no delimiter
         LA    9,24(2)             the first delimiter
         LR    0,10
UNS120   L     14,0(9)             delimiter
         LH    15,4(9)             its length
         LR    1,5
         SR    1,8                 bytes left
         CR    1,15
         BL    UNS130              not enough left for this one
         LA    1,0(3,8)
         BCTR  15,0
         EX    15,UNSCLC           matches here?
         BE    UNS170              yes, R9 says which
UNS130   LA    9,8(9)              next delimiter
         BCT   0,UNS120
         SR    9,9                 none matched at this byte
         LA    8,1(8)
         B     UNS110
UNS140   LH    1,4(6)              receiver length
         LA    8,0(4,1)            position plus that
         CR    8,5
         BNH   UNS170
         LR    8,5                 but no further than the end
UNS170   L     14,0(6)             receiver
         LH    15,4(6)             its length
         MVI   0(14),C' '
         LR    11,15
         BCTR  11,0
         LTR   11,11
         BZ    UNS172              a one-byte receiver is filled
         BCTR  11,0
         EX    11,UNSPAD           space fill
UNS172   LR    1,8
         SR    1,4                 bytes to move
         L     11,12(6)            COUNT IN cell
         LTR   11,11
         BZ    UNS174
         ST    1,0(11)             the count, before truncation
UNS174   CR    1,15
         BNH   UNS176
         LR    1,15                truncated on the right
UNS176   LTR   1,1
         BZ    UNS180              nothing to move
         BCTR  1,0
         LA    15,0(3,4)
         EX    1,UNSMVC            the bytes
UNS180   L     14,8(6)             DELIMITER IN
         LTR   14,14
         BZ    UNS186
         LH    15,6(6)             its length
         MVI   0(14),C' '
         LR    11,15
         BCTR  11,0
         LTR   11,11
         BZ    UNS182
         BCTR  11,0
         EX    11,UNSPAD           space fill
UNS182   LTR   9,9
         BZ    UNS186              no delimiter: spaces
         LH    1,4(9)              delimiter length
         CR    1,15
         BNH   UNS184
         LR    1,15
UNS184   BCTR  1,0
         L     15,0(9)
         EX    1,UNSMVC            the delimiter
UNS186   L     14,12(2)            TALLYING cell
         LTR   14,14
         BZ    UNS188
         L     15,0(14)
         LA    15,1(15)            one more receiver acted on
         ST    15,0(14)
UNS188   LTR   9,9
         BZ    UNS196              no delimiter: position is where the
         LH    1,4(9)              delimiter length
         LA    4,0(1,8)            past the delimiter
         LH    0,6(9)              ALL?
         LTR   0,0
         BZ    UNS198
UNS190   LR    0,5
         SR    0,4                 bytes left
         CR    0,1
         BL    UNS198              not enough for another copy
         LA    15,0(3,4)
         L     14,0(9)
         LR    11,1
         BCTR  11,0
         EX    11,UNSCLC2          another copy of the delimiter?
         BNE   UNS198
         LA    4,0(1,4)            skip it too
         B     UNS190
UNS196   LR    4,8
UNS198   LA    6,16(6)             next receiver
         BCTR  7,0
         B     UNS100
UNSEND   SR    15,15
         CR    4,5
         BNL   UNS200
         LA    15,1                bytes left over: overflow
UNS200   L     14,8(2)             pointer cell
         LTR   14,14
         BZ    UNSX
         LA    4,1(4)
         ST    4,0(14)
         B     UNSX
UNSBAD   LA    15,1                pointer out of range: overflow, noth
UNSX     L     13,4(13)
         ST    15,16(13)           R15 survives the LM through its own
         LM    14,12,12(13)
         BR    14
UNSCLC   CLC   0(0,1),0(14)        executed with the delimiter length
UNSCLC2  CLC   0(0,15),0(14)
UNSMVC   MVC   0(0,14),0(15)       executed with the byte count
UNSPAD   MVC   1(0,14),0(14)       executed: propagate the space
RTSAVE9  DS    18F
*
* COBWTO -- DISPLAY UPON CONSOLE. R1 -> A(text), A(halfword length).
* The text goes into a WTO list whose length halfword is set
* from the parameter; MVS caps a line at what it will show.
COBWTO   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE10+4
         LA    11,RTSAVE10
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)
         CH    4,WTOMAX
         BNH   WTO010
         LH    4,WTOMAX
WTO010   MVI   WTOTXT,C' '
         MVC   WTOTXT+1(119),WTOTXT
         LTR   4,4
         BNP   WTO020
         BCTR  4,0
         EX    4,WTOMVC
         LA    4,1(4)
WTO020   LA    4,4(4)              plus the header
         STH   4,WTOLST
         WTO   MF=(E,WTOLST)
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
WTOMVC   MVC   WTOTXT(0),0(2)      executed
WTOMAX   DC    H'120'
WTOLST   DC    AL2(124),AL2(0)     length, MCS flags
WTOTXT   DC    CL120' '
RTSAVE10 DS    18F
*
* COBWTOR -- ACCEPT FROM CONSOLE. R1 -> A(item), A(halfword length).
* A WTOR asks the operator, the task waits on its ECB, and the
* reply is moved to the item space padded. One line only.
COBWTOR  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE11+4
         LA    11,RTSAVE11
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(item)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)
         MVI   WTORRPL,C' '
         MVC   WTORRPL+1(119),WTORRPL
         XC    WTORECB,WTORECB
         WTOR  'COBC370: ACCEPT FROM CONSOLE',WTORRPL,120,WTORECB
         WAIT  ECB=WTORECB
         LTR   4,4
         BNP   WTOR20
         CH    4,WTORMAX
         BNH   WTOR10
         LH    4,WTORMAX
WTOR10   BCTR  4,0
         EX    4,WTORMVC
WTOR20   L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
WTORMVC  MVC   0(0,2),WTORRPL      executed
WTORMAX  DC    H'120'
WTORECB  DC    F'0'
WTORRPL  DC    CL120' '
RTSAVE11 DS    18F
*
* COBADT -- ACCEPT FROM DATE, DAY or TIME. R1 -> A(area), A(halfword
* kind: 1 DATE, 2 DAY, 3 TIME). Writes YYMMDD, YYDDD or HHMMSSth as
* zoned digits into the area. DATE borrows COBDATE's month walk.
COBADT   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE12+4
         LA    11,RTSAVE12
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            the area
         L     3,4(0,1)
         LH    3,0(0,3)            the kind
         CH    3,ADTH3
         BE    ADT300              TIME
         TIME  DEC                 R1 = 00YYDDDF
         ST    1,ADTPK
         UNPK  ADTZ(7),ADTPK(4)    '00YYDDD'
         OI    ADTZ+6,X'F0'
         CH    3,ADTH2
         BE    ADT200              DAY
         LA    1,ADTB              DATE: MM/DD/YY first
         L     15,ADTVD
         BALR  14,15
         MVC   0(2,2),ADTB+6       YY
         MVC   2(2,2),ADTB         MM
         MVC   4(2,2),ADTB+3       DD
         B     ADTX
ADT200   MVC   0(5,2),ADTZ+2       YYDDD
         B     ADTX
ADT300   TIME  DEC                 R0 = HHMMSSth
         ST    0,ADTPK
         MVI   ADTPK+4,X'0F'       a sign nibble to unpack against
         UNPK  ADTZ(9),ADTPK(5)    'HHMMSSth0'
         MVC   0(8,2),ADTZ
ADTX     L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
ADTVD    DC    A(COBDATE)
ADTH2    DC    H'2'
ADTH3    DC    H'3'
ADTPK    DS    2F
ADTZ     DS    CL9
ADTB     DS    CL8
RTSAVE12 DS    18F
*
* COBDCAL -- CALL identifier. R1 -> A(8-byte name), A(parameter list).
* A table of programs loaded so far: a name found there is called
* at the entry point remembered; one not found is LOADed and
* remembered, so each program is loaded once until CANCELled.
* The callee's return code comes back in R15.
COBDCAL  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE14+4
         LA    11,RTSAVE14
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            the name
         L     3,4(0,1)            the parameter list
         LA    4,DCTAB
         LA    5,16                entries
DCA010   CLI   0(4),X'00'          an empty entry?
         BE    DCA050              then it is not loaded
         CLC   0(8,4),0(2)         this one?
         BE    DCA030
         LA    4,12(4)
         BCT   5,DCA010
         LOAD  EPLOC=(2)           table full: load without remembering
         LR    15,0
         B     DCA040
DCA050   MVC   0(8,4),0(2)         remember the name
         LOAD  EPLOC=(2)
         ST    0,8(0,4)            and the entry point
DCA030   L     15,8(0,4)
DCA040   LR    1,3                 R1 -> the callee's parameters
         BALR  14,15
         L     13,4(13)
         ST    15,16(13)           the callee's return code survives th
         LM    14,12,12(13)
         BR    14
RTSAVE14 DS    18F
*
* COBCANC -- CANCEL. R1 -> A(8-byte name). A program in the table is
* DELETEd and forgotten; one that is not is left alone.
COBCANC  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE15+4
         LA    11,RTSAVE15
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            the name
         LA    4,DCTAB
         LA    5,16
CAN010   CLI   0(4),X'00'
         BE    CANX                not loaded: nothing to do
         CLC   0(8,4),0(2)
         BE    CAN020
         LA    4,12(4)
         BCT   5,CAN010
         B     CANX
CAN020   DELETE EPLOC=(2)          release it
         XC    0(12,4),0(4)        and forget it
CANX     L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
DCTAB    DC    16XL12'00'          loaded programs: CL8 name, A(entry)
RTSAVE15 DS    18F
*
* COBMVL -- an alphanumeric move of any length. R1 -> A(receiver),
*   A(sender), A(halfword receiver length, halfword sender length).
* The shorter of the two is moved in 256-byte pieces; a receiver
* longer than the sender is space filled after it. Serves a group
* whose length depends on an OCCURS DEPENDING ON count, and any
* move too long for one MVC.
COBMVL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE13+4
         LA    11,RTSAVE13
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            receiver
         L     3,4(0,1)            sender
         L     4,8(0,1)
         LH    5,0(0,4)            receiver length
         LH    6,2(0,4)            sender length
         LR    7,5
         CR    7,6
         BNH   MVL010
         LR    7,6                 bytes to move: the shorter
MVL010   SR    5,7                 bytes to fill afterwards
MVL020   LTR   7,7
         BNP   MVL040              moved
         LR    8,7
         CH    8,MVL256
         BNH   MVL030
         LH    8,MVL256            a piece
MVL030   BCTR  8,0
         EX    8,MVLMVC
         LA    8,1(8)
         AR    2,8
         AR    3,8
         SR    7,8
         B     MVL020
MVL040   LTR   5,5
         BNP   MVLX                nothing to fill
         MVI   0(2),C' '
         BCTR  5,0
MVL050   LTR   5,5
         BNP   MVLX
         LR    8,5
         CH    8,MVL256
         BNH   MVL060
         LH    8,MVL256
MVL060   BCTR  8,0
         EX    8,MVLPAD            propagate the space
         LA    8,1(8)
         AR    2,8
         SR    5,8
         B     MVL050
MVLX     L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
MVLMVC   MVC   0(0,2),0(3)         executed
MVLPAD   MVC   1(0,2),0(2)         executed
MVL256   DC    H'256'
RTSAVE13 DS    18F
         END
