*---------------------------------------------------------------
* Generated by cobc370 from tests/iftest.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
IFTEST   CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* MAIN-PARA.
P0000    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         L     2,D0000
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   WK1(16),DWK(8)
         CP    WK0(16),WK1(16)     numeric compare
         BNL   L0001
* MOVE LESS   -> OUT-MSG
         MVC   D0006(6),S0001      literal move, space padded
         B     L0002
         DROP  8
L0001    DS    0H
* MOVE NOTLES -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0002      literal move, space padded
         DROP  8
L0002    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* IF
         L     2,D0000
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   WK1(16),DWK(8)
         CP    WK0(16),WK1(16)     numeric compare
         BH    L0003
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0001(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BNH   L0003
* MOVE ANDOK  -> OUT-MSG
         MVC   D0006(6),S0003      literal move, space padded
         B     L0004
         DROP  8
L0003    DS    0H
* MOVE ANDBAD -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0004      literal move, space padded
         DROP  8
L0004    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
* IF
         L     2,D0000
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0002(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BE    L0019
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0003(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BNE   L0005
L0019    DS    0H
* MOVE OROK   -> OUT-MSG
         MVC   D0006(6),S0005      literal move, space padded
         B     L0006
         DROP  8
L0005    DS    0H
* MOVE ORBAD  -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0006      literal move, space padded
         DROP  8
L0006    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
* IF
         CLC   D0003(3),S0007      alphanumeric compare
         BNE   L0007
* MOVE STREQ  -> OUT-MSG
         MVC   D0006(6),S0008      literal move, space padded
         B     L0008
         DROP  8
L0007    DS    0H
* MOVE STRNE  -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0009      literal move, space padded
         DROP  8
L0008    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
* IF
         CLC   D0004(1),S0010      alphanumeric compare
         BNE   L0009
* MOVE EOFYES -> OUT-MSG
         MVC   D0006(6),S0011      literal move, space padded
         B     L0010
         DROP  8
L0009    DS    0H
* MOVE EOFNO  -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0012      literal move, space padded
         DROP  8
L0010    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
* MOVE Y -> EOF-FLAG
         MVC   D0004(1),S0010      literal move, space padded
* IF
         CLC   D0004(1),S0010      alphanumeric compare
         BNE   L0011
* MOVE EOFYES -> OUT-MSG
         MVC   D0006(6),S0011      literal move, space padded
         B     L0012
         DROP  8
L0011    DS    0H
* MOVE EOFNO  -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0012      literal move, space padded
         DROP  8
L0012    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006
         LA    1,PARM0006
         L     15,VDISP
         BALR  14,15
* IF
         ZAP   WK0(16),D0002(4)
         ZAP   WK1(16),K0001(8)    literal
         SRP   WK1(16),2,0         align scale (left)
         CP    WK0(16),WK1(16)     numeric compare
         BE    L0013
* MOVE NONZER -> OUT-MSG
         MVC   D0006(6),S0013      literal move, space padded
         B     L0014
         DROP  8
L0013    DS    0H
* MOVE ISZERO -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0014      literal move, space padded
         DROP  8
L0014    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006
         LA    1,PARM0007
         L     15,VDISP
         BALR  14,15
* IF
         L     2,D0000
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   WK1(16),DWK(8)
         CP    WK0(16),WK1(16)     numeric compare
         BNH   L0015
* IF
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0001(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BNH   L0016
* MOVE NEST1  -> OUT-MSG
         MVC   D0006(6),S0015      literal move, space padded
         B     L0017
         DROP  8
L0016    DS    0H
* MOVE NEST2  -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0016      literal move, space padded
         DROP  8
L0017    DS    0H
         B     L0018
L0015    DS    0H
* MOVE NEST3  -> OUT-MSG
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(6),S0017      literal move, space padded
         DROP  8
L0018    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(6),D0006
         LA    1,PARM0008
         L     15,VDISP
         BALR  14,15
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'6'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'6'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'6'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'6'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'6'
PARM0006 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0006)  last parameter
LEN0006  DC    H'6'
PARM0007 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0007)  last parameter
LEN0007  DC    H'6'
PARM0008 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0008)  last parameter
LEN0008  DC    H'6'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
K0001    DC    PL8'0'              numeric constants
K0002    DC    PL8'99'
K0003    DC    PL8'20'
S0001    DC    CL6'LESS  '         nonnumeric constants
S0002    DC    CL6'NOTLES'
S0003    DC    CL6'ANDOK '
S0004    DC    CL6'ANDBAD'
S0005    DC    CL6'OROK  '
S0006    DC    CL6'ORBAD '
S0007    DC    CL3'ABC'
S0008    DC    CL6'STREQ '
S0009    DC    CL6'STRNE '
S0010    DC    CL1'Y'
S0011    DC    CL6'EOFYES'
S0012    DC    CL6'EOFNO '
S0013    DC    CL6'NONZER'
S0014    DC    CL6'ISZERO'
S0015    DC    CL6'NEST1 '
S0016    DC    CL6'NEST2 '
S0017    DC    CL6'NEST3 '
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
SAVEAREA DS    18F
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DC    F'10'               A PIC S9(5)v0 COMP
D0001    DC    F'20'               B PIC S9(5)v0 COMP
D0002    DC    PL4'000'            BAL PIC S9(7)v2 COMP-3
D0003    DC    CL3'ABC'            CODE-X PIC X(3)
D0004    DC    CL1'N'              EOF-FLAG PIC X(1)
D0006    DC    CL6' '              OUT-MSG PIC X(6)
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
