*---------------------------------------------------------------
* Generated by cobc370 from tests/isamrnd.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
ISAMRND  CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* MAIN-PARA.
P0000    DS    0H
* OPEN INPUT GLACCT
         OPEN  (FD000,INPUT)
         LH    0,FD000+62          DCBBLKSI, filled in by OPEN
         AH    0,=H'16'            ISAM's working prefix
         GETMAIN R,LV=(0)
         ST    1,DB000+12          area address into the DECB
* MOVE 10303 -> WS-NOMKEY
         ZAP   PWK1(8),K0001(8)    literal
         L     8,BL0000            base locator
         USING WSC0000,8
         ZAP   D0008(6),PWK1(8)
         OI    D0008+5,X'0F'       unsigned: force an F sign
* READ GLACCT
         MVI   ISFLG,X'00'
         XC    DB000(4),DB000      clear the ECB before each READ
         XC    DB000+24(2),DB000+24  and the exception code
         LA    1,D0008             NOMINAL KEY
         ST    1,DB000+20          into the DECB
         LA    1,DB000             R1 -> DECB, as the READ macro does
         L     15,FD000+88         DCBLRAN: read-write K module
         BALR  14,15
         WAIT  ECB=DB000           not CHECK, and not WAITF
         CLC   DB000+24(2),=X'0000'  exception code set?
         BNE   L0001
         CLI   ISFLG,X'00'         or a permanent error?
         BNE   L0001
         L     1,DB000+16          record pointer word
         MVC   D0000(57),0(1)      block-relative record into the FD ar
         B     L0002
L0001    DS    0H                  INVALID KEY
         DROP  8
* GO TO MISS-ONE
         B     P0001
L0002    DS    0H
* MOVE GLAC-KEY -> OUT-KEY
         L     8,BL0000            base locator
         USING WSC0000,8
         ZAP   PWK1(8),D0002(6)
         UNPK  D0009(10),PWK1(8)   packed -> zoned
         OI    D0009+9,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(4),S0001
         MVC   DSPBUF+4(10),D0009
         MVC   DSPBUF+14(1),S0002
         MVC   DSPBUF+15(40),D0007
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* GO TO SECOND-PARA
         B     P0002
         DROP  8
* MISS-ONE.
P0001    DS    0H
* DISPLAY
         MVC   DSPBUF+0(10),S0003
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
* SECOND-PARA.
P0002    DS    0H
* MOVE 10301 -> WS-NOMKEY
         ZAP   PWK1(8),K0002(8)    literal
         L     8,BL0000            base locator
         USING WSC0000,8
         ZAP   D0008(6),PWK1(8)
         OI    D0008+5,X'0F'       unsigned: force an F sign
* READ GLACCT
         MVI   ISFLG,X'00'
         XC    DB000(4),DB000      clear the ECB before each READ
         XC    DB000+24(2),DB000+24  and the exception code
         LA    1,D0008             NOMINAL KEY
         ST    1,DB000+20          into the DECB
         LA    1,DB000             R1 -> DECB, as the READ macro does
         L     15,FD000+88         DCBLRAN: read-write K module
         BALR  14,15
         WAIT  ECB=DB000           not CHECK, and not WAITF
         CLC   DB000+24(2),=X'0000'  exception code set?
         BNE   L0003
         CLI   ISFLG,X'00'         or a permanent error?
         BNE   L0003
         L     1,DB000+16          record pointer word
         MVC   D0000(57),0(1)      block-relative record into the FD ar
         B     L0004
L0003    DS    0H                  INVALID KEY
         DROP  8
* GO TO MISS-TWO
         B     P0003
L0004    DS    0H
* MOVE GLAC-KEY -> OUT-KEY
         L     8,BL0000            base locator
         USING WSC0000,8
         ZAP   PWK1(8),D0002(6)
         UNPK  D0009(10),PWK1(8)   packed -> zoned
         OI    D0009+9,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(4),S0001
         MVC   DSPBUF+4(10),D0009
         MVC   DSPBUF+14(1),S0002
         MVC   DSPBUF+15(40),D0007
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
* GO TO THIRD-PARA
         B     P0004
         DROP  8
* MISS-TWO.
P0003    DS    0H
* DISPLAY
         MVC   DSPBUF+0(10),S0004
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
* THIRD-PARA.
P0004    DS    0H
* MOVE 9999999 -> WS-NOMKEY
         ZAP   PWK1(8),K0003(8)    literal
         L     8,BL0000            base locator
         USING WSC0000,8
         ZAP   D0008(6),PWK1(8)
         OI    D0008+5,X'0F'       unsigned: force an F sign
* READ GLACCT
         MVI   ISFLG,X'00'
         XC    DB000(4),DB000      clear the ECB before each READ
         XC    DB000+24(2),DB000+24  and the exception code
         LA    1,D0008             NOMINAL KEY
         ST    1,DB000+20          into the DECB
         LA    1,DB000             R1 -> DECB, as the READ macro does
         L     15,FD000+88         DCBLRAN: read-write K module
         BALR  14,15
         WAIT  ECB=DB000           not CHECK, and not WAITF
         CLC   DB000+24(2),=X'0000'  exception code set?
         BNE   L0005
         CLI   ISFLG,X'00'         or a permanent error?
         BNE   L0005
         L     1,DB000+16          record pointer word
         MVC   D0000(57),0(1)      block-relative record into the FD ar
         B     L0006
L0005    DS    0H                  INVALID KEY
         DROP  8
* GO TO MISS-THREE
         B     P0005
L0006    DS    0H
* MOVE GLAC-KEY -> OUT-KEY
         L     8,BL0000            base locator
         USING WSC0000,8
         ZAP   PWK1(8),D0002(6)
         UNPK  D0009(10),PWK1(8)   packed -> zoned
         OI    D0009+9,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(4),S0001
         MVC   DSPBUF+4(10),D0009
         MVC   DSPBUF+14(1),S0002
         MVC   DSPBUF+15(40),D0007
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
* GO TO DONE-PARA
         B     P0006
         DROP  8
* MISS-THREE.
P0005    DS    0H
* DISPLAY
         MVC   DSPBUF+0(12),S0005
         LA    1,PARM0006
         L     15,VDISP
         BALR  14,15
* DONE-PARA.
P0006    DS    0H
* CLOSE GLACCT
         CLOSE (FD000)
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* BISAM permanent-error exit; a missing record instead
* shows up as a non-zero exception code in the DECB
ISYNAD   MVI   ISFLG,X'01'
         BR    14
ISFLG    DC    X'00'
DB000    DS    0F                  BISAM DECB
         DC    A(0)                +0  ECB
         DC    X'0280'             +4  type
         DC    AL2(0)              +6  length
         DC    A(FD000)            +8  DCB
         DC    A(0)                +12 area, set at OPEN
         DC    A(0)                +16 record pointer word
         DC    A(0)                +20 key, set at READ
         DC    AL2(0)              +24 exception code
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'55'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'10'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'55'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'10'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'55'
PARM0006 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0006)  last parameter
LEN0006  DC    H'12'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
* file control blocks
FD000    DCB   DDNAME=GLACCT,DSORG=IS,MACRF=(R),SYNAD=ISYNAD
K0001    DC    PL8'10303'          numeric constants
K0002    DC    PL8'10301'
K0003    DC    PL8'9999999'
S0001    DC    CL4'GOT '           nonnumeric constants
S0002    DC    CL1' '
S0003    DC    CL10'MISS 10303'
S0004    DC    CL10'MISS 10301'
S0005    DC    CL12'MISS 9999999'
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
SAVEAREA DS    18F
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DS    0CL57               GLAC-RECORD (01 group)
D0001    DC    CL1' '              GLAC-DELETE PIC X(1)
D0002    DC    XL6'00000000000F'   GLAC-KEY PIC 9(10)v0 COMP-3
D0003    DC    PL1'0'              GLAC-CRDB PIC S9(1)v0 COMP-3
D0004    DC    CL1' '              GLAC-CLASS PIC X(1)
D0005    DC    CL2' '              GLAC-SUBCLASS PIC X(2)
D0006    DC    PL6'0'              GLAC-BALANCE PIC S9(11)v2 COMP-3
D0007    DC    CL40' '             GLAC-NAME PIC X(40)
D0008    DC    XL6'00000000000F'   WS-NOMKEY PIC 9(10)v0 COMP-3
D0009    DC    CL10'0000000000'    OUT-KEY PIC 9(10)v0 DISP
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
