*---------------------------------------------------------------
* Generated by cobc370 from ksdsnatu.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
KSDSNATU CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
         SPIE  COBSPIE,((1,15))    report program checks by line
* 000-INITIATE.
P0000    DS    0H
T0000    DS    0H
* DISPLAY
         MVC   DSPBUF+0(40),S0001
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
T0001    DS    0H
* DISPLAY
         MVC   DSPBUF+0(40),S0002
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
T0002    DS    0H
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
T0003    DS    0H
* OPEN I-O KSDS-FILE
         OPEN  (FD000)             VSAM ACB
         LTR   15,15               VSAM request succeeded?
         BZ    G0001
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'30'     permanent error
         B     G0002
G0001    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'00'
G0002    DS    0H
         DROP  8
T0004    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0005(2),S0004      alphanumeric compare
         BE    L0001
T0005    DS    0H
* DISPLAY
         MVC   DSPBUF+0(31),S0005
         MVC   DSPBUF+31(2),D0005
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
T0006    DS    0H
* MOVE Y -> END-OF-FILE-SWITCH
         MVC   D0006(1),S0006      literal move, space padded
         DROP  8
L0001    DS    0H
* 010-PROCESS.
P0001    DS    0H
T0007    DS    0H
* PERFORM 110-PROCESS-DATA THRU 119-EXIT
L0016    DS    0H
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0006(1),S0006      alphanumeric compare
         BE    L0017
         LA    15,R0001            return here
         ST    15,X0004            into the range's exit cell
         B     P0003
R0001    DS    0H
         DROP  8
         LA    15,F0004            restore fall-through
         ST    15,X0004
         B     L0016
L0017    DS    0H
* 020-TERMINATE.
P0002    DS    0H
T0008    DS    0H
* CLOSE KSDS-FILE
         CLOSE (FD000)
         LTR   15,15               VSAM request succeeded?
         BZ    G0003
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'30'     permanent error
         B     G0004
G0003    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'00'
G0004    DS    0H
         DROP  8
T0009    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0005(2),S0004      alphanumeric compare
         BE    L0002
T0010    DS    0H
* DISPLAY
         MVC   DSPBUF+0(32),S0007
         MVC   DSPBUF+32(2),D0005
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
         DROP  8
L0002    DS    0H
T0011    DS    0H
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* 110-PROCESS-DATA.
P0003    DS    0H
T0012    DS    0H
* READ KSDS-FILE
         GET   RPL=FD000R          VSAM sequential retrieval
         LTR   15,15               got a record?
         BNZ   L0003
         LTR   15,15               VSAM request succeeded?
         BZ    G0005
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        end of data
         BE    G0007
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'30'     permanent error
         B     G0006
G0007    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'10'     end of data
         B     G0006
G0005    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'00'
G0006    DS    0H
         DROP  8
         B     L0004
L0003    DS    0H                  AT END
         LTR   15,15               VSAM request succeeded?
         BZ    G0008
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        end of data
         BE    G0010
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'30'     permanent error
         B     G0009
G0010    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'10'     end of data
         B     G0009
G0008    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'00'
G0009    DS    0H
         DROP  8
T0013    DS    0H
* MOVE Y -> END-OF-FILE-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(1),S0006      literal move, space padded
         DROP  8
L0004    DS    0H
T0014    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0006(1),S0006      alphanumeric compare
         BE    L0005
T0015    DS    0H
* PERFORM 120-UPDATE-PROCESS THRU 129-EXIT
         LA    15,R0002            return here
         ST    15,X0006            into the range's exit cell
         B     P0005
R0002    DS    0H
         DROP  8
         LA    15,F0006            restore fall-through
         ST    15,X0006
L0005    DS    0H
* 119-EXIT.
P0004    DS    0H
T0016    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0004
         BR    15
F0004    DS    0H                  fall-through when not performed
* 120-UPDATE-PROCESS.
P0005    DS    0H
T0017    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0003(15),S0008     alphanumeric compare
         BNE   L0006
T0018    DS    0H
* PERFORM 130-UPDATE-IT THRU 139-EXIT
         LA    15,R0003            return here
         ST    15,X0008            into the range's exit cell
         B     P0007
R0003    DS    0H
         DROP  8
         LA    15,F0008            restore fall-through
         ST    15,X0008
L0006    DS    0H
T0019    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0003(15),S0009     alphanumeric compare
         BNE   L0007
T0020    DS    0H
* PERFORM 140-DELETE-IT THRU 149-EXIT
         LA    15,R0004            return here
         ST    15,X0010            into the range's exit cell
         B     P0009
R0004    DS    0H
         DROP  8
         LA    15,F0010            restore fall-through
         ST    15,X0010
L0007    DS    0H
* 129-EXIT.
P0006    DS    0H
T0021    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0006
         BR    15
F0006    DS    0H                  fall-through when not performed
* 130-UPDATE-IT.
P0007    DS    0H
T0022    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(80),D0000
         LA    1,PARM0006
         L     15,VDISP
         BALR  14,15
T0023    DS    0H
* DISPLAY
         MVC   DSPBUF+0(24),S0010
         LA    1,PARM0007
         L     15,VDISP
         BALR  14,15
T0024    DS    0H
* MOVE AUSTIN -> KR-CITY
         MVC   D0003(15),S0011     literal move, space padded
T0025    DS    0H
* MOVE N -> OP-FAILED-SWITCH
         MVC   D0008(1),S0012      literal move, space padded
T0026    DS    0H
* REWRITE KSDS-RECORD
         PUT   RPL=FD000R          put the held record back
         LTR   15,15               done?
         BNZ   L0008
         LTR   15,15               VSAM request succeeded?
         BZ    G0011
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'08'        prime key changed
         BE    G0013
         CLI   VSFB+3,X'10'        no such record
         BE    G0014
         CLI   VSFB+3,X'1C'        cluster is full
         BE    G0015
         MVC   D0005(2),=C'30'     permanent error
         B     G0012
G0013    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'21'     prime key changed
         B     G0012
G0014    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'23'     no such record
         B     G0012
G0015    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'24'     cluster is full
         B     G0012
G0011    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'00'
G0012    DS    0H
         DROP  8
         B     L0009
L0008    DS    0H                  INVALID KEY
         LTR   15,15               VSAM request succeeded?
         BZ    G0016
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'08'        prime key changed
         BE    G0018
         CLI   VSFB+3,X'10'        no such record
         BE    G0019
         CLI   VSFB+3,X'1C'        cluster is full
         BE    G0020
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'30'     permanent error
         B     G0017
G0018    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'21'     prime key changed
         B     G0017
G0019    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'23'     no such record
         B     G0017
G0020    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'24'     cluster is full
         B     G0017
G0016    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'00'
G0017    DS    0H
         DROP  8
T0027    DS    0H
* MOVE Y -> OP-FAILED-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0008(1),S0006      literal move, space padded
         DROP  8
L0009    DS    0H
T0028    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0008(1),S0006      alphanumeric compare
         BE    L0010
T0029    DS    0H
* DISPLAY
         MVC   DSPBUF+0(80),D0000
         LA    1,PARM0008
         L     15,VDISP
         BALR  14,15
T0030    DS    0H
* DISPLAY
         MVC   DSPBUF+0(23),S0013
         LA    1,PARM0009
         L     15,VDISP
         BALR  14,15
         DROP  8
L0010    DS    0H
T0031    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0008(1),S0006      alphanumeric compare
         BNE   L0011
T0032    DS    0H
* DISPLAY
         MVC   DSPBUF+0(30),S0014
         MVC   DSPBUF+30(2),D0005
         LA    1,PARM0010
         L     15,VDISP
         BALR  14,15
         DROP  8
L0011    DS    0H
* 139-EXIT.
P0008    DS    0H
T0033    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0008
         BR    15
F0008    DS    0H                  fall-through when not performed
* 140-DELETE-IT.
P0009    DS    0H
T0034    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(80),D0000
         LA    1,PARM0011
         L     15,VDISP
         BALR  14,15
T0035    DS    0H
* DISPLAY
         MVC   DSPBUF+0(23),S0015
         LA    1,PARM0012
         L     15,VDISP
         BALR  14,15
T0036    DS    0H
* MOVE N -> OP-FAILED-SWITCH
         MVC   D0008(1),S0012      literal move, space padded
T0037    DS    0H
* DELETE KSDS-FILE
         ERASE RPL=FD000R          erase the held record
         LTR   15,15               done?
         BNZ   L0012
         LTR   15,15               VSAM request succeeded?
         BZ    G0021
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'08'        prime key changed
         BE    G0023
         CLI   VSFB+3,X'10'        no such record
         BE    G0024
         CLI   VSFB+3,X'1C'        cluster is full
         BE    G0025
         MVC   D0005(2),=C'30'     permanent error
         B     G0022
G0023    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'21'     prime key changed
         B     G0022
G0024    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'23'     no such record
         B     G0022
G0025    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'24'     cluster is full
         B     G0022
G0021    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'00'
G0022    DS    0H
         DROP  8
         B     L0013
L0012    DS    0H                  INVALID KEY
         LTR   15,15               VSAM request succeeded?
         BZ    G0026
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'08'        prime key changed
         BE    G0028
         CLI   VSFB+3,X'10'        no such record
         BE    G0029
         CLI   VSFB+3,X'1C'        cluster is full
         BE    G0030
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'30'     permanent error
         B     G0027
G0028    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'21'     prime key changed
         B     G0027
G0029    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'23'     no such record
         B     G0027
G0030    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'24'     cluster is full
         B     G0027
G0026    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(2),=C'00'
G0027    DS    0H
         DROP  8
T0038    DS    0H
* MOVE Y -> OP-FAILED-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0008(1),S0006      literal move, space padded
         DROP  8
L0013    DS    0H
T0039    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0008(1),S0006      alphanumeric compare
         BE    L0014
T0040    DS    0H
* DISPLAY
         MVC   DSPBUF+0(12),S0016
         LA    1,PARM0013
         L     15,VDISP
         BALR  14,15
         DROP  8
L0014    DS    0H
T0041    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0008(1),S0006      alphanumeric compare
         BNE   L0015
T0042    DS    0H
* DISPLAY
         MVC   DSPBUF+0(29),S0017
         MVC   DSPBUF+29(2),D0005
         LA    1,PARM0014
         L     15,VDISP
         BALR  14,15
         DROP  8
L0015    DS    0H
* 149-EXIT.
P0010    DS    0H
T0043    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0010
         BR    15
F0010    DS    0H                  fall-through when not performed
X0004    DC    A(F0004)            119-EXIT
X0006    DC    A(F0006)            129-EXIT
X0008    DC    A(F0008)            139-EXIT
X0010    DC    A(F0010)            149-EXIT
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'40'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'40'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'1'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'33'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'34'
PARM0006 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0006)  last parameter
LEN0006  DC    H'80'
PARM0007 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0007)  last parameter
LEN0007  DC    H'24'
PARM0008 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0008)  last parameter
LEN0008  DC    H'80'
PARM0009 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0009)  last parameter
LEN0009  DC    H'23'
PARM0010 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0010)  last parameter
LEN0010  DC    H'32'
PARM0011 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0011)  last parameter
LEN0011  DC    H'80'
PARM0012 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0012)  last parameter
LEN0012  DC    H'23'
PARM0013 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0013)  last parameter
LEN0013  DC    H'12'
PARM0014 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0014)  last parameter
LEN0014  DC    H'31'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
* file control blocks
FD000    ACB   DDNAME=KSDSF01,MACRF=(KEY,SEQ,OUT)  VSAM access method c
FD000R   RPL   ACB=FD000,AREA=D0000,                                   X
               AREALEN=80,RECLEN=80,OPTCD=(KEY,SEQ,UPD,MVE)
S0001    DC    CL40'KSDSUPDT: READ/REWRITE KSDS SEQUENTIALLY'  nonnumer
S0002    DC    CL40'----------------------------------------'
S0003    DC    CL1' '
S0004    DC    CL2'00'
S0005    DC    CL31'VSAM ERROR DURING OPEN, STATUS '
S0006    DC    CL1'Y'
S0007    DC    CL32'VSAM ERROR DURING CLOSE, STATUS '
S0008    DC    CL15'SAN ANTONIO    '
S0009    DC    CL15'DETROIT        '
S0010    DC    CL24'           BEFORE UPDATE'
S0011    DC    CL15'AUSTIN         '
S0012    DC    CL1'N'
S0013    DC    CL23'           AFTER UPDATE'
S0014    DC    CL30'VSAM ERROR ON REWRITE, STATUS '
S0015    DC    CL23'          BEFORE DELETE'
S0016    DC    CL12'   DELETED  '
S0017    DC    CL29'VSAM ERROR ON DELETE, STATUS '
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
VSFB     DS    F                   VSAM SHOWCB feedback word
SAVEAREA DS    18F
* program-check exit: report the source line, then let it abend
COBSPIE  DS    0H
         USING COBSPIE,15
         STM   14,12,SPIEREGS      R15 is our base on entry
         LR    9,15                keep a base across the WTO
         DROP  15
         USING COBSPIE,9
         LR    10,1                the PIE
*  the interruption code, as the digit people know it
         SR    7,7
         IC    7,7(,10)            low byte of the interruption code
         N     7,SPIE15
         LA    7,SPIEHEX(7)
         MVC   SPIECODE(1),0(7)
*  the interrupt address, as an offset into this module
         L     2,8(,10)            second word of the old PSW
         N     2,SPIEADR           leaves the instruction address
         S     2,SPIEBEG           relative to the entry point
*  the last table entry at or before it names the statement
         L     3,SPIETAB
         LH    4,SPIENUM
         SR    5,5                 no line yet
SPIELOOP LTR   4,4
         BZ    SPIEFND
         LH    6,0(,3)             this statement's offset
         CR    6,2
         BH    SPIEFND             past it: the previous one is the ans
         LH    5,2(,3)
         LA    3,4(,3)
         BCTR  4,0
         B     SPIELOOP
SPIEFND  CVD   5,SPIEDW
         UNPK  SPIELINE(5),SPIEDW+5(3)
         OI    SPIELINE+4,X'F0'
         WTO   MF=(E,SPIEWTO)      into the job log, beside the abend
*  cancel the exit and back up to the failing instruction,
*  so the abend happens for real -- same code, same dump
         SR    2,2
         IC    2,7(,10)            the interruption code
         A     2,SPIE3000
         ABEND (2),DUMP
SPIEHEX  DC    C'0123456789ABCDEF'
SPIE15   DC    F'15'
SPIE3000 DC    F'3000'
SPIEADR  DC    X'00FFFFFF'
SPIEBEG  DC    A(COBBEG)
SPIETAB  DC    A(SPIELTB)
SPIENUM  DC    H'44'               statements in the table
SPIEREGS DS    15F
SPIEDW   DS    D
SPIEWTO  WTO   'COBC370: PROGRAM CHECK 0C0 AT SOURCE LINE 00000',      X
               MF=L
SPIECODE EQU   SPIEWTO+29,1        the 0C? digit, patched above
SPIELINE EQU   SPIEWTO+46,5        the line number, likewise
* statement offsets, ascending, paired with source lines
SPIELTB  DS    0H
         DC    AL2(T0000-COBBEG),AL2(32)
         DC    AL2(T0001-COBBEG),AL2(33)
         DC    AL2(T0002-COBBEG),AL2(34)
         DC    AL2(T0003-COBBEG),AL2(35)
         DC    AL2(T0004-COBBEG),AL2(37)
         DC    AL2(T0005-COBBEG),AL2(37)
         DC    AL2(T0006-COBBEG),AL2(38)
         DC    AL2(T0007-COBBEG),AL2(40)
         DC    AL2(T0008-COBBEG),AL2(42)
         DC    AL2(T0009-COBBEG),AL2(44)
         DC    AL2(T0010-COBBEG),AL2(44)
         DC    AL2(T0011-COBBEG),AL2(45)
         DC    AL2(T0012-COBBEG),AL2(48)
         DC    AL2(T0013-COBBEG),AL2(48)
         DC    AL2(T0014-COBBEG),AL2(50)
         DC    AL2(T0015-COBBEG),AL2(50)
         DC    AL2(T0016-COBBEG),AL2(52)
         DC    AL2(T0017-COBBEG),AL2(55)
         DC    AL2(T0018-COBBEG),AL2(55)
         DC    AL2(T0019-COBBEG),AL2(57)
         DC    AL2(T0020-COBBEG),AL2(57)
         DC    AL2(T0021-COBBEG),AL2(59)
         DC    AL2(T0022-COBBEG),AL2(61)
         DC    AL2(T0023-COBBEG),AL2(62)
         DC    AL2(T0024-COBBEG),AL2(63)
         DC    AL2(T0025-COBBEG),AL2(64)
         DC    AL2(T0026-COBBEG),AL2(66)
         DC    AL2(T0027-COBBEG),AL2(66)
         DC    AL2(T0028-COBBEG),AL2(68)
         DC    AL2(T0029-COBBEG),AL2(68)
         DC    AL2(T0030-COBBEG),AL2(69)
         DC    AL2(T0031-COBBEG),AL2(71)
         DC    AL2(T0032-COBBEG),AL2(71)
         DC    AL2(T0033-COBBEG),AL2(73)
         DC    AL2(T0034-COBBEG),AL2(75)
         DC    AL2(T0035-COBBEG),AL2(76)
         DC    AL2(T0036-COBBEG),AL2(77)
         DC    AL2(T0037-COBBEG),AL2(79)
         DC    AL2(T0038-COBBEG),AL2(79)
         DC    AL2(T0039-COBBEG),AL2(81)
         DC    AL2(T0040-COBBEG),AL2(81)
         DC    AL2(T0041-COBBEG),AL2(83)
         DC    AL2(T0042-COBBEG),AL2(83)
         DC    AL2(T0043-COBBEG),AL2(85)
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DS    0CL80               KSDS-RECORD (01 group)
D0001    DC    CL10' '             KR-KEY PIC X(10)
D0002    DC    CL49' '             FILL0002 PIC X(49)
D0003    DC    CL15' '             KR-CITY PIC X(15)
D0004    DC    CL6' '              FILL0004 PIC X(6)
D0005    DC    CL2'00'             WS-STATUS PIC X(2)
         DS    XL6                 reserve the rest of a table
D0006    DC    CL1'N'              END-OF-FILE-SWITCH PIC X(1)
         DS    XL7                 reserve the rest of a table
D0008    DC    CL1'N'              OP-FAILED-SWITCH PIC X(1)
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
