*---------------------------------------------------------------
* Generated by cobc370 from ksdsnatx.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
KSDSNATX CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* 000-INITIATE.
P0000    DS    0H
* DISPLAY
         MVC   DSPBUF+0(43),S0001
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* DISPLAY
         MVC   DSPBUF+0(43),S0002
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
* OPEN INPUT KSDS-FILE
         OPEN  (FD000)             VSAM ACB
         LTR   15,15               VSAM request succeeded?
         BZ    G0001
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0002
G0001    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0002    DS    0H
         DROP  8
* 010-PROCESS.
P0001    DS    0H
* MOVE 2522284049 -> KR-KEY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(10),S0004     literal move, space padded
* PERFORM 100-SEEK-THEN-WALK THRU 109-EXIT
         LA    15,R0001            return here
         ST    15,X0004            into the range's exit cell
         B     P0003
R0001    DS    0H
         DROP  8
         LA    15,F0004            restore fall-through
         ST    15,X0004
* MOVE 0994201010 -> KR-KEY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(10),S0005     literal move, space padded
* PERFORM 100-SEEK-THEN-WALK THRU 109-EXIT
         LA    15,R0002            return here
         ST    15,X0004            into the range's exit cell
         B     P0003
R0002    DS    0H
         DROP  8
         LA    15,F0004            restore fall-through
         ST    15,X0004
* MOVE 9999999999 -> KR-KEY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(10),S0006     literal move, space padded
* PERFORM 100-SEEK-THEN-WALK THRU 109-EXIT
         LA    15,R0003            return here
         ST    15,X0004            into the range's exit cell
         B     P0003
R0003    DS    0H
         DROP  8
         LA    15,F0004            restore fall-through
         ST    15,X0004
* 020-TERMINATE.
P0002    DS    0H
* CLOSE KSDS-FILE
         CLOSE (FD000)
         LTR   15,15               VSAM request succeeded?
         BZ    G0003
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0004
G0003    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0004    DS    0H
         DROP  8
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* 100-SEEK-THEN-WALK.
P0003    DS    0H
* DISPLAY
         MVC   DSPBUF+0(12),S0007
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+12(10),D0001
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
* MOVE N -> MISSING-SWITCH
         MVC   D0006(1),S0008      literal move, space padded
* READ KSDS-FILE
         MODCB RPL=FD000R,OPTCD=(DIR,NSP)  by key
         LTR   15,15
         BZ    G0005
         MVC   D0003(2),=C'30'     could not set the request type
         B     G0006
G0005    DS    0H
         DROP  8
         GET   RPL=FD000R          VSAM retrieval by key
         LTR   15,15               got a record?
         BNZ   L0001
         LTR   15,15               VSAM request succeeded?
         BZ    G0007
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'10'        no such record
         BE    G0009
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0008
G0009    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     no such record
         B     G0008
G0007    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0008    DS    0H
         DROP  8
         B     L0002
L0001    DS    0H                  INVALID KEY
         LTR   15,15               VSAM request succeeded?
         BZ    G0010
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'10'        no such record
         BE    G0012
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0011
G0012    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     no such record
         B     G0011
G0010    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0011    DS    0H
         DROP  8
G0006    DS    0H
* MOVE Y -> MISSING-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(1),S0009      literal move, space padded
         DROP  8
L0002    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0006(1),S0009      alphanumeric compare
         BNE   L0003
* DISPLAY
         MVC   DSPBUF+0(23),S0010
         MVC   DSPBUF+23(2),D0003
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0006
         L     15,VDISP
         BALR  14,15
         DROP  8
L0003    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0006(1),S0009      alphanumeric compare
         BE    L0004
* PERFORM 102-WALK THRU 103-EXIT
         LA    15,R0004            return here
         ST    15,X0006            into the range's exit cell
         B     P0005
R0004    DS    0H
         DROP  8
         LA    15,F0006            restore fall-through
         ST    15,X0006
L0004    DS    0H
* 109-EXIT.
P0004    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0004
         BR    15
F0004    DS    0H                  fall-through when not performed
* 102-WALK.
P0005    DS    0H
* DISPLAY
         MVC   DSPBUF+0(10),S0011
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+10(80),D0000
         LA    1,PARM0007
         L     15,VDISP
         BALR  14,15
* MOVE 0 -> RECORD-COUNTER
         ZAP   PWK1(8),K0001(8)    literal
         UNPK  D0008(8),PWK1(8)    packed -> zoned
* MOVE N -> END-OF-FILE-SWITCH
         MVC   D0004(1),S0008      literal move, space padded
* PERFORM 104-NEXT THRU 105-EXIT
L0016    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0004(1),S0009      alphanumeric compare
         BE    L0017
         PACK  WK0(16),D0008(8)    zoned -> packed
         ZAP   WK1(16),K0002(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BH    L0017
         LA    15,R0005            return here
         ST    15,X0008            into the range's exit cell
         B     P0007
R0005    DS    0H
         DROP  8
         LA    15,F0008            restore fall-through
         ST    15,X0008
         B     L0016
L0017    DS    0H
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0008
         L     15,VDISP
         BALR  14,15
* 103-EXIT.
P0006    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0006
         BR    15
F0006    DS    0H                  fall-through when not performed
* 104-NEXT.
P0007    DS    0H
* READ KSDS-FILE
         MODCB RPL=FD000R,OPTCD=(SEQ)  next
         LTR   15,15
         BZ    G0013
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     could not set the request type
         B     G0014
G0013    DS    0H
         DROP  8
         GET   RPL=FD000R          VSAM sequential retrieval
         LTR   15,15               got a record?
         BNZ   L0005
         LTR   15,15               VSAM request succeeded?
         BZ    G0015
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        end of data
         BE    G0017
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0016
G0017    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'10'     end of data
         B     G0016
G0015    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0016    DS    0H
         DROP  8
         B     L0006
L0005    DS    0H                  AT END
         LTR   15,15               VSAM request succeeded?
         BZ    G0018
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        end of data
         BE    G0020
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0019
G0020    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'10'     end of data
         B     G0019
G0018    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0019    DS    0H
         DROP  8
G0014    DS    0H
* MOVE Y -> END-OF-FILE-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0004(1),S0009      literal move, space padded
         DROP  8
L0006    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0004(1),S0009      alphanumeric compare
         BE    L0007
* DISPLAY
         MVC   DSPBUF+0(10),S0012
         MVC   DSPBUF+10(80),D0000
         LA    1,PARM0009
         L     15,VDISP
         BALR  14,15
         DROP  8
L0007    DS    0H
* ADD 1 -> RECORD-COUNTER
         L     8,BL0000            base locator
         USING WSC0000,8
         PACK  PWK1(8),D0008(8)    zoned -> packed
         ZAP   PWK2(8),K0003(8)    literal
         AP    PWK1(8),PWK2(8)
         UNPK  D0008(8),PWK1(8)    packed -> zoned
         DROP  8
* 105-EXIT.
P0008    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0008
         BR    15
F0008    DS    0H                  fall-through when not performed
X0004    DC    A(F0004)            109-EXIT
X0006    DC    A(F0006)            103-EXIT
X0008    DC    A(F0008)            105-EXIT
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'43'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'43'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'1'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'22'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'25'
PARM0006 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0006)  last parameter
LEN0006  DC    H'1'
PARM0007 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0007)  last parameter
LEN0007  DC    H'90'
PARM0008 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0008)  last parameter
LEN0008  DC    H'1'
PARM0009 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0009)  last parameter
LEN0009  DC    H'90'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
* file control blocks
FD000    ACB   DDNAME=KSDSF01,MACRF=(KEY,SEQ,DIR,IN)  VSAM access metho
FD000R   RPL   ACB=FD000,AREA=D0000,                                   X
               AREALEN=80,RECLEN=80,ARG=D0001,KEYLEN=10,OPTCD=(KEY,SEQ,X
               KEQ,NUP,MVE)
K0001    DC    PL8'0'              numeric constants
K0002    DC    PL8'2'
K0003    DC    PL8'1'
S0001    DC    CL43'KSDSNATX: DYNAMIC, KEYED READ AND READ NEXT'  nonnu
S0002    DC    CL43'-------------------------------------------'
S0003    DC    CL1' '
S0004    DC    CL10'2522284049'
S0005    DC    CL10'0994201010'
S0006    DC    CL10'9999999999'
S0007    DC    CL12'READ BY KEY '
S0008    DC    CL1'N'
S0009    DC    CL1'Y'
S0010    DC    CL23'   NO SUCH KEY, STATUS '
S0011    DC    CL10'   FOUND: '
S0012    DC    CL10'    NEXT: '
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
VSFB     DS    F                   VSAM SHOWCB feedback word
SAVEAREA DS    18F
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DS    0CL80               KSDS-RECORD (01 group)
D0001    DC    CL10' '             KR-KEY PIC X(10)
D0002    DC    CL70' '             FILL0002 PIC X(70)
D0003    DC    CL2'00'             WS-STATUS PIC X(2)
         DS    XL6                 reserve the rest of a table
D0004    DC    CL1'N'              END-OF-FILE-SWITCH PIC X(1)
         DS    XL7                 reserve the rest of a table
D0006    DC    CL1'N'              MISSING-SWITCH PIC X(1)
         DS    XL7                 reserve the rest of a table
D0008    DC    ZL8'0'              RECORD-COUNTER PIC S9(8)v0 DISP
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
