*---------------------------------------------------------------
* Generated by cobc370 from ksdsnats.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
KSDSNATS CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
         SPIE  COBSPIE,((1,15))    report program checks by line
* 000-INITIATE.
P0000    DS    0H
T0000    DS    0H
* DISPLAY
         MVC   DSPBUF+0(42),S0001
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
T0001    DS    0H
* DISPLAY
         MVC   DSPBUF+0(42),S0002
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
T0002    DS    0H
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
T0003    DS    0H
* OPEN INPUT KSDS-FILE
         OPEN  (FD000)             VSAM ACB
         LTR   15,15               VSAM request succeeded?
         BZ    G0001
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0002
G0001    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0002    DS    0H
         DROP  8
T0004    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0003(2),S0004      alphanumeric compare
         BE    L0001
T0005    DS    0H
* DISPLAY
         MVC   DSPBUF+0(31),S0005
         MVC   DSPBUF+31(2),D0003
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
T0006    DS    0H
* MOVE Y -> END-OF-FILE-SWITCH
         MVC   D0004(1),S0006      literal move, space padded
         DROP  8
L0001    DS    0H
* 010-PROCESS.
P0001    DS    0H
T0007    DS    0H
* PERFORM 110-PROCESS-DATA THRU 119-EXIT
L0015    DS    0H
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0004(1),S0006      alphanumeric compare
         BE    L0016
         LA    15,R0001            return here
         ST    15,X0004            into the range's exit cell
         B     P0003
R0001    DS    0H
         DROP  8
         LA    15,F0004            restore fall-through
         ST    15,X0004
         B     L0015
L0016    DS    0H
* 020-TERMINATE.
P0002    DS    0H
T0008    DS    0H
* CLOSE KSDS-FILE
         CLOSE (FD000)
         LTR   15,15               VSAM request succeeded?
         BZ    G0003
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0004
G0003    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0004    DS    0H
         DROP  8
T0009    DS    0H
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* 110-PROCESS-DATA.
P0003    DS    0H
T0010    DS    0H
* MOVE 1033846021 -> KR-KEY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(10),S0007     literal move, space padded
T0011    DS    0H
* DISPLAY
         MVC   DSPBUF+0(19),S0008
         MVC   DSPBUF+19(10),D0001
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
T0012    DS    0H
* MOVE N -> START-FAILED-SWITCH
         MVC   D0006(1),S0009      literal move, space padded
T0013    DS    0H
* START KSDS-FILE
         MODCB RPL=FD000R,OPTCD=(KEQ)  equal to
         LTR   15,15
         BNZ   L0002
         POINT RPL=FD000R          position by key
         LTR   15,15               positioned?
         BNZ   L0002
         LTR   15,15               VSAM request succeeded?
         BZ    G0005
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        nothing at or after the key
         BE    G0007
         CLI   VSFB+3,X'10'        no such record
         BE    G0008
         MVC   D0003(2),=C'30'     permanent error
         B     G0006
G0007    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     nothing at or after the key
         B     G0006
G0008    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     no such record
         B     G0006
G0005    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0006    DS    0H
         DROP  8
         B     L0003
L0002    DS    0H                  INVALID KEY
         LTR   15,15               VSAM request succeeded?
         BZ    G0009
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        nothing at or after the key
         BE    G0011
         CLI   VSFB+3,X'10'        no such record
         BE    G0012
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0010
G0011    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     nothing at or after the key
         B     G0010
G0012    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     no such record
         B     G0010
G0009    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0010    DS    0H
         DROP  8
T0014    DS    0H
* MOVE Y -> START-FAILED-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(1),S0006      literal move, space padded
         DROP  8
L0003    DS    0H
T0015    DS    0H
* PERFORM 120-START-AND-READ THRU 129-EXIT
         LA    15,R0002            return here
         ST    15,X0006            into the range's exit cell
         B     P0005
R0002    DS    0H
         LA    15,F0006            restore fall-through
         ST    15,X0006
T0016    DS    0H
* MOVE 2534789096 -> KR-KEY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(10),S0010     literal move, space padded
T0017    DS    0H
* DISPLAY
         MVC   DSPBUF+0(19),S0008
         MVC   DSPBUF+19(10),D0001
         LA    1,PARM0006
         L     15,VDISP
         BALR  14,15
T0018    DS    0H
* MOVE N -> START-FAILED-SWITCH
         MVC   D0006(1),S0009      literal move, space padded
T0019    DS    0H
* START KSDS-FILE
         MODCB RPL=FD000R,OPTCD=(KEQ)  equal to
         LTR   15,15
         BNZ   L0004
         POINT RPL=FD000R          position by key
         LTR   15,15               positioned?
         BNZ   L0004
         LTR   15,15               VSAM request succeeded?
         BZ    G0013
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        nothing at or after the key
         BE    G0015
         CLI   VSFB+3,X'10'        no such record
         BE    G0016
         MVC   D0003(2),=C'30'     permanent error
         B     G0014
G0015    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     nothing at or after the key
         B     G0014
G0016    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     no such record
         B     G0014
G0013    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0014    DS    0H
         DROP  8
         B     L0005
L0004    DS    0H                  INVALID KEY
         LTR   15,15               VSAM request succeeded?
         BZ    G0017
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        nothing at or after the key
         BE    G0019
         CLI   VSFB+3,X'10'        no such record
         BE    G0020
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0018
G0019    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     nothing at or after the key
         B     G0018
G0020    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     no such record
         B     G0018
G0017    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0018    DS    0H
         DROP  8
T0020    DS    0H
* MOVE Y -> START-FAILED-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(1),S0006      literal move, space padded
         DROP  8
L0005    DS    0H
T0021    DS    0H
* PERFORM 120-START-AND-READ THRU 129-EXIT
         LA    15,R0003            return here
         ST    15,X0006            into the range's exit cell
         B     P0005
R0003    DS    0H
         LA    15,F0006            restore fall-through
         ST    15,X0006
T0022    DS    0H
* MOVE 3284189067 -> KR-KEY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(10),S0011     literal move, space padded
T0023    DS    0H
* DISPLAY
         MVC   DSPBUF+0(35),S0012
         MVC   DSPBUF+35(10),D0001
         LA    1,PARM0007
         L     15,VDISP
         BALR  14,15
T0024    DS    0H
* MOVE N -> START-FAILED-SWITCH
         MVC   D0006(1),S0009      literal move, space padded
T0025    DS    0H
* START KSDS-FILE
         MODCB RPL=FD000R,OPTCD=(KGE)  not less than
         LTR   15,15
         BNZ   L0006
         POINT RPL=FD000R          position by key
         LTR   15,15               positioned?
         BNZ   L0006
         LTR   15,15               VSAM request succeeded?
         BZ    G0021
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        nothing at or after the key
         BE    G0023
         CLI   VSFB+3,X'10'        no such record
         BE    G0024
         MVC   D0003(2),=C'30'     permanent error
         B     G0022
G0023    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     nothing at or after the key
         B     G0022
G0024    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     no such record
         B     G0022
G0021    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0022    DS    0H
         DROP  8
         B     L0007
L0006    DS    0H                  INVALID KEY
         LTR   15,15               VSAM request succeeded?
         BZ    G0025
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        nothing at or after the key
         BE    G0027
         CLI   VSFB+3,X'10'        no such record
         BE    G0028
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0026
G0027    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     nothing at or after the key
         B     G0026
G0028    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     no such record
         B     G0026
G0025    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0026    DS    0H
         DROP  8
T0026    DS    0H
* MOVE Y -> START-FAILED-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(1),S0006      literal move, space padded
         DROP  8
L0007    DS    0H
T0027    DS    0H
* PERFORM 120-START-AND-READ THRU 129-EXIT
         LA    15,R0004            return here
         ST    15,X0006            into the range's exit cell
         B     P0005
R0004    DS    0H
         LA    15,F0006            restore fall-through
         ST    15,X0006
T0028    DS    0H
* MOVE 3860000000 -> KR-KEY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(10),S0013     literal move, space padded
T0029    DS    0H
* DISPLAY
         MVC   DSPBUF+0(35),S0012
         MVC   DSPBUF+35(10),D0001
         LA    1,PARM0008
         L     15,VDISP
         BALR  14,15
T0030    DS    0H
* MOVE N -> START-FAILED-SWITCH
         MVC   D0006(1),S0009      literal move, space padded
T0031    DS    0H
* START KSDS-FILE
         MODCB RPL=FD000R,OPTCD=(KGE)  not less than
         LTR   15,15
         BNZ   L0008
         POINT RPL=FD000R          position by key
         LTR   15,15               positioned?
         BNZ   L0008
         LTR   15,15               VSAM request succeeded?
         BZ    G0029
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        nothing at or after the key
         BE    G0031
         CLI   VSFB+3,X'10'        no such record
         BE    G0032
         MVC   D0003(2),=C'30'     permanent error
         B     G0030
G0031    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     nothing at or after the key
         B     G0030
G0032    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     no such record
         B     G0030
G0029    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0030    DS    0H
         DROP  8
         B     L0009
L0008    DS    0H                  INVALID KEY
         LTR   15,15               VSAM request succeeded?
         BZ    G0033
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        nothing at or after the key
         BE    G0035
         CLI   VSFB+3,X'10'        no such record
         BE    G0036
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0034
G0035    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     nothing at or after the key
         B     G0034
G0036    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'23'     no such record
         B     G0034
G0033    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0034    DS    0H
         DROP  8
T0032    DS    0H
* MOVE Y -> START-FAILED-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0006(1),S0006      literal move, space padded
         DROP  8
L0009    DS    0H
T0033    DS    0H
* PERFORM 120-START-AND-READ THRU 129-EXIT
         LA    15,R0005            return here
         ST    15,X0006            into the range's exit cell
         B     P0005
R0005    DS    0H
         LA    15,F0006            restore fall-through
         ST    15,X0006
T0034    DS    0H
* MOVE Y -> END-OF-FILE-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0004(1),S0006      literal move, space padded
         DROP  8
* 119-EXIT.
P0004    DS    0H
T0035    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0004
         BR    15
F0004    DS    0H                  fall-through when not performed
* 120-START-AND-READ.
P0005    DS    0H
T0036    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0006(1),S0006      alphanumeric compare
         BNE   L0010
T0037    DS    0H
* DISPLAY
         MVC   DSPBUF+0(24),S0014
         LA    1,PARM0009
         L     15,VDISP
         BALR  14,15
         DROP  8
L0010    DS    0H
T0038    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0006(1),S0006      alphanumeric compare
         BE    L0011
T0039    DS    0H
* PERFORM 122-READ-FIVE THRU 123-EXIT
         LA    15,R0006            return here
         ST    15,X0008            into the range's exit cell
         B     P0007
R0006    DS    0H
         DROP  8
         LA    15,F0008            restore fall-through
         ST    15,X0008
L0011    DS    0H
* 129-EXIT.
P0006    DS    0H
T0040    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0006
         BR    15
F0006    DS    0H                  fall-through when not performed
* 122-READ-FIVE.
P0007    DS    0H
T0041    DS    0H
* MOVE 0 -> RECORD-COUNTER
         ZAP   PWK1(8),K0001(8)    literal
         L     8,BL0000            base locator
         USING WSC0000,8
         UNPK  D0008(8),PWK1(8)    packed -> zoned
T0042    DS    0H
* PERFORM 130-READ-AND-DISPLAY THRU 139-EXIT
L0027    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0004(1),S0006      alphanumeric compare
         BE    L0028
         PACK  WK0(16),D0008(8)    zoned -> packed
         ZAP   WK1(16),K0002(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BH    L0028
         LA    15,R0007            return here
         ST    15,X0010            into the range's exit cell
         B     P0009
R0007    DS    0H
         DROP  8
         LA    15,F0010            restore fall-through
         ST    15,X0010
         B     L0027
L0028    DS    0H
T0043    DS    0H
* MOVE N -> END-OF-FILE-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0004(1),S0009      literal move, space padded
         DROP  8
* 123-EXIT.
P0008    DS    0H
T0044    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0008
         BR    15
F0008    DS    0H                  fall-through when not performed
* 130-READ-AND-DISPLAY.
P0009    DS    0H
T0045    DS    0H
* READ KSDS-FILE
         GET   RPL=FD000R          VSAM sequential retrieval
         LTR   15,15               got a record?
         BNZ   L0012
         LTR   15,15               VSAM request succeeded?
         BZ    G0037
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        end of data
         BE    G0039
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0038
G0039    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'10'     end of data
         B     G0038
G0037    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0038    DS    0H
         DROP  8
         B     L0013
L0012    DS    0H                  AT END
         LTR   15,15               VSAM request succeeded?
         BZ    G0040
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        end of data
         BE    G0042
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'30'     permanent error
         B     G0041
G0042    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'10'     end of data
         B     G0041
G0040    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(2),=C'00'
G0041    DS    0H
         DROP  8
T0046    DS    0H
* MOVE Y -> END-OF-FILE-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0004(1),S0006      literal move, space padded
         DROP  8
L0013    DS    0H
T0047    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0004(1),S0006      alphanumeric compare
         BE    L0014
T0048    DS    0H
* DISPLAY
         MVC   DSPBUF+0(5),S0015
         MVC   DSPBUF+5(10),D0001
         MVC   DSPBUF+15(10),S0016
         MVC   DSPBUF+25(80),D0000
         LA    1,PARM0010
         L     15,VDISP
         BALR  14,15
         DROP  8
L0014    DS    0H
T0049    DS    0H
* ADD 1 -> RECORD-COUNTER
         L     8,BL0000            base locator
         USING WSC0000,8
         PACK  PWK1(8),D0008(8)    zoned -> packed
         ZAP   PWK2(8),K0003(8)    literal
         AP    PWK1(8),PWK2(8)
         UNPK  D0008(8),PWK1(8)    packed -> zoned
         DROP  8
* 139-EXIT.
P0010    DS    0H
T0050    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0010
         BR    15
F0010    DS    0H                  fall-through when not performed
X0004    DC    A(F0004)            119-EXIT
X0006    DC    A(F0006)            129-EXIT
X0008    DC    A(F0008)            123-EXIT
X0010    DC    A(F0010)            139-EXIT
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'42'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'42'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'1'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'33'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'29'
PARM0006 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0006)  last parameter
LEN0006  DC    H'29'
PARM0007 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0007)  last parameter
LEN0007  DC    H'45'
PARM0008 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0008)  last parameter
LEN0008  DC    H'45'
PARM0009 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0009)  last parameter
LEN0009  DC    H'24'
PARM0010 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0010)  last parameter
LEN0010  DC    H'105'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
* file control blocks
FD000    ACB   DDNAME=KSDSF01,MACRF=(KEY,SEQ,IN)  VSAM access method co
FD000R   RPL   ACB=FD000,AREA=D0000,                                   X
               AREALEN=80,RECLEN=80,ARG=D0001,KEYLEN=10,OPTCD=(KEY,SEQ,X
               NUP,MVE)
K0001    DC    PL8'0'              numeric constants
K0002    DC    PL8'4'
K0003    DC    PL8'1'
S0001    DC    CL42'KSDSSSEQ: READ KSDS SEQUENTIALLY (W/START)'  nonnum
S0002    DC    CL42'------------------------------------------'
S0003    DC    CL1' '
S0004    DC    CL2'00'
S0005    DC    CL31'VSAM ERROR DURING OPEN, STATUS '
S0006    DC    CL1'Y'
S0007    DC    CL10'1033846021'
S0008    DC    CL19'START KEY EQUAL TO '
S0009    DC    CL1'N'
S0010    DC    CL10'2534789096'
S0011    DC    CL10'3284189067'
S0012    DC    CL35'START KEY GREATER THAN OR EQUAL TO '
S0013    DC    CL10'3860000000'
S0014    DC    CL24'*** RECORD NOT FOUND ***'
S0015    DC    CL5'KEY: '
S0016    DC    CL10'  RECORD: '
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
VSFB     DS    F                   VSAM SHOWCB feedback word
SAVEAREA DS    18F
* program-check exit: report the source line, then let it abend
COBSPIE  DS    0H
         USING COBSPIE,15
         STM   14,12,SPIEREGS      R15 is our base on entry
         LR    9,15                keep a base across the WTO
         DROP  15
         USING COBSPIE,9
         LR    10,1                the PIE
*  the interruption code, as the digit people know it
         SR    7,7
         IC    7,7(,10)            low byte of the interruption code
         N     7,SPIE15
         LA    7,SPIEHEX(7)
         MVC   SPIECODE(1),0(7)
*  the interrupt address, as an offset into this module
         L     2,8(,10)            second word of the old PSW
         N     2,SPIEADR           leaves the instruction address
         S     2,SPIEBEG           relative to the entry point
*  the last table entry at or before it names the statement
         L     3,SPIETAB
         LH    4,SPIENUM
         SR    5,5                 no line yet
SPIELOOP LTR   4,4
         BZ    SPIEFND
         LH    6,0(,3)             this statement's offset
         CR    6,2
         BH    SPIEFND             past it: the previous one is the ans
         LH    5,2(,3)
         LA    3,4(,3)
         BCTR  4,0
         B     SPIELOOP
SPIEFND  CVD   5,SPIEDW
         UNPK  SPIELINE(5),SPIEDW+5(3)
         OI    SPIELINE+4,X'F0'
         WTO   MF=(E,SPIEWTO)      into the job log, beside the abend
*  cancel the exit and back up to the failing instruction,
*  so the abend happens for real -- same code, same dump
         SR    2,2
         IC    2,7(,10)            the interruption code
         A     2,SPIE3000
         ABEND (2),DUMP
SPIEHEX  DC    C'0123456789ABCDEF'
SPIE15   DC    F'15'
SPIE3000 DC    F'3000'
SPIEADR  DC    X'00FFFFFF'
SPIEBEG  DC    A(COBBEG)
SPIETAB  DC    A(SPIELTB)
SPIENUM  DC    H'51'               statements in the table
SPIEREGS DS    15F
SPIEDW   DS    D
SPIEWTO  WTO   'COBC370: PROGRAM CHECK 0C0 AT SOURCE LINE 00000',      X
               MF=L
SPIECODE EQU   SPIEWTO+29,1        the 0C? digit, patched above
SPIELINE EQU   SPIEWTO+46,5        the line number, likewise
* statement offsets, ascending, paired with source lines
SPIELTB  DS    0H
         DC    AL2(T0000-COBBEG),AL2(30)
         DC    AL2(T0001-COBBEG),AL2(31)
         DC    AL2(T0002-COBBEG),AL2(32)
         DC    AL2(T0003-COBBEG),AL2(33)
         DC    AL2(T0004-COBBEG),AL2(35)
         DC    AL2(T0005-COBBEG),AL2(35)
         DC    AL2(T0006-COBBEG),AL2(36)
         DC    AL2(T0007-COBBEG),AL2(38)
         DC    AL2(T0008-COBBEG),AL2(40)
         DC    AL2(T0009-COBBEG),AL2(41)
         DC    AL2(T0010-COBBEG),AL2(43)
         DC    AL2(T0011-COBBEG),AL2(44)
         DC    AL2(T0012-COBBEG),AL2(45)
         DC    AL2(T0013-COBBEG),AL2(46)
         DC    AL2(T0014-COBBEG),AL2(47)
         DC    AL2(T0015-COBBEG),AL2(48)
         DC    AL2(T0016-COBBEG),AL2(49)
         DC    AL2(T0017-COBBEG),AL2(50)
         DC    AL2(T0018-COBBEG),AL2(51)
         DC    AL2(T0019-COBBEG),AL2(52)
         DC    AL2(T0020-COBBEG),AL2(53)
         DC    AL2(T0021-COBBEG),AL2(54)
         DC    AL2(T0022-COBBEG),AL2(55)
         DC    AL2(T0023-COBBEG),AL2(56)
         DC    AL2(T0024-COBBEG),AL2(57)
         DC    AL2(T0025-COBBEG),AL2(58)
         DC    AL2(T0026-COBBEG),AL2(59)
         DC    AL2(T0027-COBBEG),AL2(60)
         DC    AL2(T0028-COBBEG),AL2(61)
         DC    AL2(T0029-COBBEG),AL2(62)
         DC    AL2(T0030-COBBEG),AL2(63)
         DC    AL2(T0031-COBBEG),AL2(64)
         DC    AL2(T0032-COBBEG),AL2(65)
         DC    AL2(T0033-COBBEG),AL2(66)
         DC    AL2(T0034-COBBEG),AL2(67)
         DC    AL2(T0035-COBBEG),AL2(69)
         DC    AL2(T0036-COBBEG),AL2(72)
         DC    AL2(T0037-COBBEG),AL2(72)
         DC    AL2(T0038-COBBEG),AL2(74)
         DC    AL2(T0039-COBBEG),AL2(74)
         DC    AL2(T0040-COBBEG),AL2(76)
         DC    AL2(T0041-COBBEG),AL2(78)
         DC    AL2(T0042-COBBEG),AL2(79)
         DC    AL2(T0043-COBBEG),AL2(81)
         DC    AL2(T0044-COBBEG),AL2(83)
         DC    AL2(T0045-COBBEG),AL2(86)
         DC    AL2(T0046-COBBEG),AL2(86)
         DC    AL2(T0047-COBBEG),AL2(88)
         DC    AL2(T0048-COBBEG),AL2(88)
         DC    AL2(T0049-COBBEG),AL2(89)
         DC    AL2(T0050-COBBEG),AL2(91)
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DS    0CL80               KSDS-RECORD (01 group)
D0001    DC    CL10' '             KR-KEY PIC X(10)
D0002    DC    CL70' '             FILL0002 PIC X(70)
D0003    DC    CL2'00'             WS-STATUS PIC X(2)
         DS    XL6                 reserve the rest of a table
D0004    DC    CL1'N'              END-OF-FILE-SWITCH PIC X(1)
         DS    XL7                 reserve the rest of a table
D0006    DC    CL1'N'              START-FAILED-SWITCH PIC X(1)
         DS    XL7                 reserve the rest of a table
D0008    DC    ZL8'0'              RECORD-COUNTER PIC S9(8)v0 DISP
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL,COBDATE
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBDATE -- fill an 8-byte field with MM/DD/YY.
*   R1 -> the field.  TIME DEC hands back the date as packed
*   00YYDDDF, which is Julian, so the day of year has to be
*   walked into a month and a day.
*
COBDATE  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE4+4
         LA    11,RTSAVE4
         ST    11,8(13)
         LR    13,11
         LR    2,1                 the field, before TIME takes R1
         TIME  DEC                 R0 = HHMMSSth, R1 = 00YYDDDF
         ST    1,DTPACK
         UNPK  DTZONE(7),DTPACK(4)  '00YYDDD'
         OI    DTZONE+6,X'F0'
         PACK  DTDW(8),DTZONE+4(3)
         CVB   3,DTDW              day of the year
         PACK  DTDW(8),DTZONE+2(2)
         CVB   4,DTDW              the year
         N     4,DTF3              zero if a leap year -- 1901-2099, so
*                             mod 4 is the whole rule
         LA    5,1                 month
         LA    6,DTMON
DT010    SR    7,7
         IC    7,0(0,6)            days in this month
         CH    5,DTH2              February?
         BNE   DT020
         LTR   4,4
         BNZ   DT020
         LA    7,1(0,7)            29 this year
DT020    CR    3,7
         BNH   DT030               the day falls in this month
         SR    3,7
         LA    5,1(0,5)
         LA    6,1(0,6)
         B     DT010
DT030    CVD   5,DTDW
         UNPK  0(2,2),DTDW+6(2)    MM
         OI    1(2),X'F0'
         MVI   2(2),C'/'
         CVD   3,DTDW
         UNPK  3(2,2),DTDW+6(2)    DD
         OI    4(2),X'F0'
         MVI   5(2),C'/'
         MVC   6(2,2),DTZONE+2     YY, already zoned
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
DTMON    DC    AL1(31,28,31,30,31,30,31,31,30,31,30,31)
DTF3     DC    F'3'
DTH2     DC    H'2'
DTPACK   DS    F
DTZONE   DS    CL8
DTDW     DS    D
RTSAVE4  DS    18F
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
