*---------------------------------------------------------------
* Generated by cobc370 from tests/occtest.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
OCCTEST  CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* MAIN-PARA.
P0000    DS    0H
* MOVE 1 -> WS-IDX
         ZAP   PWK1(8),K0001(8)    literal
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         L     8,BL0000            base locator
         USING WSC0000,8
         STH   2,D0006
         DROP  8
* FILL-LOOP.
P0001    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0006
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0002(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BNH   L0001
* GO TO FILL-DONE
         B     P0002
         DROP  8
L0001    DS    0H
* COMPUTE YT-DEBITS = ...
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0006
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0003(8)    literal
         ZAP   MULT8(8),WK1(16)    MP takes at most 8 bytes on the righ
         MP    WK0(16),MULT8(8)    scale becomes the sum of the scales
         SRP   WK0(16),2,0         align scale (left)
         ZAP   PWK1(8),WK0(16)
         LH    6,D0006             subscript
         BCTR  6,0                 subscript-1
         MH    6,H0001             times element size
         LA    6,D0002(6)          element address
         ZAP   0(5,6),PWK1(8)
* COMPUTE YT-CREDITS = ...
         LH    2,D0006
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0004(8)    literal
         ZAP   MULT8(8),WK1(16)    MP takes at most 8 bytes on the righ
         MP    WK0(16),MULT8(8)    scale becomes the sum of the scales
         SRP   WK0(16),2,0         align scale (left)
         ZAP   PWK1(8),WK0(16)
         LH    6,D0006             subscript
         BCTR  6,0                 subscript-1
         MH    6,H0001             times element size
         LA    6,D0003(6)          element address
         ZAP   0(5,6),PWK1(8)
* ADD 1 -> WS-IDX
         LH    2,D0006
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         ZAP   PWK2(8),K0001(8)    literal
         AP    PWK1(8),PWK2(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         STH   2,D0006
* GO TO FILL-LOOP
         B     P0001
         DROP  8
* FILL-DONE.
P0002    DS    0H
* MOVE 3 -> WS-IDX
         ZAP   PWK1(8),K0005(8)    literal
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         L     8,BL0000            base locator
         USING WSC0000,8
         STH   2,D0006
* MOVE YT-DEBITS -> OUT-NUM
         LH    7,D0006             subscript
         BCTR  7,0                 subscript-1
         MH    7,H0001             times element size
         LA    7,D0002(7)          element address
         ZAP   PWK1(8),0(5,7)
         UNPK  D0007(9),PWK1(8)    packed -> zoned
         OI    D0007+8,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(9),D0007
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* MOVE YT-CREDITS -> OUT-NUM
         LH    7,D0006             subscript
         BCTR  7,0                 subscript-1
         MH    7,H0001             times element size
         LA    7,D0003(7)          element address
         ZAP   PWK1(8),0(5,7)
         UNPK  D0007(9),PWK1(8)    packed -> zoned
         OI    D0007+8,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(9),D0007
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
* MOVE YT-DEBITS -> OUT-NUM
         LA    7,4                 subscript-1
         MH    7,H0001             times element size
         LA    7,D0002(7)          element address
         ZAP   PWK1(8),0(5,7)
         UNPK  D0007(9),PWK1(8)    packed -> zoned
         OI    D0007+8,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(9),D0007
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
* COMPUTE OUT-NUM = ...
         LA    7,1                 subscript-1
         MH    7,H0001             times element size
         LA    7,D0002(7)          element address
         ZAP   WK0(16),0(5,7)
         LA    7,3                 subscript-1
         MH    7,H0001             times element size
         LA    7,D0003(7)          element address
         ZAP   WK1(16),0(5,7)
         AP    WK0(16),WK1(16)
         ZAP   PWK1(8),WK0(16)
         UNPK  D0007(9),PWK1(8)    packed -> zoned
         OI    D0007+8,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(9),D0007
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
* MOVE 12 -> MD-ENTRY
         ZAP   PWK1(8),K0006(8)    literal
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         LA    6,0                 subscript-1
         MH    6,H0002             times element size
         LA    6,D0005(6)          element address
         STH   2,0(,6)
* MOVE 31 -> MD-ENTRY
         ZAP   PWK1(8),K0007(8)    literal
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         LA    6,11                subscript-1
         MH    6,H0002             times element size
         LA    6,D0005(6)          element address
         STH   2,0(,6)
* MOVE MD-ENTRY -> OUT-SMALL
         LA    7,11                subscript-1
         MH    7,H0002             times element size
         LA    7,D0005(7)          element address
         LH    2,0(,7)
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         UNPK  D0008(4),PWK1(8)    packed -> zoned
         OI    D0008+3,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(4),D0008
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'9'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'9'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'9'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'9'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'4'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
K0001    DC    PL8'1'              numeric constants
K0002    DC    PL8'5'
K0003    DC    PL8'100'
K0004    DC    PL8'10'
K0005    DC    PL8'3'
K0006    DC    PL8'12'
K0007    DC    PL8'31'
H0001    DC    H'10'               element sizes
H0002    DC    H'2'
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
SAVEAREA DS    18F
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DS    0CL50               YEARLY-TABLE (01 group)
D0001    DS    0CL10               YEARLY-TOTALS (05 group, OCCURS 5)
D0002    DC    PL5'0'              YT-DEBITS PIC S9(9)v2 COMP-3
D0003    DC    PL5'0'              YT-CREDITS PIC S9(9)v2 COMP-3
         DS    XL40                reserve the rest of a table
D0004    DS    0CL24               MONTH-DAYS (01 group)
D0005    DC    12H'0'              MD-ENTRY PIC 9(2)v0 COMP table
D0006    DC    H'1'                WS-IDX PIC S9(4)v0 COMP
D0007    DC    CL9'000000000'      OUT-NUM PIC 9(9)v2 DISP
D0008    DC    CL4'0000'           OUT-SMALL PIC 9(4)v0 DISP
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
