*---------------------------------------------------------------
* Generated by cobc370 from /Users/sdennis/cobc370/tests/perftest.cb
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
PERFTEST CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* MAIN-PARA.
P0000    DS    0H
* PERFORM FILL-PARA THRU FILL-EXIT
         ZAP   WK0(16),K0001(8)    literal
         ZAP   PWK1(8),WK0(16)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         L     8,BL0000            base locator
         USING WSC0000,8
         STH   2,D0003
L0002    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0003
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0002(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BH    L0003
         LA    15,R0001            return here
         ST    15,X0002            into the range's exit cell
         B     P0001
R0001    DS    0H
         DROP  8
         LA    15,F0002            restore fall-through
         ST    15,X0002
         ZAP   WK0(16),K0001(8)    literal
         ZAP   PWK2(8),WK0(16)
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0003
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         AP    PWK1(8),PWK2(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         STH   2,D0003
         B     L0002
L0003    DS    0H
         DROP  8
* MOVE WS-IDX -> OUT-NUM
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0003
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         UNPK  D0008(7),PWK1(8)    packed -> zoned
         OI    D0008+6,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(7),D0008
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* MOVE 0 -> WS-TOT
         ZAP   PWK1(8),K0003(8)    literal
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         ST    2,D0004
* MOVE 1 -> WS-IDX
         ZAP   PWK1(8),K0001(8)    literal
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         STH   2,D0003
* PERFORM SUM-PARA THRU SUM-EXIT
L0004    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0003
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0002(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BH    L0005
         LH    7,D0003             subscript
         BCTR  7,0                 subscript-1
         MH    7,H0001             times element size
         LA    7,D0002(7)          element address
         LH    2,0(,7)
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0004(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BH    L0005
         LA    15,R0002            return here
         ST    15,X0004            into the range's exit cell
         B     P0003
R0002    DS    0H
         DROP  8
         LA    15,F0004            restore fall-through
         ST    15,X0004
         B     L0004
L0005    DS    0H
* MOVE WS-TOT -> OUT-NUM
         L     8,BL0000            base locator
         USING WSC0000,8
         L     2,D0004
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         UNPK  D0008(7),PWK1(8)    packed -> zoned
         OI    D0008+6,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(7),D0008
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
* MOVE 0 -> WS-CNT
         ZAP   PWK1(8),K0003(8)    literal
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         STH   2,D0005
* PERFORM EOF-PARA THRU EOF-EXIT
L0006    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0006(1),S0001      alphanumeric compare
         BE    L0007
         LA    15,R0003            return here
         ST    15,X0006            into the range's exit cell
         B     P0005
R0003    DS    0H
         DROP  8
         LA    15,F0006            restore fall-through
         ST    15,X0006
         B     L0006
L0007    DS    0H
* MOVE WS-CNT -> OUT-NUM
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0005
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         UNPK  D0008(7),PWK1(8)    packed -> zoned
         OI    D0008+6,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(7),D0008
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
* MOVE 0 -> WS-CNT
         ZAP   PWK1(8),K0003(8)    literal
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         STH   2,D0005
* PERFORM BUMP-PARA THRU BUMP-EXIT
         ZAP   WK0(16),K0005(8)    literal
         ZAP   DWK(8),WK0(16)
         CVB   2,DWK               repeat count
         STH   2,PT014
L0008    DS    0H
         DROP  8
         LH    2,PT014
         LTR   2,2
         BNP   L0009
         LA    15,R0004            return here
         ST    15,X0008            into the range's exit cell
         B     P0007
R0004    DS    0H
         LA    15,F0008            restore fall-through
         ST    15,X0008
         LH    2,PT014
         BCTR  2,0
         STH   2,PT014
         B     L0008
L0009    DS    0H
* MOVE WS-CNT -> OUT-NUM
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0005
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         UNPK  D0008(7),PWK1(8)    packed -> zoned
         OI    D0008+6,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(7),D0008
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
* MOVE 0 -> WS-CNT
         ZAP   PWK1(8),K0003(8)    literal
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         STH   2,D0005
* PERFORM BUMP-PARA THRU BUMP-EXIT
L0010    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0005
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0003(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BE    L0011
         LA    15,R0005            return here
         ST    15,X0008            into the range's exit cell
         B     P0007
R0005    DS    0H
         DROP  8
         LA    15,F0008            restore fall-through
         ST    15,X0008
         B     L0010
L0011    DS    0H
* MOVE WS-CNT -> OUT-NUM
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0005
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         UNPK  D0008(7),PWK1(8)    packed -> zoned
         OI    D0008+6,X'F0'       unsigned: force an F zone
* DISPLAY
         MVC   DSPBUF+0(7),D0008
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
         DROP  8
* FILL-PARA.
P0001    DS    0H
* MOVE WS-IDX -> ENT-YEAR
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0003
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         LH    6,D0003             subscript
         BCTR  6,0                 subscript-1
         MH    6,H0001             times element size
         LA    6,D0002(6)          element address
         STH   2,0(,6)
         DROP  8
* FILL-EXIT.
P0002    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0002
         BR    15
F0002    DS    0H                  fall-through when not performed
* SUM-PARA.
P0003    DS    0H
* ADD ENT-YEAR -> WS-TOT
         L     8,BL0000            base locator
         USING WSC0000,8
         L     2,D0004
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         LH    7,D0003             subscript
         BCTR  7,0                 subscript-1
         MH    7,H0001             times element size
         LA    7,D0002(7)          element address
         LH    2,0(,7)
         CVD   2,DWK               binary -> packed
         ZAP   PWK2(8),DWK(8)
         AP    PWK1(8),PWK2(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         ST    2,D0004
* ADD 1 -> WS-IDX
         LH    2,D0003
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         ZAP   PWK2(8),K0001(8)    literal
         AP    PWK1(8),PWK2(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         STH   2,D0003
         DROP  8
* SUM-EXIT.
P0004    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0004
         BR    15
F0004    DS    0H                  fall-through when not performed
* EOF-PARA.
P0005    DS    0H
* ADD 1 -> WS-CNT
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0005
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         ZAP   PWK2(8),K0001(8)    literal
         AP    PWK1(8),PWK2(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         STH   2,D0005
* IF
         LH    2,D0005
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0006(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BNH   L0001
* MOVE Y -> EOF-FLAG
         MVC   D0006(1),S0001      literal move, space padded
         DROP  8
L0001    DS    0H
* EOF-EXIT.
P0006    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0006
         BR    15
F0006    DS    0H                  fall-through when not performed
* BUMP-PARA.
P0007    DS    0H
* ADD 1 -> WS-CNT
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0005
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         ZAP   PWK2(8),K0001(8)    literal
         AP    PWK1(8),PWK2(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         STH   2,D0005
         DROP  8
* BUMP-EXIT.
P0008    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0008
         BR    15
F0008    DS    0H                  fall-through when not performed
PT014    DC    H'0'                PERFORM n TIMES counter
X0002    DC    A(F0002)            FILL-EXIT
X0004    DC    A(F0004)            SUM-EXIT
X0006    DC    A(F0006)            EOF-EXIT
X0008    DC    A(F0008)            BUMP-EXIT
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'7'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'7'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'7'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'7'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'7'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
K0001    DC    PL8'1'              numeric constants
K0002    DC    PL8'5'
K0003    DC    PL8'0'
K0004    DC    PL8'3'
K0005    DC    PL8'4'
K0006    DC    PL8'2'
H0001    DC    H'2'                element sizes
S0001    DC    CL1'Y'              nonnumeric constants
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
SAVEAREA DS    18F
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DS    0CL10               TBL (01 group)
D0001    DS    0CL2                ENT (05 group, OCCURS 5)
D0002    DC    HL2'0'              ENT-YEAR PIC S9(4)v0 COMP
         DS    XL14                reserve the rest of a table
D0003    DC    HL2'0'              WS-IDX PIC S9(4)v0 COMP
         DS    XL6                 reserve the rest of a table
D0004    DC    FL4'0'              WS-TOT PIC S9(7)v0 COMP
         DS    XL4                 reserve the rest of a table
D0005    DC    HL2'0'              WS-CNT PIC S9(4)v0 COMP
         DS    XL6                 reserve the rest of a table
D0006    DC    CL1'N'              EOF-FLAG PIC X(1)
         DS    XL7                 reserve the rest of a table
D0008    DC    CL7'0000000'        OUT-NUM PIC 9(7)v0 DISP
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
