*---------------------------------------------------------------
* Generated by cobc370 from tests/rpttest.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
RPTTEST  CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* MAIN-PARA.
P0000    DS    0H
* OPEN OUTPUT PRINT-FILE
         OPEN  (FD000,OUTPUT)
* INITIATE SIMPLE-RPT
         SR    2,2
         STH   2,RL000
         MVI   RCTL,C'1'           eject before the first page
* MOVE 0 -> WS-IDX
         ZAP   PWK1(8),K0001(8)    literal
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         L     8,BL0000            base locator
         USING WSC0000,8
         STH   2,D0003
         DROP  8
* LOOP-PARA.
P0001    DS    0H
* ADD 1 -> WS-IDX
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0003
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         ZAP   PWK2(8),K0002(8)    literal
         AP    PWK1(8),PWK2(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         STH   2,D0003
* IF
         LH    2,D0003
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0003(8)    literal
         CP    WK0(16),WK1(16)     numeric compare
         BNH   L0001
* GO TO DONE-PARA
         B     P0002
         DROP  8
L0001    DS    0H
* MOVE WS-IDX -> WS-NUM
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    2,D0003
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         ST    2,D0001
* COMPUTE WS-AMT = ...
         LH    2,D0003
         CVD   2,DWK               binary -> packed
         ZAP   WK0(16),DWK(8)
         ZAP   WK1(16),K0004(8)    literal
         ZAP   MULT8(8),WK1(16)    MP takes at most 8 bytes on the righ
         MP    WK0(16),MULT8(8)    scale becomes the sum of the scales
         SRP   WK0(16),2,0         align scale (left)
         ZAP   PWK1(8),WK0(16)
         ZAP   D0002(5),PWK1(8)
* GENERATE DETAIL-LINE
         DROP  8
         LH    2,RL000
         LA    2,1(2)              first line
         LH    3,RL000
         LTR   3,3                 no page yet?
         BZ    L0002
         CH    2,H0001             past LAST DETAIL?
         BNH   L0003
L0002    MVI   RCTL,C'1'           new page
         SR    2,2
         STH   2,RL000
         BAL   14,RG000            page heading
         LA    2,3                 details start at FIRST DETAIL
         STH   2,RL000
L0003    DS    0H
         BAL   14,RG001
* GO TO LOOP-PARA
         B     P0001
* DONE-PARA.
P0002    DS    0H
* TERMINATE SIMPLE-RPT (no report footing in this subset)
* CLOSE PRINT-FILE
         CLOSE (FD000)
* STOP RUN
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* report group PAGE-HEAD
RG000    ST    14,RGS              save the return, COBWRL clobbers R14
         LA    2,1                 LINE n
         STH   2,RTGT
         MVC   RBUF(1),RCTL        carriage control
         MVI   RCTL,C' '           one eject only
         MVI   RBUF+1,C' '
         MVC   RBUF+2(131),RBUF+1  blank the line
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0004(16),D0000     alphanumeric move
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   RBUF+1(16),D0004    COLUMN placement
         MVC   RBUF+25(11),S0001   COLUMN literal
         LA    1,RGP000
         L     15,VWRL
         BALR  14,15
         DROP  8
         LH    2,RL000
         LA    2,2(2)              LINE PLUS n
         STH   2,RTGT
         MVC   RBUF(1),RCTL        carriage control
         MVI   RCTL,C' '           one eject only
         MVI   RBUF+1,C' '
         MVC   RBUF+2(131),RBUF+1  blank the line
         MVC   RBUF+1(3),S0002     COLUMN literal
         MVC   RBUF+10(6),S0003    COLUMN literal
         LA    1,RGP000
         L     15,VWRL
         BALR  14,15
         L     14,RGS
         BR    14
* report group DETAIL-LINE
RG001    ST    14,RGS              save the return, COBWRL clobbers R14
         LH    2,RL000
         LA    2,1(2)              LINE PLUS n
         STH   2,RTGT
         MVC   RBUF(1),RCTL        carriage control
         MVI   RCTL,C' '           one eject only
         MVI   RBUF+1,C' '
         MVC   RBUF+2(131),RBUF+1  blank the line
         L     8,BL0000            base locator
         USING WSC0000,8
         L     2,D0001
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         UNPK  D0008(5),PWK1(8)    packed -> zoned
         OI    D0008+4,X'F0'       unsigned: force an F zone
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   RBUF+1(5),D0008     COLUMN placement
         ZAP   PWK1(8),D0002(5)
         ZAP   EDSRC(6),PWK1(8)    source, sized to the selector count
         MVC   EDWK(16),M0001      load the ED pattern
         LA    1,EDWK+3            default sign position
         EDMK  EDWK(16),EDSRC
         BCTR  1,0                 one left of the first significant di
         BNM   G0001               not negative?
         MVI   0(1),C'-'
G0001    DS    0H
         MVC   D0009(14),EDWK+2    the edited result
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   RBUF+10(14),D0009   COLUMN placement
         LA    1,RGP001
         L     15,VWRL
         BALR  14,15
         L     14,RGS
         BR    14
VWRL     DC    V(COBWRL)
RGP000   DC    A(FD000)            PAGE-HEAD
         DC    A(RL000)
         DC    A(RTGT)
         DC    X'80',AL3(RBUF)     last parameter
RGP001   DC    A(FD000)            DETAIL-LINE
         DC    A(RL000)
         DC    A(RTGT)
         DC    X'80',AL3(RBUF)     last parameter
RL000    DC    H'0'                SIMPLE-RPT
RP000    DC    H'0'
RTGT     DS    H                   target line
RGS      DS    F                   renderer return address
RCTL     DC    C' '                pending carriage control
RBUF     DC    CL133' '            ASA byte + 132 columns
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
* file control blocks
FD000    DCB   DDNAME=PROUT,DSORG=PS,MACRF=(PM),RECFM=FBA,             X
               LRECL=133,BLKSIZE=133
K0001    DC    PL8'0'              numeric constants
K0002    DC    PL8'1'
K0003    DC    PL8'10'
K0004    DC    PL8'1000'
M0001    DC    XL16'40204020206B2020206B2021204B2020'  ED patterns
H0001    DC    H'10'               element sizes
S0001    DC    CL11'TEST REPORT'   nonnumeric constants
S0002    DC    CL3'NUM'
S0003    DC    CL6'AMOUNT'
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
SAVEAREA DS    18F
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DC    CL16'ACME CORPORATION'  WS-NAME PIC X(16)
D0001    DC    F'0'                WS-NUM PIC S9(5)v0 COMP
D0002    DC    PL5'000'            WS-AMT PIC S9(9)v2 COMP-3
D0003    DC    H'0'                WS-IDX PIC S9(4)v0 COMP
D0004    DC    CL16' '             RPT0 PIC X(16)
D0005    DC    CL11' '             RPT1 PIC X(11)
D0006    DC    CL3' '              RPT2 PIC X(3)
D0007    DC    CL6' '              RPT3 PIC X(6)
D0008    DC    CL5'00000'          RPT4 PIC 9(5)v0 DISP
D0009    DC    CL14' '             RPT5 edited, 14 chars
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
