*---------------------------------------------------------------
* Generated by cobc370 from rrdsnatl.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
RRDSNATL CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
         SPIE  COBSPIE,((1,15))    report program checks by line
* 000-INITIATE.
P0000    DS    0H
T0000    DS    0H
* DISPLAY
         MVC   DSPBUF+0(33),S0001
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
T0001    DS    0H
* DISPLAY
         MVC   DSPBUF+0(33),S0002
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
T0002    DS    0H
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
T0003    DS    0H
* OPEN INPUT RECORD-IMAGES
         OPEN  (FD000,INPUT)
T0004    DS    0H
* OPEN OUTPUT RRDS-FILE
         OPEN  (FD001)             VSAM ACB
         LTR   15,15               VSAM request succeeded?
         BZ    G0001
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'30'     permanent error
         B     G0002
G0001    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'00'
G0002    DS    0H
         DROP  8
T0005    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0002(2),S0004      alphanumeric compare
         BE    L0001
T0006    DS    0H
* DISPLAY
         MVC   DSPBUF+0(31),S0005
         MVC   DSPBUF+31(2),D0002
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
T0007    DS    0H
* MOVE Y -> END-OF-FILE-SWITCH
         MVC   D0003(1),S0006      literal move, space padded
         DROP  8
L0001    DS    0H
* 010-PROCESS.
P0001    DS    0H
T0008    DS    0H
* PERFORM 110-PROCESS-DATA THRU 119-EXIT
L0009    DS    0H
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0003(1),S0006      alphanumeric compare
         BE    L0010
         LA    15,R0001            return here
         ST    15,X0004            into the range's exit cell
         B     P0003
R0001    DS    0H
         DROP  8
         LA    15,F0004            restore fall-through
         ST    15,X0004
         B     L0009
L0010    DS    0H
* 020-TERMINATE.
P0002    DS    0H
T0009    DS    0H
* CLOSE RECORD-IMAGES
         CLOSE (FD000)
T0010    DS    0H
* CLOSE RRDS-FILE
         CLOSE (FD001)
         LTR   15,15               VSAM request succeeded?
         BZ    G0003
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'30'     permanent error
         B     G0004
G0003    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'00'
G0004    DS    0H
         DROP  8
T0011    DS    0H
* MOVE RECORD-COUNTER -> COUNTER-EDIT
         L     8,BL0000            base locator
         USING WSC0000,8
         PACK  PWK1(16),D0007(8)   zoned -> packed
         ZAP   EDSRC(5),PWK1(16)   source, sized to the selector count
         MVC   EDWK(12),M0001      load the ED pattern
         ED    EDWK(12),EDSRC
         MVC   D0008(10),EDWK+2    the edited result
T0012    DS    0H
* DISPLAY
         MVC   DSPBUF+0(10),D0008
         MVC   DSPBUF+10(33),S0007
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
T0013    DS    0H
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
         DROP  8
* 110-PROCESS-DATA.
P0003    DS    0H
T0014    DS    0H
* READ RECORD-IMAGES
         LA    1,L0002             this READ's AT END
         STCM  1,7,FD000+33        into DCBEODAD
         L     8,BL0000            base locator
         USING WSC0000,8
         GET   FD000,D0000         QSAM move mode
         B     L0003
L0002    DS    0H                  AT END
         DROP  8
T0015    DS    0H
* MOVE Y -> END-OF-FILE-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0003(1),S0006      literal move, space padded
         DROP  8
L0003    DS    0H
T0016    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0003(1),S0006      alphanumeric compare
         BE    L0004
T0017    DS    0H
* PERFORM 120-ADD-RECORD THRU 129-EXIT
         LA    15,R0002            return here
         ST    15,X0006            into the range's exit cell
         B     P0005
R0002    DS    0H
         DROP  8
         LA    15,F0006            restore fall-through
         ST    15,X0006
L0004    DS    0H
* 119-EXIT.
P0004    DS    0H
T0018    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0004
         BR    15
F0004    DS    0H                  fall-through when not performed
* 120-ADD-RECORD.
P0005    DS    0H
T0019    DS    0H
* MOVE RECORD-IMAGE -> RRDS-RECORD
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(80),D0000     alphanumeric move
T0020    DS    0H
* MOVE N -> WRITE-FAILED-SWITCH
         MVC   D0005(1),S0008      literal move, space padded
T0021    DS    0H
* WRITE RRDS-RECORD
         PUT   RPL=FD001R          VSAM sequential store
         LTR   15,15               stored?
         BNZ   L0005
         LTR   15,15               VSAM request succeeded?
         BZ    G0005
         SHOWCB RPL=FD001R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'08'        duplicate key
         BE    G0007
         CLI   VSFB+3,X'0C'        key out of sequence
         BE    G0008
         CLI   VSFB+3,X'1C'        cluster is full
         BE    G0009
         MVC   D0002(2),=C'30'     permanent error
         B     G0006
G0007    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'22'     duplicate key
         B     G0006
G0008    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'21'     key out of sequence
         B     G0006
G0009    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'24'     cluster is full
         B     G0006
G0005    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'00'
G0006    DS    0H
         DROP  8
         B     L0006
L0005    DS    0H                  INVALID KEY
         LTR   15,15               VSAM request succeeded?
         BZ    G0010
         SHOWCB RPL=FD001R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'08'        duplicate key
         BE    G0012
         CLI   VSFB+3,X'0C'        key out of sequence
         BE    G0013
         CLI   VSFB+3,X'1C'        cluster is full
         BE    G0014
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'30'     permanent error
         B     G0011
G0012    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'22'     duplicate key
         B     G0011
G0013    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'21'     key out of sequence
         B     G0011
G0014    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'24'     cluster is full
         B     G0011
G0010    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(2),=C'00'
G0011    DS    0H
         DROP  8
T0022    DS    0H
* MOVE Y -> WRITE-FAILED-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0005(1),S0006      literal move, space padded
         DROP  8
L0006    DS    0H
T0023    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0005(1),S0006      alphanumeric compare
         BE    L0007
T0024    DS    0H
* ADD 1 -> RECORD-COUNTER
         PACK  PWK1(16),D0007(8)   zoned -> packed
         ZAP   PWK2(16),K0001(16)  literal
         AP    PWK1(16),PWK2(16)
         UNPK  D0007(8),PWK1(16)   packed -> zoned
         DROP  8
L0007    DS    0H
T0025    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0005(1),S0006      alphanumeric compare
         BNE   L0008
T0026    DS    0H
* DISPLAY
         MVC   DSPBUF+0(28),S0009
         MVC   DSPBUF+28(2),D0002
         LA    1,PARM0006
         L     15,VDISP
         BALR  14,15
T0027    DS    0H
* MOVE Y -> END-OF-FILE-SWITCH
         MVC   D0003(1),S0006      literal move, space padded
         DROP  8
L0008    DS    0H
* 129-EXIT.
P0006    DS    0H
T0028    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0006
         BR    15
F0006    DS    0H                  fall-through when not performed
X0004    DC    A(F0004)            119-EXIT
X0006    DC    A(F0006)            129-EXIT
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'33'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'33'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'1'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'33'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'43'
PARM0006 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0006)  last parameter
LEN0006  DC    H'30'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL16
PWK2     DS    PL16
EDSRC    DS    PL16                ED source, sized to the selectors
EDWK     DS    CL64                ED pattern and result
ZWK      DS    CL20                zoned, for a numeric to alphanumeric
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
* file control blocks
FD000    DCB   DDNAME=IMAGES,DSORG=PS,MACRF=(GM)
FD001    ACB   DDNAME=RRDSF01,MACRF=(KEY,SEQ,OUT,RST)  VSAM access meth
FD001R   RPL   ACB=FD001,AREA=D0001,                                   X
               AREALEN=80,RECLEN=80,ARG=FD001K,OPTCD=(KEY,SEQ,NUP,MVE)
FD001K   DS    F                   relative record number
K0001    DC    PL16'1'             numeric constants
M0001    DC    XL12'402020206B2020206B202120'  ED patterns
S0001    DC    CL33'RRDSLODS: WRITE RRDS SEQUENTIALLY'  nonnumeric cons
S0002    DC    CL33'---------------------------------'
S0003    DC    CL1' '
S0004    DC    CL2'00'
S0005    DC    CL31'VSAM ERROR DURING OPEN, STATUS '
S0006    DC    CL1'Y'
S0007    DC    CL33' RECORDS WERE LOADED SUCCESSFULLY'
S0008    DC    CL1'N'
S0009    DC    CL28'VSAM ERROR ON WRITE, STATUS '
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
VSFB     DS    F                   VSAM SHOWCB feedback word
SAVEAREA DS    18F
* program-check exit: report the source line, then let it abend
COBSPIE  DS    0H
         USING COBSPIE,15
         STM   14,12,SPIEREGS      R15 is our base on entry
         LR    9,15                keep a base across the WTO
         DROP  15
         USING COBSPIE,9
         LR    10,1                the PIE
*  the interruption code, as the digit people know it
         SR    7,7
         IC    7,7(,10)            low byte of the interruption code
         N     7,SPIE15
         LA    7,SPIEHEX(7)
         MVC   SPIECODE(1),0(7)
*  the interrupt address, as an offset into this module
         L     2,8(,10)            second word of the old PSW
         N     2,SPIEADR           leaves the instruction address
         S     2,SPIEBEG           relative to the entry point
*  the last table entry at or before it names the statement
         L     3,SPIETAB
         LH    4,SPIENUM
         SR    5,5                 no line yet
SPIELOOP LTR   4,4
         BZ    SPIEFND
         LH    6,0(,3)             this statement's offset
         CR    6,2
         BH    SPIEFND             past it: the previous one is the ans
         LH    5,2(,3)
         LA    3,4(,3)
         BCTR  4,0
         B     SPIELOOP
SPIEFND  CVD   5,SPIEDW
         UNPK  SPIELINE(5),SPIEDW+5(3)
         OI    SPIELINE+4,X'F0'
         WTO   MF=(E,SPIEWTO)      into the job log, beside the abend
*  cancel the exit and back up to the failing instruction,
*  so the abend happens for real -- same code, same dump
         SR    2,2
         IC    2,7(,10)            the interruption code
         A     2,SPIE3000
         ABEND (2),DUMP
SPIEHEX  DC    C'0123456789ABCDEF'
SPIE15   DC    F'15'
SPIE3000 DC    F'3000'
SPIEADR  DC    X'00FFFFFF'
SPIEBEG  DC    A(COBBEG)
SPIETAB  DC    A(SPIELTB)
SPIENUM  DC    H'29'               statements in the table
SPIEREGS DS    15F
SPIEDW   DS    D
SPIEWTO  WTO   'COBC370: PROGRAM CHECK 0C0 AT SOURCE LINE 00000',      X
               MF=L
SPIECODE EQU   SPIEWTO+29,1        the 0C? digit, patched above
SPIELINE EQU   SPIEWTO+46,5        the line number, likewise
* statement offsets, ascending, paired with source lines
SPIELTB  DS    0H
         DC    AL2(T0000-COBBEG),AL2(32)
         DC    AL2(T0001-COBBEG),AL2(33)
         DC    AL2(T0002-COBBEG),AL2(34)
         DC    AL2(T0003-COBBEG),AL2(35)
         DC    AL2(T0004-COBBEG),AL2(36)
         DC    AL2(T0005-COBBEG),AL2(38)
         DC    AL2(T0006-COBBEG),AL2(38)
         DC    AL2(T0007-COBBEG),AL2(39)
         DC    AL2(T0008-COBBEG),AL2(41)
         DC    AL2(T0009-COBBEG),AL2(43)
         DC    AL2(T0010-COBBEG),AL2(44)
         DC    AL2(T0011-COBBEG),AL2(45)
         DC    AL2(T0012-COBBEG),AL2(46)
         DC    AL2(T0013-COBBEG),AL2(47)
         DC    AL2(T0014-COBBEG),AL2(50)
         DC    AL2(T0015-COBBEG),AL2(50)
         DC    AL2(T0016-COBBEG),AL2(52)
         DC    AL2(T0017-COBBEG),AL2(52)
         DC    AL2(T0018-COBBEG),AL2(54)
         DC    AL2(T0019-COBBEG),AL2(56)
         DC    AL2(T0020-COBBEG),AL2(57)
         DC    AL2(T0021-COBBEG),AL2(59)
         DC    AL2(T0022-COBBEG),AL2(59)
         DC    AL2(T0023-COBBEG),AL2(61)
         DC    AL2(T0024-COBBEG),AL2(61)
         DC    AL2(T0025-COBBEG),AL2(63)
         DC    AL2(T0026-COBBEG),AL2(63)
         DC    AL2(T0027-COBBEG),AL2(64)
         DC    AL2(T0028-COBBEG),AL2(66)
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DC    CL80' '             RECORD-IMAGE PIC X(80)
D0001    DC    CL80' '             RRDS-RECORD PIC X(80)
D0002    DC    CL2'00'             WS-STATUS PIC X(2)
         DS    XL6                 reserve the rest of a table
D0003    DC    CL1'N'              END-OF-FILE-SWITCH PIC X(1)
         DS    XL7                 reserve the rest of a table
D0005    DC    CL1'N'              WRITE-FAILED-SWITCH PIC X(1)
         DS    XL7                 reserve the rest of a table
D0007    DC    ZL8'0'              RECORD-COUNTER PIC S9(8)v0 DISP
D0008    DC    CL10' '             COUNTER-EDIT edited, 10 chars
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL,COBDATE
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBDATE -- fill an 8-byte field with MM/DD/YY.
*   R1 -> the field.  TIME DEC hands back the date as packed
*   00YYDDDF, which is Julian, so the day of year has to be
*   walked into a month and a day.
*
COBDATE  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE4+4
         LA    11,RTSAVE4
         ST    11,8(13)
         LR    13,11
         LR    2,1                 the field, before TIME takes R1
         TIME  DEC                 R0 = HHMMSSth, R1 = 00YYDDDF
         ST    1,DTPACK
         UNPK  DTZONE(7),DTPACK(4)  '00YYDDD'
         OI    DTZONE+6,X'F0'
         PACK  DTDW(8),DTZONE+4(3)
         CVB   3,DTDW              day of the year
         PACK  DTDW(8),DTZONE+2(2)
         CVB   4,DTDW              the year
         N     4,DTF3              zero if a leap year -- 1901-2099, so
*                             mod 4 is the whole rule
         LA    5,1                 month
         LA    6,DTMON
DT010    SR    7,7
         IC    7,0(0,6)            days in this month
         CH    5,DTH2              February?
         BNE   DT020
         LTR   4,4
         BNZ   DT020
         LA    7,1(0,7)            29 this year
DT020    CR    3,7
         BNH   DT030               the day falls in this month
         SR    3,7
         LA    5,1(0,5)
         LA    6,1(0,6)
         B     DT010
DT030    CVD   5,DTDW
         UNPK  0(2,2),DTDW+6(2)    MM
         OI    1(2),X'F0'
         MVI   2(2),C'/'
         CVD   3,DTDW
         UNPK  3(2,2),DTDW+6(2)    DD
         OI    4(2),X'F0'
         MVI   5(2),C'/'
         MVC   6(2,2),DTZONE+2     YY, already zoned
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
DTMON    DC    AL1(31,28,31,30,31,30,31,31,30,31,30,31)
DTF3     DC    F'3'
DTH2     DC    H'2'
DTPACK   DS    F
DTZONE   DS    CL8
DTDW     DS    D
RTSAVE4  DS    18F
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
