*---------------------------------------------------------------
* Generated by cobc370 from /Users/sdennis/cobc370/tests/rrdsnatr.cb
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
RRDSNATR CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* 000-INITIATE.
P0000    DS    0H
* DISPLAY
         MVC   DSPBUF+0(32),S0001
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* DISPLAY
         MVC   DSPBUF+0(32),S0002
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
* DISPLAY
         MVC   DSPBUF+0(1),S0003
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
* OPEN INPUT RRDS-FILE
         OPEN  (FD000)             VSAM ACB
         LTR   15,15               VSAM request succeeded?
         BZ    G0001
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(2),=C'30'     permanent error
         B     G0002
G0001    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(2),=C'00'
G0002    DS    0H
         DROP  8
* 010-PROCESS.
P0001    DS    0H
* PERFORM 110-PROCESS-DATA THRU 119-EXIT
L0004    DS    0H
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0002(1),S0004      alphanumeric compare
         BE    L0005
         LA    15,R0001            return here
         ST    15,X0004            into the range's exit cell
         B     P0003
R0001    DS    0H
         DROP  8
         LA    15,F0004            restore fall-through
         ST    15,X0004
         B     L0004
L0005    DS    0H
* 020-TERMINATE.
P0002    DS    0H
* CLOSE RRDS-FILE
         CLOSE (FD000)
         LTR   15,15               VSAM request succeeded?
         BZ    G0003
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(2),=C'30'     permanent error
         B     G0004
G0003    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(2),=C'00'
G0004    DS    0H
         DROP  8
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* 110-PROCESS-DATA.
P0003    DS    0H
* READ RRDS-FILE
         GET   RPL=FD000R          VSAM sequential retrieval
         LTR   15,15               got a record?
         BNZ   L0001
         LTR   15,15               VSAM request succeeded?
         BZ    G0005
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        end of data
         BE    G0007
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(2),=C'30'     permanent error
         B     G0006
G0007    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(2),=C'10'     end of data
         B     G0006
G0005    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(2),=C'00'
G0006    DS    0H
         DROP  8
         B     L0002
L0001    DS    0H                  AT END
         LTR   15,15               VSAM request succeeded?
         BZ    G0008
         SHOWCB RPL=FD000R,FIELDS=FDBK,AREA=VSFB,LENGTH=4  why did it f
         CLI   VSFB+3,X'04'        end of data
         BE    G0010
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(2),=C'30'     permanent error
         B     G0009
G0010    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(2),=C'10'     end of data
         B     G0009
G0008    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0001(2),=C'00'
G0009    DS    0H
         DROP  8
* MOVE Y -> END-OF-FILE-SWITCH
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0002(1),S0004      literal move, space padded
         DROP  8
L0002    DS    0H
* IF
         L     8,BL0000            base locator
         USING WSC0000,8
         CLC   D0002(1),S0004      alphanumeric compare
         BE    L0003
* ADD 1 -> RECORD-COUNTER
         PACK  PWK1(8),D0004(8)    zoned -> packed
         ZAP   PWK2(8),K0001(8)    literal
         AP    PWK1(8),PWK2(8)
         UNPK  D0004(8),PWK1(8)    packed -> zoned
* MOVE RECORD-COUNTER -> COUNTER-EDIT
         PACK  PWK1(8),D0004(8)    zoned -> packed
         ZAP   EDSRC(5),PWK1(8)    source, sized to the selector count
         MVC   EDWK(12),M0001      load the ED pattern
         ED    EDWK(12),EDSRC
         MVC   D0005(10),EDWK+2    the edited result
* DISPLAY
         MVC   DSPBUF+0(10),D0005
         MVC   DSPBUF+10(2),S0005
         MVC   DSPBUF+12(80),D0000
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
         DROP  8
L0003    DS    0H
* 119-EXIT.
P0004    DS    0H
* EXIT
* end of a PERFORM range: return through its cell
         L     15,X0004
         BR    15
F0004    DS    0H                  fall-through when not performed
X0004    DC    A(F0004)            119-EXIT
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'32'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'32'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'1'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'92'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
* file control blocks
FD000    ACB   DDNAME=RRDSF01,MACRF=(KEY,SEQ,IN)  VSAM access method co
FD000R   RPL   ACB=FD000,AREA=D0000,                                   X
               AREALEN=80,RECLEN=80,ARG=FD000K,OPTCD=(KEY,SEQ,NUP,MVE)
FD000K   DS    F                   relative record number
K0001    DC    PL8'1'              numeric constants
M0001    DC    XL12'402020206B2020206B202120'  ED patterns
S0001    DC    CL32'RRDSREAD: READ RRDS SEQUENTIALLY'  nonnumeric const
S0002    DC    CL32'--------------------------------'
S0003    DC    CL1' '
S0004    DC    CL1'Y'
S0005    DC    CL2': '
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
VSFB     DS    F                   VSAM SHOWCB feedback word
SAVEAREA DS    18F
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DC    CL80' '             RRDS-RECORD PIC X(80)
D0001    DC    CL2'00'             WS-STATUS PIC X(2)
         DS    XL6                 reserve the rest of a table
D0002    DC    CL1'N'              END-OF-FILE-SWITCH PIC X(1)
         DS    XL7                 reserve the rest of a table
D0004    DC    ZL8'0'              RECORD-COUNTER PIC S9(8)v0 DISP
D0005    DC    CL10' '             COUNTER-EDIT edited, 10 chars
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
