*---------------------------------------------------------------
* Generated by cobc370 from signclau.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
SIGNCLAU CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
         SPIE  COBSPIE,((1,15))    report program checks by line
T0000    DS    0H
* MOVE -12345 -> DEF-T
         ZAP   PWK1(16),K0001(16)  literal
         L     8,BL0000            base locator
         USING WSC0000,8
         UNPK  D0000(5),PWK1(16)   packed -> zoned
T0001    DS    0H
* MOVE -12345 -> LEA-O
         ZAP   PWK1(16),K0001(16)  literal
         UNPK  ZWK(5),PWK1(16)     packed -> zoned
         MVZ   ZWK(1),ZWK+4        the sign moves to the leading digit
         OI    ZWK+4,X'F0'         the trailing digit is a digit again
         MVC   D0001(5),ZWK        the item, sign and all
T0002    DS    0H
* MOVE -12345 -> TRA-O
         ZAP   PWK1(16),K0001(16)  literal
         UNPK  D0002(5),PWK1(16)   packed -> zoned
T0003    DS    0H
* MOVE -12345 -> LEA-S
         ZAP   PWK1(16),K0001(16)  literal
         UNPK  ZWK+1(5),PWK1(16)   packed -> zoned
         OI    ZWK+5,X'F0'         no overpunch: the sign has its own p
         CP    PWK1(16),K0002(16)  negative?
         BM    L0001
         MVI   ZWK+0,C'+'
         B     L0002
L0001    DS    0H
         MVI   ZWK+0,C'-'
L0002    DS    0H
         MVC   D0004(6),ZWK        the item, sign and all
T0004    DS    0H
* MOVE -12345 -> TRA-S
         ZAP   PWK1(16),K0001(16)  literal
         UNPK  ZWK+0(5),PWK1(16)   packed -> zoned
         OI    ZWK+4,X'F0'         no overpunch: the sign has its own p
         CP    PWK1(16),K0002(16)  negative?
         BM    L0003
         MVI   ZWK+5,C'+'
         B     L0004
L0003    DS    0H
         MVI   ZWK+5,C'-'
L0004    DS    0H
         MVC   D0007(6),ZWK        the item, sign and all
T0005    DS    0H
* MOVE DEF-T -> SHOW-N
         PACK  PWK1(16),D0000(5)   zoned -> packed
         ZAP   EDSRC(4),PWK1(16)   source, sized to the selector count
         MVC   EDWK(9),M0001       load the ED pattern
         ED    EDWK(9),EDSRC
         BNM   G0001               not negative?
         MVI   EDWK+3,C'-'
G0001    DS    0H
         MVC   D0009(6),EDWK+3     the edited result
T0006    DS    0H
* DISPLAY
         MVC   DSPBUF+0(7),S0001
         MVC   DSPBUF+7(6),D0009
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
T0007    DS    0H
* MOVE LEA-O -> SHOW-N
         MVC   ZWK(5),D0001        the item, sign and all
         MVZ   ZWK+4(1),ZWK        the sign moves to where PACK looks f
         OI    ZWK,X'F0'           the leading digit is a digit again
         PACK  PWK1(16),ZWK(5)     zoned -> packed
         ZAP   EDSRC(4),PWK1(16)   source, sized to the selector count
         MVC   EDWK(9),M0001       load the ED pattern
         ED    EDWK(9),EDSRC
         BNM   G0003               not negative?
         MVI   EDWK+3,C'-'
G0003    DS    0H
         MVC   D0009(6),EDWK+3     the edited result
T0008    DS    0H
* DISPLAY
         MVC   DSPBUF+0(7),S0002
         MVC   DSPBUF+7(6),D0009
         LA    1,PARM0002
         L     15,VDISP
         BALR  14,15
T0009    DS    0H
* MOVE TRA-O -> SHOW-N
         PACK  PWK1(16),D0002(5)   zoned -> packed
         ZAP   EDSRC(4),PWK1(16)   source, sized to the selector count
         MVC   EDWK(9),M0001       load the ED pattern
         ED    EDWK(9),EDSRC
         BNM   G0005               not negative?
         MVI   EDWK+3,C'-'
G0005    DS    0H
         MVC   D0009(6),EDWK+3     the edited result
T0010    DS    0H
* DISPLAY
         MVC   DSPBUF+0(7),S0003
         MVC   DSPBUF+7(6),D0009
         LA    1,PARM0003
         L     15,VDISP
         BALR  14,15
T0011    DS    0H
* MOVE LEA-S -> SHOW-N
         MVC   ZWK(6),D0004        the item, sign and all
         PACK  PWK1(16),ZWK+1(5)   the digits, without the sign charact
         CLI   ZWK+0,C'-'          negative?
         BNE   L0005
         NI    PWK1+15,X'F0'       clear the sign nibble
         OI    PWK1+15,X'0D'       and make it negative
L0005    DS    0H
         ZAP   EDSRC(4),PWK1(16)   source, sized to the selector count
         MVC   EDWK(9),M0001       load the ED pattern
         ED    EDWK(9),EDSRC
         BNM   G0007               not negative?
         MVI   EDWK+3,C'-'
G0007    DS    0H
         MVC   D0009(6),EDWK+3     the edited result
T0012    DS    0H
* DISPLAY
         MVC   DSPBUF+0(7),S0004
         MVC   DSPBUF+7(6),D0009
         LA    1,PARM0004
         L     15,VDISP
         BALR  14,15
T0013    DS    0H
* MOVE TRA-S -> SHOW-N
         MVC   ZWK(6),D0007        the item, sign and all
         PACK  PWK1(16),ZWK+0(5)   the digits, without the sign charact
         CLI   ZWK+5,C'-'          negative?
         BNE   L0006
         NI    PWK1+15,X'F0'       clear the sign nibble
         OI    PWK1+15,X'0D'       and make it negative
L0006    DS    0H
         ZAP   EDSRC(4),PWK1(16)   source, sized to the selector count
         MVC   EDWK(9),M0001       load the ED pattern
         ED    EDWK(9),EDSRC
         BNM   G0009               not negative?
         MVI   EDWK+3,C'-'
G0009    DS    0H
         MVC   D0009(6),EDWK+3     the edited result
T0014    DS    0H
* DISPLAY
         MVC   DSPBUF+0(7),S0005
         MVC   DSPBUF+7(6),D0009
         LA    1,PARM0005
         L     15,VDISP
         BALR  14,15
T0015    DS    0H
* DISPLAY
         MVC   DSPBUF+0(11),S0006
         MVC   DSPBUF+11(6),D0005
         MVC   DSPBUF+17(1),S0007
         LA    1,PARM0006
         L     15,VDISP
         BALR  14,15
T0016    DS    0H
* DISPLAY
         MVC   DSPBUF+0(11),S0008
         MVC   DSPBUF+11(6),D0008
         MVC   DSPBUF+17(1),S0007
         LA    1,PARM0007
         L     15,VDISP
         BALR  14,15
T0017    DS    0H
* MOVE 67890 -> LEA-S
         ZAP   PWK1(16),K0003(16)  literal
         UNPK  ZWK+1(5),PWK1(16)   packed -> zoned
         OI    ZWK+5,X'F0'         no overpunch: the sign has its own p
         CP    PWK1(16),K0002(16)  negative?
         BM    L0007
         MVI   ZWK+0,C'+'
         B     L0008
L0007    DS    0H
         MVI   ZWK+0,C'-'
L0008    DS    0H
         MVC   D0004(6),ZWK        the item, sign and all
T0018    DS    0H
* MOVE 67890 -> TRA-S
         ZAP   PWK1(16),K0003(16)  literal
         UNPK  ZWK+0(5),PWK1(16)   packed -> zoned
         OI    ZWK+4,X'F0'         no overpunch: the sign has its own p
         CP    PWK1(16),K0002(16)  negative?
         BM    L0009
         MVI   ZWK+5,C'+'
         B     L0010
L0009    DS    0H
         MVI   ZWK+5,C'-'
L0010    DS    0H
         MVC   D0007(6),ZWK        the item, sign and all
T0019    DS    0H
* MOVE 67890 -> LEA-O
         ZAP   PWK1(16),K0003(16)  literal
         UNPK  ZWK(5),PWK1(16)     packed -> zoned
         MVZ   ZWK(1),ZWK+4        the sign moves to the leading digit
         OI    ZWK+4,X'F0'         the trailing digit is a digit again
         MVC   D0001(5),ZWK        the item, sign and all
T0020    DS    0H
* DISPLAY
         MVC   DSPBUF+0(11),S0009
         MVC   DSPBUF+11(6),D0005
         MVC   DSPBUF+17(1),S0007
         LA    1,PARM0008
         L     15,VDISP
         BALR  14,15
T0021    DS    0H
* DISPLAY
         MVC   DSPBUF+0(11),S0010
         MVC   DSPBUF+11(6),D0008
         MVC   DSPBUF+17(1),S0007
         LA    1,PARM0009
         L     15,VDISP
         BALR  14,15
T0022    DS    0H
* MOVE LEA-O -> SHOW-N
         MVC   ZWK(5),D0001        the item, sign and all
         MVZ   ZWK+4(1),ZWK        the sign moves to where PACK looks f
         OI    ZWK,X'F0'           the leading digit is a digit again
         PACK  PWK1(16),ZWK(5)     zoned -> packed
         ZAP   EDSRC(4),PWK1(16)   source, sized to the selector count
         MVC   EDWK(9),M0001       load the ED pattern
         ED    EDWK(9),EDSRC
         BNM   G0011               not negative?
         MVI   EDWK+3,C'-'
G0011    DS    0H
         MVC   D0009(6),EDWK+3     the edited result
T0023    DS    0H
* DISPLAY
         MVC   DSPBUF+0(10),S0011
         MVC   DSPBUF+10(6),D0009
         LA    1,PARM0010
         L     15,VDISP
         BALR  14,15
T0024    DS    0H
* ADD 1 -> LEA-O
         MVC   ZWK(5),D0001        the item, sign and all
         MVZ   ZWK+4(1),ZWK        the sign moves to where PACK looks f
         OI    ZWK,X'F0'           the leading digit is a digit again
         PACK  PWK1(16),ZWK(5)     zoned -> packed
         ZAP   PWK2(16),K0004(16)  literal
         AP    PWK1(16),PWK2(16)
         UNPK  ZWK(5),PWK1(16)     packed -> zoned
         MVZ   ZWK(1),ZWK+4        the sign moves to the leading digit
         OI    ZWK+4,X'F0'         the trailing digit is a digit again
         MVC   D0001(5),ZWK        the item, sign and all
T0025    DS    0H
* MOVE LEA-O -> SHOW-N
         MVC   ZWK(5),D0001        the item, sign and all
         MVZ   ZWK+4(1),ZWK        the sign moves to where PACK looks f
         OI    ZWK,X'F0'           the leading digit is a digit again
         PACK  PWK1(16),ZWK(5)     zoned -> packed
         ZAP   EDSRC(4),PWK1(16)   source, sized to the selector count
         MVC   EDWK(9),M0001       load the ED pattern
         ED    EDWK(9),EDSRC
         BNM   G0013               not negative?
         MVI   EDWK+3,C'-'
G0013    DS    0H
         MVC   D0009(6),EDWK+3     the edited result
T0026    DS    0H
* DISPLAY
         MVC   DSPBUF+0(10),S0012
         MVC   DSPBUF+10(6),D0009
         LA    1,PARM0011
         L     15,VDISP
         BALR  14,15
T0027    DS    0H
* SUBTRACT 2 -> TRA-S
         MVC   ZWK(6),D0007        the item, sign and all
         PACK  PWK1(16),ZWK+0(5)   the digits, without the sign charact
         CLI   ZWK+5,C'-'          negative?
         BNE   L0011
         NI    PWK1+15,X'F0'       clear the sign nibble
         OI    PWK1+15,X'0D'       and make it negative
L0011    DS    0H
         ZAP   PWK2(16),K0005(16)  literal
         SP    PWK1(16),PWK2(16)
         UNPK  ZWK+0(5),PWK1(16)   packed -> zoned
         OI    ZWK+4,X'F0'         no overpunch: the sign has its own p
         CP    PWK1(16),K0002(16)  negative?
         BM    L0012
         MVI   ZWK+5,C'+'
         B     L0013
L0012    DS    0H
         MVI   ZWK+5,C'-'
L0013    DS    0H
         MVC   D0007(6),ZWK        the item, sign and all
T0028    DS    0H
* DISPLAY
         MVC   DSPBUF+0(11),S0013
         MVC   DSPBUF+11(6),D0008
         MVC   DSPBUF+17(1),S0007
         LA    1,PARM0012
         L     15,VDISP
         BALR  14,15
T0029    DS    0H
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'13'
PARM0002 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0002)  last parameter
LEN0002  DC    H'13'
PARM0003 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0003)  last parameter
LEN0003  DC    H'13'
PARM0004 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0004)  last parameter
LEN0004  DC    H'13'
PARM0005 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0005)  last parameter
LEN0005  DC    H'13'
PARM0006 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0006)  last parameter
LEN0006  DC    H'18'
PARM0007 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0007)  last parameter
LEN0007  DC    H'18'
PARM0008 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0008)  last parameter
LEN0008  DC    H'18'
PARM0009 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0009)  last parameter
LEN0009  DC    H'18'
PARM0010 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0010)  last parameter
LEN0010  DC    H'16'
PARM0011 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0011)  last parameter
LEN0011  DC    H'16'
PARM0012 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0012)  last parameter
LEN0012  DC    H'18'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL16
PWK2     DS    PL16
EDSRC    DS    PL16                ED source, sized to the selectors
EDWK     DS    CL64                ED pattern and result
ZWK      DS    CL24                zoned work area
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
K0001    DC    PL16'-12345'        numeric constants
K0002    DC    PL16'0'
K0003    DC    PL16'67890'
K0004    DC    PL16'1'
K0005    DC    PL16'2'
M0001    DC    XL9'402021402020202020'  ED patterns
S0001    DC    CL7'DEF-T  '        nonnumeric constants
S0002    DC    CL7'LEA-O  '
S0003    DC    CL7'TRA-O  '
S0004    DC    CL7'LEA-S  '
S0005    DC    CL7'TRA-S  '
S0006    DC    CL11'LEA-S neg ['
S0007    DC    CL1']'
S0008    DC    CL11'TRA-S neg ['
S0009    DC    CL11'LEA-S pos ['
S0010    DC    CL11'TRA-S pos ['
S0011    DC    CL10'LEA-O pos '
S0012    DC    CL10'LEA-O +1  '
S0013    DC    CL11'TRA-S -2  ['
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
SAVEAREA DS    18F
* program-check exit: report the source line, then let it abend
COBSPIE  DS    0H
         USING COBSPIE,15
         STM   14,12,SPIEREGS      R15 is our base on entry
         LR    9,15                keep a base across the WTO
         DROP  15
         USING COBSPIE,9
         LR    10,1                the PIE
*  the interruption code, as the digit people know it
         SR    7,7
         IC    7,7(,10)            low byte of the interruption code
         N     7,SPIE15
         LA    7,SPIEHEX(7)
         MVC   SPIECODE(1),0(7)
*  the interrupt address, as an offset into this module
         L     2,8(,10)            second word of the old PSW
         N     2,SPIEADR           leaves the instruction address
         S     2,SPIEBEG           relative to the entry point
*  the last table entry at or before it names the statement
         L     3,SPIETAB
         LH    4,SPIENUM
         SR    5,5                 no line yet
SPIELOOP LTR   4,4
         BZ    SPIEFND
         LH    6,0(,3)             this statement's offset
         CR    6,2
         BH    SPIEFND             past it: the previous one is the ans
         LH    5,2(,3)
         LA    3,4(,3)
         BCTR  4,0
         B     SPIELOOP
SPIEFND  CVD   5,SPIEDW
         UNPK  SPIELINE(5),SPIEDW+5(3)
         OI    SPIELINE+4,X'F0'
         WTO   MF=(E,SPIEWTO)      into the job log, beside the abend
*  cancel the exit and back up to the failing instruction,
*  so the abend happens for real -- same code, same dump
         SR    2,2
         IC    2,7(,10)            the interruption code
         A     2,SPIE3000
         ABEND (2),DUMP
SPIEHEX  DC    C'0123456789ABCDEF'
SPIE15   DC    F'15'
SPIE3000 DC    F'3000'
SPIEADR  DC    X'00FFFFFF'
SPIEBEG  DC    A(COBBEG)
SPIETAB  DC    A(SPIELTB)
SPIENUM  DC    H'30'               statements in the table
SPIEREGS DS    15F
SPIEDW   DS    D
SPIEWTO  WTO   'COBC370: PROGRAM CHECK 0C0 AT SOURCE LINE 00000',      X
               MF=L
SPIECODE EQU   SPIEWTO+29,1        the 0C? digit, patched above
SPIELINE EQU   SPIEWTO+46,5        the line number, likewise
* statement offsets, ascending, paired with source lines
SPIELTB  DS    0H
         DC    AL2(T0000-COBBEG),AL2(26)
         DC    AL2(T0001-COBBEG),AL2(26)
         DC    AL2(T0002-COBBEG),AL2(26)
         DC    AL2(T0003-COBBEG),AL2(26)
         DC    AL2(T0004-COBBEG),AL2(26)
         DC    AL2(T0005-COBBEG),AL2(27)
         DC    AL2(T0006-COBBEG),AL2(28)
         DC    AL2(T0007-COBBEG),AL2(29)
         DC    AL2(T0008-COBBEG),AL2(30)
         DC    AL2(T0009-COBBEG),AL2(31)
         DC    AL2(T0010-COBBEG),AL2(32)
         DC    AL2(T0011-COBBEG),AL2(33)
         DC    AL2(T0012-COBBEG),AL2(34)
         DC    AL2(T0013-COBBEG),AL2(35)
         DC    AL2(T0014-COBBEG),AL2(36)
         DC    AL2(T0015-COBBEG),AL2(37)
         DC    AL2(T0016-COBBEG),AL2(38)
         DC    AL2(T0017-COBBEG),AL2(39)
         DC    AL2(T0018-COBBEG),AL2(39)
         DC    AL2(T0019-COBBEG),AL2(39)
         DC    AL2(T0020-COBBEG),AL2(40)
         DC    AL2(T0021-COBBEG),AL2(41)
         DC    AL2(T0022-COBBEG),AL2(42)
         DC    AL2(T0023-COBBEG),AL2(43)
         DC    AL2(T0024-COBBEG),AL2(44)
         DC    AL2(T0025-COBBEG),AL2(45)
         DC    AL2(T0026-COBBEG),AL2(46)
         DC    AL2(T0027-COBBEG),AL2(47)
         DC    AL2(T0028-COBBEG),AL2(48)
         DC    AL2(T0029-COBBEG),AL2(49)
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DC    ZL5'0'              DEF-T PIC S9(5)v0 DISP
         DS    XL3                 reserve the rest of a table
D0001    DC    ZL5'0'              LEA-O PIC S9(5)v0 DISP
         DS    XL3                 reserve the rest of a table
D0002    DC    ZL5'0'              TRA-O PIC S9(5)v0 DISP
         DS    XL3                 reserve the rest of a table
D0003    DS    0CL6                G-LEA-S (01 group)
D0004    DC    ZL6'0'              LEA-S PIC S9(5)v0 DISP
D0005    EQU   COBWS+24            X-LEA-S REDEFINES
         DS    XL2                 reserve the rest of a table
D0006    DS    0CL6                G-TRA-S (01 group)
D0007    DC    ZL6'0'              TRA-S PIC S9(5)v0 DISP
D0008    EQU   COBWS+32            X-TRA-S REDEFINES
         DS    XL2                 reserve the rest of a table
D0009    DC    CL6' '              SHOW-N edited, 6 chars
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL,COBDATE,COBACC
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBACC -- one transfer from SYSIN into the caller's item.
*
* General rule 2 on II-53 leaves the size of a transfer to the
* implementor: here it is one 80-column record. The buffer is
* blanked first, so a receiver wider than a card is padded and
* a read past the last card returns spaces rather than the
* card before it.
*
* Parameter list: A(item), A(halfword length).
COBACC   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE5+4
         LA    11,RTSAVE5
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(item)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         MVI   ACCBUF,C' '
         MVC   ACCBUF+1(255),ACCBUF  blank the buffer
         CLI   ACCEOFF,X'01'       already at end of file?
         BE    COBA020
         CLI   ACCOPEN,X'01'       already open?
         BE    COBA010
         OPEN  (ACCDCB,INPUT)
         MVI   ACCOPEN,X'01'
COBA010  LA    1,COBA030
         STCM  1,7,ACCDCB+33       into DCBEODAD
         GET   ACCDCB,ACCBUF       one card
         B     COBA020
COBA030  MVI   ACCEOFF,X'01'       end of file: the buffer stays blank
COBA020  LTR   4,4
         BNP   COBA040             nothing to store
         CH    4,ACCMAX
         BNH   COBA035
         LH    4,ACCMAX            one MVC is 256 bytes
COBA035  BCTR  4,0                 EX wants length-1
         EX    4,COBAMVC
COBA040  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBAMVC  MVC   0(0,2),ACCBUF       patched by EX
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   ACCOPEN,X'01'
         BNE   COBT005
         CLOSE (ACCDCB)
         MVI   ACCOPEN,X'00'
COBT005  CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBDATE -- fill an 8-byte field with MM/DD/YY.
*   R1 -> the field.  TIME DEC hands back the date as packed
*   00YYDDDF, which is Julian, so the day of year has to be
*   walked into a month and a day.
*
COBDATE  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE4+4
         LA    11,RTSAVE4
         ST    11,8(13)
         LR    13,11
         LR    2,1                 the field, before TIME takes R1
         TIME  DEC                 R0 = HHMMSSth, R1 = 00YYDDDF
         ST    1,DTPACK
         UNPK  DTZONE(7),DTPACK(4)  '00YYDDD'
         OI    DTZONE+6,X'F0'
         PACK  DTDW(8),DTZONE+4(3)
         CVB   3,DTDW              day of the year
         PACK  DTDW(8),DTZONE+2(2)
         CVB   4,DTDW              the year
         N     4,DTF3              zero if a leap year -- 1901-2099, so
*                             mod 4 is the whole rule
         LA    5,1                 month
         LA    6,DTMON
DT010    SR    7,7
         IC    7,0(0,6)            days in this month
         CH    5,DTH2              February?
         BNE   DT020
         LTR   4,4
         BNZ   DT020
         LA    7,1(0,7)            29 this year
DT020    CR    3,7
         BNH   DT030               the day falls in this month
         SR    3,7
         LA    5,1(0,5)
         LA    6,1(0,6)
         B     DT010
DT030    CVD   5,DTDW
         UNPK  0(2,2),DTDW+6(2)    MM
         OI    1(2),X'F0'
         MVI   2(2),C'/'
         CVD   3,DTDW
         UNPK  3(2,2),DTDW+6(2)    DD
         OI    4(2),X'F0'
         MVI   5(2),C'/'
         MVC   6(2,2),DTZONE+2     YY, already zoned
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
DTMON    DC    AL1(31,28,31,30,31,30,31,31,30,31,30,31)
DTF3     DC    F'3'
DTH2     DC    H'2'
DTPACK   DS    F
DTZONE   DS    CL8
DTDW     DS    D
RTSAVE4  DS    18F
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTSAVE5  DS    18F
ACCOPEN  DC    X'00'
ACCEOFF  DC    X'00'
ACCBUF   DC    CL256' '            one card from SYSIN, blank padded
ACCMAX   DC    H'256'
ACCDCB   DCB   DDNAME=SYSIN,DSORG=PS,MACRF=(GM),                       X
               EODAD=0
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
