*---------------------------------------------------------------
* Generated by cobc370 from tests/srchall.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
* DISPLAY and report output are served by our own COBRT runtime.
*---------------------------------------------------------------
SRCHALL  CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* MAIN-PARA.
P0000    DS    0H
* MOVE A -> WS-WANT
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0010(1),S0001      literal move, space padded
* PERFORM LOOKUP
         LA    15,R0001            return here
         ST    15,X0001            into the range's exit cell
         B     P0001
R0001    DS    0H
         DROP  8
         LA    15,F0001            restore fall-through
         ST    15,X0001
* MOVE E -> WS-WANT
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0010(1),S0002      literal move, space padded
* PERFORM LOOKUP
         LA    15,R0002            return here
         ST    15,X0001            into the range's exit cell
         B     P0001
R0002    DS    0H
         DROP  8
         LA    15,F0001            restore fall-through
         ST    15,X0001
* MOVE I -> WS-WANT
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0010(1),S0003      literal move, space padded
* PERFORM LOOKUP
         LA    15,R0003            return here
         ST    15,X0001            into the range's exit cell
         B     P0001
R0003    DS    0H
         DROP  8
         LA    15,F0001            restore fall-through
         ST    15,X0001
* MOVE L -> WS-WANT
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0010(1),S0004      literal move, space padded
* PERFORM LOOKUP
         LA    15,R0004            return here
         ST    15,X0001            into the range's exit cell
         B     P0001
R0004    DS    0H
         DROP  8
         LA    15,F0001            restore fall-through
         ST    15,X0001
* MOVE Q -> WS-WANT
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0010(1),S0005      literal move, space padded
* PERFORM LOOKUP
         LA    15,R0005            return here
         ST    15,X0001            into the range's exit cell
         B     P0001
R0005    DS    0H
         DROP  8
         LA    15,F0001            restore fall-through
         ST    15,X0001
* MOVE Z -> WS-WANT
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0010(1),S0006      literal move, space padded
* PERFORM LOOKUP
         LA    15,R0006            return here
         ST    15,X0001            into the range's exit cell
         B     P0001
R0006    DS    0H
         DROP  8
         LA    15,F0001            restore fall-through
         ST    15,X0001
* MOVE B -> WS-WANT
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0010(1),S0007      literal move, space padded
* PERFORM LOOKUP
         LA    15,R0007            return here
         ST    15,X0001            into the range's exit cell
         B     P0001
R0007    DS    0H
         DROP  8
         LA    15,F0001            restore fall-through
         ST    15,X0001
* STOP RUN
         L     15,VTERM            close anything the runtime opened
         BALR  14,15
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* LOOKUP.
P0001    DS    0H
* SEARCH ALL CLASS-ENTRY
         LA    1,1
         STH   1,SL017             low = 1
         LA    1,5
         STH   1,SH017             high = OCCURS
SP017    DS    0H
         LH    1,SL017
         LH    2,SH017
         CR    1,2                 low > high means it is not there
         BH    L0001
         AR    1,2
         SRA   1,1                 mid = (low + high) / 2
         L     8,BL0000            base locator
         USING WSC0000,8
         STH   1,D0012             the index is the occurrence number
         LH    6,D0012             subscript
         BCTR  6,0                 subscript-1
         MH    6,H0001             times element size
         LA    6,D0008(6)          element address
         CLC   0(1,6),D0010        alphanumeric compare
         BE    L0002
         LH    6,D0012             subscript
         BCTR  6,0                 subscript-1
         MH    6,H0001             times element size
         LA    6,D0008(6)          element address
         CLC   0(1,6),D0010        alphanumeric compare
         BL    L0004
         LH    1,D0012
         BCTR  1,0
         STH   1,SH017             high = mid - 1
         B     SP017
L0004    DS    0H
         DROP  8
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    1,D0012
         LA    1,1(1)
         STH   1,SL017             low = mid + 1
         B     SP017
         DROP  8
L0001    DS    0H
* MOVE *NOT FOUND*   -> WS-NAME
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   D0011(13),S0008     literal move, space padded
         B     L0003
         DROP  8
L0002    DS    0H
* MOVE CLASS-NAME -> WS-NAME
         L     8,BL0000            base locator
         USING WSC0000,8
         LH    7,D0012             subscript
         BCTR  7,0                 subscript-1
         MH    7,H0001             times element size
         LA    7,D0009(7)          element address
         MVC   D0011(13),0(7)      alphanumeric move
         DROP  8
L0003    DS    0H
* DISPLAY
         L     8,BL0000            base locator
         USING WSC0000,8
         MVC   DSPBUF+0(1),D0010
         MVC   DSPBUF+1(5),S0009
         MVC   DSPBUF+6(13),D0011
         MVC   DSPBUF+19(1),S0010
         LA    1,PARM0001
         L     15,VDISP
         BALR  14,15
* end of a PERFORM range: return through its cell
         L     15,X0001
         BR    15
F0001    DS    0H                  fall-through when not performed
SL017    DC    H'0'                SEARCH ALL low bound
SH017    DC    H'0'                high bound
X0001    DC    A(F0001)            LOOKUP
VDISP    DC    V(COBDISP)
VTERM    DC    V(COBTERM)
PARM0001 DC    A(DSPBUF)
         DC    X'80',AL3(LEN0001)  last parameter
LEN0001  DC    H'20'
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
H0001    DC    H'14'               element sizes
S0001    DC    CL1'A'              nonnumeric constants
S0002    DC    CL1'E'
S0003    DC    CL1'I'
S0004    DC    CL1'L'
S0005    DC    CL1'Q'
S0006    DC    CL1'Z'
S0007    DC    CL1'B'
S0008    DC    CL13'*NOT FOUND*  '
S0009    DC    CL5' -> ['
S0010    DC    CL1']'
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
DSPBUF   DS    CL121               DISPLAY line
SAVEAREA DS    18F
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DS    0CL70               CLASS-INIT (01 group)
D0001    DC    CL14'AAssets       '  FILL0001 PIC X(14)
D0002    DC    CL14'EExpenses     '  FILL0002 PIC X(14)
D0003    DC    CL14'IIncome       '  FILL0003 PIC X(14)
D0004    DC    CL14'LLiabilities  '  FILL0004 PIC X(14)
D0005    DC    CL14'QEquity       '  FILL0005 PIC X(14)
D0006    EQU   COBWS+0             CLASS-TABLE REDEFINES
D0007    EQU   COBWS+0             CLASS-ENTRY REDEFINES
D0008    EQU   COBWS+0             CLASS-LETTER REDEFINES
D0009    EQU   COBWS+1             CLASS-NAME REDEFINES
         DS    XL2                 reserve the rest of a table
D0010    DC    CL1' '              WS-WANT PIC X(1)
         DS    XL7                 reserve the rest of a table
D0011    DC    CL13' '             WS-NAME PIC X(13)
         DS    XL3                 reserve the rest of a table
D0012    DC    HL2'0'              CL PIC S9(4)v0 COMP
*---------------------------------------------------------------
* COBRT -- our runtime. Nothing here is from SYS1.COBLIB.
* DISPLAY reaches SYSOUT through QSAM directly, which is the
* same access-method path IKFCBL00 uses for its own file I/O.
* Not reentrant: MVS 3.8j batch does not require it.
*---------------------------------------------------------------
COBRT    CSECT
         ENTRY COBDISP,COBTERM,COBWRL
*
* COBDISP -- write one line to SYSOUT.
*   R1 -> A(text), A(halfword length).  Opens SYSOUT on demand.
*
COBDISP  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE1+4
         LA    11,RTSAVE1
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(text)
         L     3,4(0,1)            A(length)
         LH    4,0(0,3)            length
         CLI   RTOPEN,X'01'        already open?
         BE    COBD010
         OPEN  (RTDCB,OUTPUT)
         MVI   RTOPEN,X'01'
COBD010  MVI   RTLINE,C' '         ASA: single space
         MVC   RTLINE+1(120),RTLINE  blank the text area
         LTR   4,4
         BNP   COBD020             empty: emit a blank line
         CH    4,RTMAX
         BNH   COBD015
         LH    4,RTMAX             truncate at line width
COBD015  BCTR  4,0                 EX wants length-1
         EX    4,COBDMVC
COBD020  PUT   RTDCB,RTLINE
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
COBDMVC  MVC   RTLINE+1(0),0(2)    executed, never fallen into
*
* COBTERM -- close SYSOUT if COBDISP ever opened it.
*
COBTERM  STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE2+4
         LA    11,RTSAVE2
         ST    11,8(13)
         LR    13,11
         CLI   RTOPEN,X'01'
         BNE   COBT010
         CLOSE (RTDCB)
         MVI   RTOPEN,X'00'
COBT010  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
* COBWRL -- advance the paper and write one report line.
*   R1 -> A(dcb), A(current line), A(target line), A(buffer)
*
COBWRL   STM   14,12,12(13)
         BALR  12,0
         USING *,12
         ST    13,RTSAVE3+4
         LA    11,RTSAVE3
         ST    11,8(13)
         LR    13,11
         L     2,0(0,1)            A(dcb)
         L     3,4(0,1)            A(current line)
         L     4,8(0,1)            A(target line)
         L     5,12(0,1)           A(buffer)
         LH    6,0(0,3)
         LH    7,0(0,4)
COBW010  LA    8,1(0,6)
         CR    8,7                 already at the line before the targe
         BNL   COBW020
         PUT   (2),RTBLNK          skip a line
         LA    6,1(0,6)
         B     COBW010
COBW020  PUT   (2),(5)
         STH   7,0(0,3)            current line = target
         L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
RTBLNK   DC    CL133' '            a blank line, ASA single space
RTSAVE3  DS    18F
RTOPEN   DC    X'00'
RTMAX    DC    H'120'
RTLINE   DC    CL121' '            ASA byte + 120 columns
RTSAVE1  DS    18F
RTSAVE2  DS    18F
RTDCB    DCB   DDNAME=SYSOUT,DSORG=PS,MACRF=(PM),RECFM=FBA,            X
               LRECL=121,BLKSIZE=121
         END
