*---------------------------------------------------------------
* Generated by cobc370 from tests/stoprun.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
*---------------------------------------------------------------
STOPRUN  CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                establish addressability
         USING *,12
         ST    13,SAVEAREA+4       backward chain to caller
         LA    11,SAVEAREA
         ST    11,8(13)            forward chain from caller
         LR    13,11               our save area is now current
* STOP RUN
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
SAVEAREA DS    18F
         END
