*---------------------------------------------------------------
* Generated by cobc370 from sub12.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
*---------------------------------------------------------------
SUB12    CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
B0000    EQU   COBBEG              the first code block
         USING COBBEG,12
         B     PRO001
PROCON   DC    A(COBCON)
PRO001   L     11,PROCON           the constants region
         LA    10,2048(,11)        and its second 4K
         LA    10,2048(,10)
         USING COBCON,11
         USING COBCON+4096,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* PROCEDURE DIVISION USING: the caller's parameter list
         L     0,0(0,1)
         ST    0,PBL0000           P1
         L     0,4(0,1)
         ST    0,PBL0001           P2
         L     0,8(0,1)
         ST    0,PBL0002           P3
         L     0,12(0,1)
         ST    0,PBL0003           P4
         L     0,16(0,1)
         ST    0,PBL0004           P5
         L     0,20(0,1)
         ST    0,PBL0005           P6
         L     0,24(0,1)
         ST    0,PBL0006           P7
         L     0,28(0,1)
         ST    0,PBL0007           P8
         L     0,32(0,1)
         ST    0,PBL0008           P9
         L     0,36(0,1)
         ST    0,PBL0009           P10
         L     0,40(0,1)
         ST    0,PBL0010           P11
         L     0,44(0,1)
         ST    0,PBL0011           P12
         SR    0,0
         SPM   0                   no overflow interrupts: high-order t
         CLI   SPIEDONE,X'01'      already armed?
         BE    SPIEARMD            the macro is several instructions: a
         SPIE  COBSPIE,((1,7),9,(11,12),15)  report program checks by l
         MVI   SPIEDONE,X'01'
SPIEARMD DS    0H
* MAIN-PARA.
P0000    DS    0H
         BALR  12,0                this paragraph's code base
B0001    EQU   *
         USING B0001,12
T0000    DS    0H
* COMPUTE P12 = ...
         L     8,PBL0000           parameter address
         USING LS0000,8
         PACK  WK0+9(7),D0000(2)   zoned -> packed
         L     9,PBL0001           parameter address
         USING LS0001,9
         PACK  WK1+14(2),D0001(2)  zoned -> packed
         AP    WK0+9(7),WK1+14(2)
         DROP  8
         L     8,PBL0002           parameter address
         USING LS0002,8
         PACK  WK1+14(2),D0002(2)  zoned -> packed
         AP    WK0+9(7),WK1+14(2)
         DROP  9
         L     9,PBL0003           parameter address
         USING LS0003,9
         PACK  WK1+14(2),D0003(2)  zoned -> packed
         AP    WK0+9(7),WK1+14(2)
         DROP  8
         L     8,PBL0004           parameter address
         USING LS0004,8
         PACK  WK1+14(2),D0004(2)  zoned -> packed
         AP    WK0+9(7),WK1+14(2)
         DROP  9
         L     9,PBL0005           parameter address
         USING LS0005,9
         PACK  WK1+14(2),D0005(2)  zoned -> packed
         AP    WK0+9(7),WK1+14(2)
         DROP  8
         L     8,PBL0006           parameter address
         USING LS0006,8
         PACK  WK1+14(2),D0006(2)  zoned -> packed
         AP    WK0+9(7),WK1+14(2)
         DROP  9
         L     9,PBL0007           parameter address
         USING LS0007,9
         PACK  WK1+14(2),D0007(2)  zoned -> packed
         AP    WK0+9(7),WK1+14(2)
         DROP  8
         L     8,PBL0008           parameter address
         USING LS0008,8
         PACK  WK1+14(2),D0008(2)  zoned -> packed
         AP    WK0+9(7),WK1+14(2)
         DROP  9
         L     9,PBL0009           parameter address
         USING LS0009,9
         PACK  WK1+14(2),D0009(2)  zoned -> packed
         AP    WK0+9(7),WK1+14(2)
         DROP  8
         L     8,PBL0010           parameter address
         USING LS0010,8
         PACK  WK1+14(2),D0010(2)  zoned -> packed
         AP    WK0+9(7),WK1+14(2)
         DROP  9
         L     9,PBL0011           parameter address
         USING LS0011,9
         UNPK  D0011(2),WK0+9(7)   packed -> zoned
         OI    D0011+1,X'F0'       unsigned: force an F zone
T0001    DS    0H
* GOBACK to the caller
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* end of the Procedure Division: an implicit STOP RUN
* GOBACK to the caller
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
         DROP  12
COBCON   DS    0D                  constants, work areas, out-of-line c
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL16
PWK2     DS    PL16
EDSRC    DS    PL16                ED source, sized to the selectors
EDWK     DS    CL64                ED pattern and result
ZWK      DS    CL24                zoned work area
MULT8    DS    PL8                 ** multiplier
QTMP     DS    PL16                DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
* one cell per LINKAGE 01, filled in from the parameter list
PBL0000  DC    A(0)                P1
PBL0001  DC    A(0)                P2
PBL0002  DC    A(0)                P3
PBL0003  DC    A(0)                P4
PBL0004  DC    A(0)                P5
PBL0005  DC    A(0)                P6
PBL0006  DC    A(0)                P7
PBL0007  DC    A(0)                P8
PBL0008  DC    A(0)                P9
PBL0009  DC    A(0)                P10
PBL0010  DC    A(0)                P11
PBL0011  DC    A(0)                P12
SAVEAREA DS    18F
* program-check exit: report the source line, then let it abend
COBSPIE  DS    0H
         USING COBSPIE,15
         STM   14,12,SPIEREGS      R15 is our base on entry
         LR    9,15                keep a base across the WTO
         DROP  15
         USING COBSPIE,9
         LR    10,1                the PIE
*  the interruption code, as the digit people know it
         SR    7,7
         IC    7,7(,10)            low byte of the interruption code
         N     7,SPIE15
         LA    7,SPIEHEX(7)
         MVC   SPIECODE(1),0(7)
*  the interrupt address, as an offset into this module
         L     2,8(,10)            second word of the old PSW
         N     2,SPIEADR           leaves the instruction address
         S     2,SPIEBEG           relative to the entry point
*  the last table entry at or before it names the statement
         L     3,SPIETAB
         LH    4,SPIENUM
         SR    5,5                 no line yet
SPIELOOP LTR   4,4
         BZ    SPIEFND
         L     6,0(,3)             this statement's offset
         CR    6,2
         BH    SPIEFND             past it: the previous one is the ans
         LH    5,4(,3)
         LA    3,8(,3)
         BCTR  4,0
         B     SPIELOOP
SPIEFND  CVD   5,SPIEDW
         UNPK  SPIELINE(5),SPIEDW+5(3)
         OI    SPIELINE+4,X'F0'
         ST    2,SPIEDW            the offset, relative to COBBEG
         UNPK  SPIEOFF(7),SPIEDW+1(4)  low three bytes to zoned
         TR    SPIEOFF(6),SPIEHEXT  zoned to hex digits
         WTO   MF=(E,SPIEWTO)      into the job log, beside the abend
*  cancel the exit and back up to the failing instruction,
*  so the abend happens for real -- same code, same dump
         SR    2,2
         IC    2,7(,10)            the interruption code
         A     2,SPIE3000
         ABEND (2),DUMP
SPIEHEX  DC    C'0123456789ABCDEF'
SPIEHEXT DC    240X'00',C'0123456789ABCDEF'
SPIE15   DC    F'15'
SPIE3000 DC    F'3000'
SPIEADR  DC    X'00FFFFFF'
SPIEBEG  DC    A(COBBEG)
SPIETAB  DC    A(SPIELTB)
SPIENUM  DC    H'2'                statements in the table
SPIEREGS DS    15F
SPIEDONE DC    X'00'               1 once this module's SPIE is armed
SPIEDW   DS    D
SPIEWTO  WTO   'COBC370: PROGRAM CHECK 0C0 LINE 00000 OFFSET 000000',  X
               MF=L
SPIECODE EQU   SPIEWTO+29,1        the 0C? digit, patched above
SPIELINE EQU   SPIEWTO+36,5        the line number, likewise
SPIEOFF  EQU   SPIEWTO+49,7        the offset from COBBEG, in hex
         DS    0F
CB0000   DC    A(B0000)            a code block's base
CB0001   DC    A(B0001)            a code block's base
         LTORG
* statement offsets, ascending, paired with source lines
SPIELTB  DS    0F
         DC    A(T0000-COBBEG),AL2(21,0)
         DC    A(T0001-COBBEG),AL2(23,0)
         CSECT                     WORKING-STORAGE: private code, one p
COBWS    DS    0D
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
         DS    XL2                 reserve the rest of the last table
LS0000   DSECT                     P1 (caller's storage)
D0000    DS    CL2                 P1
LS0001   DSECT                     P2 (caller's storage)
D0001    DS    CL2                 P2
LS0002   DSECT                     P3 (caller's storage)
D0002    DS    CL2                 P3
LS0003   DSECT                     P4 (caller's storage)
D0003    DS    CL2                 P4
LS0004   DSECT                     P5 (caller's storage)
D0004    DS    CL2                 P5
LS0005   DSECT                     P6 (caller's storage)
D0005    DS    CL2                 P6
LS0006   DSECT                     P7 (caller's storage)
D0006    DS    CL2                 P7
LS0007   DSECT                     P8 (caller's storage)
D0007    DS    CL2                 P8
LS0008   DSECT                     P9 (caller's storage)
D0008    DS    CL2                 P9
LS0009   DSECT                     P10 (caller's storage)
D0009    DS    CL2                 P10
LS0010   DSECT                     P11 (caller's storage)
D0010    DS    CL2                 P11
LS0011   DSECT                     P12 (caller's storage)
D0011    DS    CL2                 P12
         END
