*---------------------------------------------------------------
* Generated by cobc370 from subadd.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
*---------------------------------------------------------------
SUBADD   CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* PROCEDURE DIVISION USING: the caller's parameter list
         L     0,0(0,1)
         ST    0,PBL0000           LS-IN
         L     0,4(0,1)
         ST    0,PBL0001           LS-OUT
         SPIE  COBSPIE,((1,15))    report program checks by line
* MAIN-PARA.
P0000    DS    0H
T0000    DS    0H
* MOVE IN-VAL -> WS-T
         L     8,PBL0000           parameter address
         USING LS0000,8
         L     2,D0002
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(16),DWK(8)
         ZAP   DWK(8),PWK1(16)
         CVB   2,DWK               packed -> binary
         L     9,BL0000            base locator
         USING WSC0000,9
         ST    2,D0000
T0001    DS    0H
* ADD 1000 -> WS-T
         L     2,D0000
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(16),DWK(8)
         ZAP   PWK2(16),K0001(16)  literal
         AP    PWK1(16),PWK2(16)
         ZAP   DWK(8),PWK1(16)
         CVB   2,DWK               packed -> binary
         ST    2,D0000
T0002    DS    0H
* MOVE WS-T -> OUT-VAL
         L     2,D0000
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(16),DWK(8)
         ZAP   DWK(8),PWK1(16)
         CVB   2,DWK               packed -> binary
         DROP  8
         L     8,PBL0001           parameter address
         USING LS0001,8
         ST    2,D0004
T0003    DS    0H
* MOVE DONE -> OUT-TAG
         MVC   D0005(4),S0001      literal move, space padded
T0004    DS    0H
* GOBACK to the caller
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL16
PWK2     DS    PL16
EDSRC    DS    PL16                ED source, sized to the selectors
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
K0001    DC    PL16'1000'          numeric constants
S0001    DC    CL4'DONE'           nonnumeric constants
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
* one cell per LINKAGE 01, filled in from the parameter list
PBL0000  DC    A(0)                LS-IN
PBL0001  DC    A(0)                LS-OUT
SAVEAREA DS    18F
* program-check exit: report the source line, then let it abend
COBSPIE  DS    0H
         USING COBSPIE,15
         STM   14,12,SPIEREGS      R15 is our base on entry
         LR    9,15                keep a base across the WTO
         DROP  15
         USING COBSPIE,9
         LR    10,1                the PIE
*  the interruption code, as the digit people know it
         SR    7,7
         IC    7,7(,10)            low byte of the interruption code
         N     7,SPIE15
         LA    7,SPIEHEX(7)
         MVC   SPIECODE(1),0(7)
*  the interrupt address, as an offset into this module
         L     2,8(,10)            second word of the old PSW
         N     2,SPIEADR           leaves the instruction address
         S     2,SPIEBEG           relative to the entry point
*  the last table entry at or before it names the statement
         L     3,SPIETAB
         LH    4,SPIENUM
         SR    5,5                 no line yet
SPIELOOP LTR   4,4
         BZ    SPIEFND
         LH    6,0(,3)             this statement's offset
         CR    6,2
         BH    SPIEFND             past it: the previous one is the ans
         LH    5,2(,3)
         LA    3,4(,3)
         BCTR  4,0
         B     SPIELOOP
SPIEFND  CVD   5,SPIEDW
         UNPK  SPIELINE(5),SPIEDW+5(3)
         OI    SPIELINE+4,X'F0'
         WTO   MF=(E,SPIEWTO)      into the job log, beside the abend
*  cancel the exit and back up to the failing instruction,
*  so the abend happens for real -- same code, same dump
         SR    2,2
         IC    2,7(,10)            the interruption code
         A     2,SPIE3000
         ABEND (2),DUMP
SPIEHEX  DC    C'0123456789ABCDEF'
SPIE15   DC    F'15'
SPIE3000 DC    F'3000'
SPIEADR  DC    X'00FFFFFF'
SPIEBEG  DC    A(COBBEG)
SPIETAB  DC    A(SPIELTB)
SPIENUM  DC    H'5'                statements in the table
SPIEREGS DS    15F
SPIEDW   DS    D
SPIEWTO  WTO   'COBC370: PROGRAM CHECK 0C0 AT SOURCE LINE 00000',      X
               MF=L
SPIECODE EQU   SPIEWTO+29,1        the 0C? digit, patched above
SPIELINE EQU   SPIEWTO+46,5        the line number, likewise
* statement offsets, ascending, paired with source lines
SPIELTB  DS    0H
         DC    AL2(T0000-COBBEG),AL2(15)
         DC    AL2(T0001-COBBEG),AL2(16)
         DC    AL2(T0002-COBBEG),AL2(17)
         DC    AL2(T0003-COBBEG),AL2(18)
         DC    AL2(T0004-COBBEG),AL2(19)
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DC    FL4'0'              WS-T PIC S9(8)v0 COMP
         DS    XL4                 reserve the rest of the last table
LS0000   DSECT                     LS-IN (caller's storage)
D0001    DS    0CL4                LS-IN (01 group)
D0002    DS    CL4                 IN-VAL
LS0001   DSECT                     LS-OUT (caller's storage)
D0003    DS    0CL8                LS-OUT (01 group)
D0004    DS    CL4                 OUT-VAL
D0005    DS    CL4                 OUT-TAG
         END
