*---------------------------------------------------------------
* Generated by cobc370 from /Users/sdennis/cobc370/tests/subadd.cbl
* Standard OS/360 entry linkage. SYS1.COBLIB is never referenced.
*---------------------------------------------------------------
SUBADD   CSECT
         STM   14,12,12(13)        save caller's registers
         BALR  12,0                first code base
COBBEG   EQU   *
         USING COBBEG,12
         LA    11,2048(,12)        second code base
         LA    11,2048(,11)
         USING COBBEG+4096,11
         LA    10,2048(,11)        third code base
         LA    10,2048(,10)
         USING COBBEG+8192,10
         ST    13,SAVEAREA+4       backward chain to caller
         LA    0,SAVEAREA
         ST    0,8(13)             forward chain from caller
         LR    13,0                our save area is now current
* PROCEDURE DIVISION USING: the caller's parameter list
         L     0,0(0,1)
         ST    0,PBL0000           LS-IN
         L     0,4(0,1)
         ST    0,PBL0001           LS-OUT
* MAIN-PARA.
P0000    DS    0H
* MOVE IN-VAL -> WS-T
         L     8,PBL0000           parameter address
         USING LS0000,8
         L     2,D0002
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         L     9,BL0000            base locator
         USING WSC0000,9
         ST    2,D0000
* ADD 1000 -> WS-T
         L     2,D0000
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         ZAP   PWK2(8),K0001(8)    literal
         AP    PWK1(8),PWK2(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         ST    2,D0000
* MOVE WS-T -> OUT-VAL
         L     2,D0000
         CVD   2,DWK               binary -> packed
         ZAP   PWK1(8),DWK(8)
         ZAP   DWK(8),PWK1(8)
         CVB   2,DWK               packed -> binary
         DROP  8
         L     8,PBL0001           parameter address
         USING LS0001,8
         ST    2,D0004
* MOVE DONE -> OUT-TAG
         MVC   D0005(4),S0001      literal move, space padded
* GOBACK to the caller
         L     13,4(13)            restore caller's save area
         LM    14,12,12(13)        restore caller's registers
         SR    15,15               return code 0
         BR    14                  return to caller
* work areas for decimal arithmetic
DWK      DS    D                   CVD/CVB doubleword
PWK1     DS    PL8
PWK2     DS    PL8
EDSRC    DS    PL8                 ED source, exactly sized
EDWK     DS    CL64                ED pattern and result
MULT8    DS    PL8                 MP right operand
DIVR8    DS    PL8                 DP divisor
QTMP     DS    PL8                 DP quotient
WK0      DS    PL16                expression stack
WK1      DS    PL16
WK2      DS    PL16
WK3      DS    PL16
WK4      DS    PL16
WK5      DS    PL16
K0001    DC    PL8'1000'           numeric constants
S0001    DC    CL4'DONE'           nonnumeric constants
* base locator cells, one per 4096 bytes of COBWS
BL0000   DC    A(WSC0000)
* one cell per LINKAGE 01, filled in from the parameter list
PBL0000  DC    A(0)                LS-IN
PBL0001  DC    A(0)                LS-OUT
SAVEAREA DS    18F
COBWS    CSECT
WSC0000  EQU   COBWS               chunk origins
* WORKING-STORAGE
D0000    DC    FL4'0'              WS-T PIC S9(8)v0 COMP
         DS    XL4                 reserve the rest of the last table
LS0000   DSECT                     LS-IN (caller's storage)
D0001    DS    0CL4                LS-IN (01 group)
D0002    DS    CL4                 IN-VAL
LS0001   DSECT                     LS-OUT (caller's storage)
D0003    DS    0CL8                LS-OUT (01 group)
D0004    DS    CL4                 OUT-VAL
D0005    DS    CL4                 OUT-TAG
         END
