
#line 1 "picture.rl"
/*! \file picture.rl
 * \brief COBOL PICTURE scanner — Ragel -G2, feeding a hand-written analyser.
 *
 * PICTURE stopped being lexing and became compiling: it has to yield digit
 * count, scale, sign, field width AND the byte pattern for the S/370 ED
 * instruction. That is a small regular language with real semantic output,
 * which is what a state machine is for. The surrounding token stream is still
 * hand-scanned; it has one context flag and no continuation lines, so it does
 * not need this yet.
 *
 * The machine only tokenises. Meaning is assigned in picture.c, so the
 * intricate part -- floating insertion strings, where n sign symbols give
 * n-1 digit positions -- is written in C where it can be read.
 *
 * Build: ragel -G2 -o picture.c picture.rl
 */
#include <stdlib.h>
#include <string.h>
#include "picture.h"

/* The DFA below is generated by Ragel on an ASCII host, so its transition
 * tables are ASCII byte values. On MVS itself (-DMVS370) the picture text
 * arrives in EBCDIC: pic_scan translates it to ASCII for the machine, and
 * every emitted symbol is translated back to the execution character set.
 * The action code parses repeat counts and uppercases with explicit ASCII
 * arithmetic for the same reason -- it always reads the ASCII view. */
#ifdef MVS370
static const unsigned char pic_a2e[95] = {
    0x40,0x5A,0x7F,0x7B,0x5B,0x6C,0x50,0x7D,0x4D,0x5D,0x5C,0x4E,0x6B,0x60,0x4B,0x61,
    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0x7A,0x5E,0x4C,0x7E,0x6E,0x6F,
    0x7C,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,
    0xD7,0xD8,0xD9,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xBA,0xE0,0xBB,0xB0,0x6D,
    0x79,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x91,0x92,0x93,0x94,0x95,0x96,
    0x97,0x98,0x99,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xC0,0x4F,0xD0,0xA1 };
#define PIC_EXEC(c) ((c) >= 0x20 && (c) <= 0x7E ? pic_a2e[(c) - 0x20] : (unsigned char)(c))
static unsigned char pic_e2a[256];
static void pic_e2a_init(void)
{
    int i;
    if (pic_e2a[0x40]) return;
    for (i = 0; i < 256; i++) pic_e2a[i] = 0xFF;      /* not picture text: the DFA rejects it */
    for (i = 0; i < 95; i++) pic_e2a[pic_a2e[i]] = (unsigned char)(0x20 + i);
}
#else
#define PIC_EXEC(c) (c)
#endif

/* ASCII arithmetic on the scanned (always-ASCII) view. */
static int pic_upper(int c) { return c >= 97 && c <= 122 ? c - 32 : c; }
static int pic_rep(const char *q)
{
    int v = 0;
    for (; *q >= 48 && *q <= 57; q++) v = v * 10 + (*q - 48);
    return v;
}


#line 61 "picture_scan.c"
static const int picscan_start = 7;
static const int picscan_first_final = 7;
static const int picscan_error = 0;

static const int picscan_en_main = 7;


#line 60 "picture.rl"


/* Tokenise a PICTURE into (symbol, repeat) pairs.
 * Returns the number of items, or -1 with *errpos set to the offending byte.
 * CR and DB collapse to the single symbols 'C' and 'D'. */
int pic_scan(const char *s, PicItem *out, int max, int *errpos)
{
    const char *p, *pe, *eof;
    const char *ts, *te;
    int cs, act, count = 0;
#ifdef MVS370
    char abuf[256];
    size_t alen = strlen(s), ai;
    if (alen >= sizeof abuf) { *errpos = 0; return -1; }
    pic_e2a_init();
    for (ai = 0; ai <= alen; ai++)
        abuf[ai] = s[ai] ? (char)pic_e2a[(unsigned char)s[ai]] : 0;
    s = abuf;
#endif
    p = s; pe = s + strlen(s); eof = pe;

    *errpos = -1;

    
#line 119 "picture.rl"


    
#line 98 "picture_scan.c"
	{
	cs = picscan_start;
	ts = 0;
	te = 0;
	act = 0;
	}

#line 122 "picture.rl"
    
#line 108 "picture_scan.c"
	{
	if ( p == pe )
		goto _test_eof;
	switch ( cs )
	{
tr0:
#line 98 "picture.rl"
	{{p = ((te))-1;}{
            if (count >= max) { *errpos = (int)(ts - s); return -1; }
            out[count].sym = (char)PIC_EXEC(pic_upper((unsigned char)ts[0]));
            out[count].rep = 1;
            count++;
        }}
	goto st7;
tr2:
#line 91 "picture.rl"
	{te = p+1;{
            if (count >= max) { *errpos = (int)(ts - s); return -1; }
            out[count].sym = (char)PIC_EXEC(pic_upper((unsigned char)ts[0]));
            out[count].rep = pic_rep(ts + 2);
            if (out[count].rep < 1) { *errpos = (int)(ts - s); return -1; }
            count++;
        }}
	goto st7;
tr3:
#line 104 "picture.rl"
	{te = p+1;{
            if (count >= max) { *errpos = (int)(ts - s); return -1; }
            out[count].sym = 'C'; out[count].rep = 1; count++;
        }}
	goto st7;
tr5:
#line 108 "picture.rl"
	{te = p+1;{
            if (count >= max) { *errpos = (int)(ts - s); return -1; }
            out[count].sym = 'D'; out[count].rep = 1; count++;
        }}
	goto st7;
tr11:
#line 98 "picture.rl"
	{te = p;p--;{
            if (count >= max) { *errpos = (int)(ts - s); return -1; }
            out[count].sym = (char)PIC_EXEC(pic_upper((unsigned char)ts[0]));
            out[count].rep = 1;
            count++;
        }}
	goto st7;
st7:
#line 1 "NONE"
	{ts = 0;}
	if ( ++p == pe )
		goto _test_eof7;
case 7:
#line 1 "NONE"
	{ts = p;}
#line 164 "picture_scan.c"
	switch( (*p) ) {
		case 36: goto tr6;
		case 57: goto tr6;
		case 67: goto st3;
		case 68: goto st4;
		case 80: goto tr6;
		case 83: goto tr6;
		case 86: goto tr6;
		case 88: goto tr6;
		case 90: goto tr6;
		case 99: goto st5;
		case 100: goto st6;
		case 112: goto tr6;
		case 115: goto tr6;
		case 118: goto tr6;
		case 120: goto tr6;
		case 122: goto tr6;
	}
	if ( (*p) < 65 ) {
		if ( 42 <= (*p) && (*p) <= 48 )
			goto tr6;
	} else if ( (*p) > 66 ) {
		if ( 97 <= (*p) && (*p) <= 98 )
			goto tr6;
	} else
		goto tr6;
	goto st0;
st0:
cs = 0;
	goto _out;
tr6:
#line 1 "NONE"
	{te = p+1;}
	goto st8;
st8:
	if ( ++p == pe )
		goto _test_eof8;
case 8:
#line 203 "picture_scan.c"
	if ( (*p) == 40 )
		goto st1;
	goto tr11;
st1:
	if ( ++p == pe )
		goto _test_eof1;
case 1:
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st2;
	goto tr0;
st2:
	if ( ++p == pe )
		goto _test_eof2;
case 2:
	if ( (*p) == 41 )
		goto tr2;
	if ( 48 <= (*p) && (*p) <= 57 )
		goto st2;
	goto tr0;
st3:
	if ( ++p == pe )
		goto _test_eof3;
case 3:
	if ( (*p) == 82 )
		goto tr3;
	goto st0;
st4:
	if ( ++p == pe )
		goto _test_eof4;
case 4:
	if ( (*p) == 66 )
		goto tr5;
	goto st0;
st5:
	if ( ++p == pe )
		goto _test_eof5;
case 5:
	if ( (*p) == 114 )
		goto tr3;
	goto st0;
st6:
	if ( ++p == pe )
		goto _test_eof6;
case 6:
	if ( (*p) == 98 )
		goto tr5;
	goto st0;
	}
	_test_eof7: cs = 7; goto _test_eof; 
	_test_eof8: cs = 8; goto _test_eof; 
	_test_eof1: cs = 1; goto _test_eof; 
	_test_eof2: cs = 2; goto _test_eof; 
	_test_eof3: cs = 3; goto _test_eof; 
	_test_eof4: cs = 4; goto _test_eof; 
	_test_eof5: cs = 5; goto _test_eof; 
	_test_eof6: cs = 6; goto _test_eof; 

	_test_eof: {}
	if ( p == eof )
	{
	switch ( cs ) {
	case 8: goto tr11;
	case 1: goto tr0;
	case 2: goto tr0;
	}
	}

	_out: {}
	}

#line 123 "picture.rl"

    (void)act; (void)eof; (void)te;
    if (cs == picscan_error) { *errpos = (int)(p - s); return -1; }
    return count;
}
