/*! \file picture.rl
 * \brief COBOL PICTURE scanner — Ragel -G2, feeding a hand-written analyser.
 *
 * PICTURE stopped being lexing and became compiling: it has to yield digit
 * count, scale, sign, field width AND the byte pattern for the S/370 ED
 * instruction. That is a small regular language with real semantic output,
 * which is what a state machine is for. The surrounding token stream is still
 * hand-scanned; it has one context flag and no continuation lines, so it does
 * not need this yet.
 *
 * The machine only tokenises. Meaning is assigned in picture.c, so the
 * intricate part -- floating insertion strings, where n sign symbols give
 * n-1 digit positions -- is written in C where it can be read.
 *
 * Build: ragel -G2 -o picture.c picture.rl
 */
#include <stdlib.h>
#include <string.h>
#include "picture.h"

/* The DFA below is generated by Ragel on an ASCII host, so its transition
 * tables are ASCII byte values. On MVS itself (-DMVS370) the picture text
 * arrives in EBCDIC: pic_scan translates it to ASCII for the machine, and
 * every emitted symbol is translated back to the execution character set.
 * The action code parses repeat counts and uppercases with explicit ASCII
 * arithmetic for the same reason -- it always reads the ASCII view. */
#ifdef MVS370
static const unsigned char pic_a2e[95] = {
    0x40,0x5A,0x7F,0x7B,0x5B,0x6C,0x50,0x7D,0x4D,0x5D,0x5C,0x4E,0x6B,0x60,0x4B,0x61,
    0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0x7A,0x5E,0x4C,0x7E,0x6E,0x6F,
    0x7C,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,
    0xD7,0xD8,0xD9,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xBA,0xE0,0xBB,0xB0,0x6D,
    0x79,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x91,0x92,0x93,0x94,0x95,0x96,
    0x97,0x98,0x99,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xC0,0x4F,0xD0,0xA1 };
#define PIC_EXEC(c) ((c) >= 0x20 && (c) <= 0x7E ? pic_a2e[(c) - 0x20] : (unsigned char)(c))
static unsigned char pic_e2a[256];
static void pic_e2a_init(void)
{
    int i;
    if (pic_e2a[0x40]) return;
    for (i = 0; i < 256; i++) pic_e2a[i] = 0xFF;      /* not picture text: the DFA rejects it */
    for (i = 0; i < 95; i++) pic_e2a[pic_a2e[i]] = (unsigned char)(0x20 + i);
}
#else
#define PIC_EXEC(c) (c)
#endif

/* ASCII arithmetic on the scanned (always-ASCII) view. */
static int pic_upper(int c) { return c >= 97 && c <= 122 ? c - 32 : c; }
static int pic_rep(const char *q)
{
    int v = 0;
    for (; *q >= 48 && *q <= 57; q++) v = v * 10 + (*q - 48);
    return v;
}

%%{
    machine picscan;
    write data;
}%%

/* Tokenise a PICTURE into (symbol, repeat) pairs.
 * Returns the number of items, or -1 with *errpos set to the offending byte.
 * CR and DB collapse to the single symbols 'C' and 'D'. */
int pic_scan(const char *s, PicItem *out, int max, int *errpos)
{
    const char *p, *pe, *eof;
    const char *ts, *te;
    int cs, act, count = 0;
#ifdef MVS370
    char abuf[256];
    size_t alen = strlen(s), ai;
    if (alen >= sizeof abuf) { *errpos = 0; return -1; }
    pic_e2a_init();
    for (ai = 0; ai <= alen; ai++)
        abuf[ai] = s[ai] ? (char)pic_e2a[(unsigned char)s[ai]] : 0;
    s = abuf;
#endif
    p = s; pe = s + strlen(s); eof = pe;

    *errpos = -1;

    %%{
        # Spelled out rather than as a character class: '-', '/' and '$' all
        # need escaping inside one, and this reads better anyway.
        picsym = '9' | 'Z' | 'z' | 'X' | 'x' | 'A' | 'a' | 'V' | 'v'
               | 'P' | 'p'
               | 'S' | 's' | '*' | ',' | '.' | '/' | 'B' | 'b' | '0'
               | '+' | '$' | '-';

        action emit_rep {
            if (count >= max) { *errpos = (int)(ts - s); return -1; }
            out[count].sym = (char)PIC_EXEC(pic_upper((unsigned char)ts[0]));
            out[count].rep = pic_rep(ts + 2);
            if (out[count].rep < 1) { *errpos = (int)(ts - s); return -1; }
            count++;
        }
        action emit_one {
            if (count >= max) { *errpos = (int)(ts - s); return -1; }
            out[count].sym = (char)PIC_EXEC(pic_upper((unsigned char)ts[0]));
            out[count].rep = 1;
            count++;
        }
        action emit_cr {
            if (count >= max) { *errpos = (int)(ts - s); return -1; }
            out[count].sym = 'C'; out[count].rep = 1; count++;
        }
        action emit_db {
            if (count >= max) { *errpos = (int)(ts - s); return -1; }
            out[count].sym = 'D'; out[count].rep = 1; count++;
        }

        main := |*
            picsym '(' digit+ ')'  => emit_rep;
            ('CR' | 'cr')          => emit_cr;
            ('DB' | 'db')          => emit_db;
            picsym                 => emit_one;
        *|;
    }%%

    %% write init;
    %% write exec;

    (void)act; (void)eof; (void)te;
    if (cs == picscan_error) { *errpos = (int)(p - s); return -1; }
    return count;
}
